### ISSUE TITLE
Unsubscribe art positioning appears stale

### ISSUE THREAD

**Issue by jsoref** [github/docs#10320]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions#unsubscribing-from-notifications-in-your-inbox

### What part(s) of the article would you like to see updated?

This art does not appear to match what I see:
![Drop down](https://docs.github.com/assets/images/help/notifications-v2/unsubscribe-from-main-inbox.png)

For me, the `unsubscribe` and `done` buttons are no longer in a drop down.

---
Edited by maintainer 

Step 3 in [this section](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions#unsubscribing-from-notifications-in-your-inbox) of the article should be replaced with the below screenshot to match current usage.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/33761166/135479212-0492672f-982c-42e7-ac87-4ae616ff11b3.png">

**Comment by ramyaparimi** [comment]
@jsoref We updated the original post of the issue because your description was not clear enough for people to easily understand what needed to be corrected. For some tips to help make things more clear to the people who will read your issues and make it easier for them to fix the problems you care about, see @lee-dohm’s blog post on [writing better bug reports](https://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/).

**Comment by kunaljain0212** [comment]
Can I work on this issue @ramyaparimi?

**Comment by deep8476** [comment]
Android tools

**Comment by ramyaparimi** [comment]
> Can I work on this issue @ramyaparimi?

Yes! Please link your PR to this issues when ready ✨ 🐬
