### ISSUE TITLE
rest/reference/checks: clarification on conclusion `stale`

### ISSUE THREAD

**Issue by jtagcat** [github/docs#10505]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/checks
https://github.com/github/docs/blob/main/content/rest/reference/checks.md

### What part(s) of the article would you like to see updated?

> You cannot change a check run conclusion to stale, only GitHub can set this.

When are checks timed out by GitHub? Does it differ for `queued` and `in_progress`?

### Additional information

If I have a check, that is waiting for code approval in a PR before doing anything, will it go stale?

PRs can be inactive for many years, it's a human / external dependency. Since the value of conclusion is immutable, it needs to be reflected in the status. `status: waiting_dependancy` (bad name) for example.

https://prow.k8s.io, tide is already one of them existing 'pending forever'. (ex https://github.com/kubernetes/website/pull)

***
note to self / bookmark:
[integrating per-path repo write perms gh doesn't have](https://github.com/jtagcat/readonly-codeowner/blob/main/README.md)
(darn it, you can't even grant perms to interact with issues without granting write access to the repo, not even mentioning path-based / codeowners (whitelist))

**Comment by ramyaparimi** [comment]
@jtagcat 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! [Getting started with the Checks API](https://docs.github.com/en/rest/guides/getting-started-with-the-checks-api) (linked to in the intro of [Checks](https://docs.github.com/en/rest/reference/checks)) states:

> If a check run is in a incomplete state for more than 14 days, then the check run's conclusion becomes stale and appears on GitHub as stale

If your check has started but not completed for 14 days due to a missing code approval, I believe it will be marked as stale. If the check will not start until code approval is granted, I don't think it will be marked as stale. You can aways rerun the check once approval is granted. 

I don't think any docs changes are required, so I am going to close this issue.
