### ISSUE TITLE
Discrepancy between `gh auth login` and docs

### ISSUE THREAD

**Issue by BastianZim** [github/docs#10600]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git#github-cli

### What changes are you suggesting?

The `gh auth login` section says:

```markdown
1. Install GitHub CLI on macOS, Windows, or Linux.
2. In the command line, enter gh auth login, then follow the prompts.
  * When prompted for your preferred protocol for Git operations, select HTTPS.
  * When asked if you would like to authenticate to Git with your GitHub credentials, enter Y.
```

Yet when running I'm not promted if I want to authenticate with git:

```zsh
(base)user@computer % gh auth login
? What account do you want to log into? GitHub.com
? You're already logged into github.com. Do you want to re-authenticate? Yes
? What is your preferred protocol for Git operations? HTTPS
? How would you like to authenticate GitHub CLI? Login with a web browser

! First copy your one-time code: code
- Press Enter to open github.com in your browser... 
✓ Authentication complete. Press Enter to continue...

- gh config set -h github.com git_protocol https
✓ Configured git protocol
✓ Logged in as BastianZim
```

### Additional information

Version:
gh version 2.0.0 (2021-08-23)
https://github.com/cli/cli/releases/tag/v2.0.0

Installed through brew.

macOS Big Sur 11.6

**Comment by ramyaparimi** [comment]
@BastianZim

**Comment by mishmanners** [comment]
`gh auth` has now been depreciated:
https://dev.to/github/how-to-never-type-passwords-when-using-git-18bb

This is now to do this now. Docs should reflect this.

**Comment by mishmanners** [comment]
This doc is perfect: https://docs.github.com/en/github-ae@latest/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by BastianZim** [comment]
Are you sure that it's depreciated? Because it doesn't ask for my username and password anymore, it now opens the browser and asks me to log in there.
Additonally, it's well and alive in the `gh` docs and no depreciation notice is given.

**Comment by mislav** [comment]
Hi, GitHub CLI developer here.

I think @mishmanners had a typo; it's not `gh auth` that's deprecated, but git password authentication that's been disallowed on GitHub since a few weeks ago. You may no longer use your GitHub password to authenticate git operations. Note that it already wasn't possible to use your password if your GitHub account was 2FA-enabled.

The article that @mishmanners shared lists several alternative methods of authenticating git with GitHub and `gh auth login` is one of them. As an easier alternative to manually generating a Personal Access Token to use for git, for example, I would recommend using `gh auth login` instead, choosing the "HTTPS" protocol for git, and allowing gh to "authenticate git with your GitHub credentials". This will set up GitHub CLI as your git credential helper (you may inspect that in your `~/.gitconfig`).

@BastianZim The prompt "Authenticate git with your GitHub credentials?" will not show if you already have gh set up as a credential helper for git. Could this be the case?

**Comment by BastianZim** [comment]
That was the case, thanks @mislav. 
In case that's something that the docs team wants to add as a disclaimer I'll keep the issue open but would otherwise close it.

**Comment by lecoursen** [comment]
Thanks everyone, I think this is good to close!
