### ISSUE TITLE
Clarify permission level needed to access secrets

### ISSUE THREAD

**Issue by muru** [github/docs#1087]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

### What part(s) of the article would you like to see updated?

In "Creating encrypted secrets for a repository," it says:

> To create secrets for a user account repository, you must be the repository owner. To create secrets for an organization repository, you must have `admin` access.

However, according to [the API docs](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#secrets):

> Authenticated users must have collaborator access to a repository to create, update, or read secrets.

So, only admins can use the web interface to access secrets, but users with `write` access or above can use the API (directly, or indirectly, e.g., via Terraform). This is in fact the actual behaviour.

### Additional information

This feels like a security issue, since updating secrets via the API involves not much of a record or oversight AFAICT (as opposed to, say, creating a workflow that dumps all secrets, which could leave traces that a bad actor cannot easily remove). I did report it as one, and the response is that this is intentional to allow users with write access to create and maintain workflows (which is understandable and fine by me). However, the current behaviour can be a bit surprising and the docs a bit time-wasting (I would write Terraform code that my org's admin would then apply, when I could have just applied them myself).

**Comment by janiceilene** [comment]
👋 Thanks for opening an issue @muru! Can you clarify what change you'd like to see in the "Creating encrypted secrets for a repository"? Are you hoping a line is added to that article letting folks know that anyone with write+ permissions can use the API to access secrets?

**Comment by muru** [comment]
@janiceilene Hmmm, yes. Or a rephrasing of the whole thing to include the reason for this particular behaviour. Something like:

> Like other repository settings, secrets can be managed from the web interface only by repository owners (for user repositories) or users with `admin` access (for organization repositories). However, to enable developers to create and maintain workflows, users with collaborator access are allowed to use [the API](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#secrets) to manage secrets.

(Or perhaps with the last sentence as a `{% note %}`.)

**Comment by janiceilene** [comment]
👍 Thanks for the clarification @muru! I'll leave it to the team to respond further.

**Comment by runleonarun** [comment]
This sounds great, @muru! I added the "Help wanted" so someone can go ahead and fix this!

**Comment by nomeelnoj** [comment]
What is the goal behind allowing anyone with write access to create/modify secrets? As mentioned above, I agree that this is a security risk.  We have repo admins for a reason, and while others with write access have the ability to merge PRs, they should not be able to affect repo secrets.  It would really be a bummer to have to yank back permissions from people, as then a few key admins would be responsible for merging all pull requests, rather than the authors.

We have a process in place for adding/modifying repo secrets, and with this in place it allows anyone with write access to make changes outside of that process.

**Comment by kbluck** [comment]
I would ask that it go further than updating the docs, but rather that the web behavior conform to the API behavior. It's a little obnoxious that users with suitable write access have to use the API merely to list secrets to find out their names, which are apparently hidden from them on the web interface.

**Comment by janiceilene** [comment]
👋 @kbluck We only own the documentation on docs.github.com in this repo. The best place to send your feedback is to https://support.github.com/contact/feedback 💛

**Comment by GMNGeoffrey** [comment]
So the doc update here was actually wiped out in https://github.com/github/docs/commit/95bd8c84f9, replaced with the much-less-clear "You can use the REST API to manage secrets." (followed by a link to those docs). The permission levels being different between the UI and the API is such an odd thing that it really deserves to be called out. Reading the current documentation, I would never think "oh I'm not an admin, so I can't do this from the UI, but since it says you can manage it from the API maybe I'll look and see if there are totally different access levels there". As @kbluck notes, the real issue here is that there are even different access levels (did you file feedback somewhere?), but given that there are, it would be nice if the docs actually reflected that and it's disappointing that the doc update to fix this bug was effectively reverted

**Comment by nstein-gpjoule** [comment]
> So the doc update here was actually wiped out in [95bd8c84f9](https://github.com/github/docs/commit/95bd8c84f9), replaced with the much-less-clear "You can use the REST API to manage secrets." (followed by a link to those docs). The permission levels being different between the UI and the API is such an odd thing that it really deserves to be called out. Reading the current documentation, I would never think "oh I'm not an admin, so I can't do this from the UI, but since it says you can manage it from the API maybe I'll look and see if there are totally different access levels there". As @kbluck notes, the real issue here is that there are even different access levels (did you file feedback somewhere?), but given that there are, it would be nice if the docs actually reflected that and it's disappointing that the doc update to fix this bug was effectively reverted

A follow up would be great!
@kbluck is there any ticket / issue one can subscribe to?

**Comment by faximan** [comment]
Has behavior here changed?

I believe `gh secret set` worked in the past on repos where I only had write/collaborator access. Now I'm getting

```
failed to fetch public key: HTTP 403: Must have admin rights to Repository.
```
