### ISSUE TITLE
Refine the warning of using PowerShell and UTF-8.

### ISSUE THREAD

**Issue by kristof-mattei** [github/docs#11336]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#environment-files

### What part(s) of the article would you like to see updated?

The PowerShell warning:

```
Warning: Powershell does not use UTF-8 by default. Make sure you write files using the correct encoding. For example, you need to set UTF-8 encoding when you set the path:
```

I think this can be further restricted to `powershell` on `Windows-*`, and explicitly not to `pwsh`, PowerShell Core, on all platforms.

### Additional information

What better way of validating this by running the actual test in GitHub Actions?

Here's a simple workflow I've written which dumps the encodings to files, stores them in a downloadable artifact, and dumps to the console for your viewing pleasure.

The workflow: https://github.com/Kristof-Mattei/powershell-encodings/actions/runs/1366342341

Where it dumps: https://github.com/Kristof-Mattei/powershell-encodings/runs/3959514653?check_suite_focus=true (expand "Display encodings of previously generated files")

You'll notice that only PowerShell on Windows (we can't run it anywhere else) uses `UTF-16LE` by default, unlike `pwsh` on all systems, which yield the good ol' `UTF-8`.

Maybe the documentation needs some refinement pointing this out?

Also, the correct way to spell PowerShell is with a capitalized S, not sure if GitHub has a policy on capitalizing inside names.

**Comment by skedwards88** [comment]
Thank you for opening this issue and providing your validation! You or anyone else is welcome to open a PR to update the warning to say something like `PowerShell on Windows does not use UTF-8 by default` instead of `Powershell does not use UTF-8 by default`. 

You are correct that PowerShell is the correct capitalization. Unfortunately, we are not consistent in the docs. I opened a separate issue to correct the capitalization: https://github.com/github/docs/issues/11811
