### ISSUE TITLE
Welcome to Gboard clipboard, any text you copy will be saved here.

### ISSUE THREAD

**Issue by Whatgraph** [github/docs#11746]
```

```

**Comment by Luiskiing** [comment]
Okay I understand all the requirements that are in the document format

But before continuing with the update platform completion process

I need to have a commission directly for shipping if there was Western
Union or Caribe Express because I am in the Caribbean


Please respond to this message to pass on the personal data to proceed with
the shipment

**Comment by Asesuas** [comment]
What's the publik recorded?

2021-11-06, št 14:51, welcome[bot] ***@***.***> rašė:
