### ISSUE TITLE
`synchronize` event not clear enough

### ISSUE THREAD

**Issue by marcofugaro** [github/docs#12335]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

**pull_request** section of this article

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request

### What part(s) of the article would you like to see updated?

In the article, the pull request events are listed. Among those, the `synchronize` event doesn't have a clear meaning.

I have found out thanks to some forums that it means on push of the PR.

It would be much easier for users if it was clearly explained when it's triggered, like this:

> The `syncronize` event is triggered...

**Comment by ramyaparimi** [comment]
@marcofugaro 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by marcofugaro** [comment]
Ho, I just found out that the `synchronize` event is not triggered if the PR has conflicts. You probably want to explicitly document this.

**Comment by skedwards88** [comment]
Thanks for opening this issue! We have some internal improvements to this article in progress that should address this issue (and that should make it more clear that you can find more info about the event activity types in the webhook event docs: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request).

Since this is being addressed internally, I am going to close this issue.

**Comment by marcofugaro** [comment]
Thanks @skedwards88.

Any idea about what event to use to run an action on any commit push on the PR?

I am using this to deploy a PR preview, but it doesn't get triggered if the PR has conflicts.

```yaml
on:
  pull_request:
    types: [opened, synchronize]
```

I can't use the `push` event because I need the `github.event.pull_request` info.
