### ISSUE TITLE
GitHub App Guide typo

### ISSUE THREAD

**Issue by rsese** [github/docs#129]
### Issue overview

Hiyo :wave:!  User reporting a typo in https://developer.github.com/apps/quickstart-guides/setting-up-your-development-environment/#step-4-prepare-the-runtime-environment:

> I noticed a typo in the Developer Docs: https://developer.github.com/apps/quickstart-guides/setting-up-your-development-environment/
> 
> In Step 4, in the example `.env` file at the end, `PRIVATE_KEY` should be `GITHUB_PRIVATE_KEY`

So this is the example `.env` file at the end of step 4.

I think they're right?  The template code to start from that we mention in the `Prerequisites` section uses `GITHUB_PRIVATE_KEY`:

https://github.com/github-developer/github-app-template/blob/d73485c3ef88d351fbd45b11666c045b319f7f49/.env-example#L1

### Products affected by this issue

- [ ] REST API
- [ ] GraphQL API
- [ ] Apps
- [ ] GitHub Actions
- [ ] GitHub Marketplace
- [ ] Webhooks

/cc @github/product-docs-ecosystem

**Comment by casals** [comment]
It's not possible to edit this page (hosted at https://developer.github.com) at the moment since it was deprecated in favor of https://docs.github.com/apps/quickstart-guides/setting-up-your-development-environment/ . The new page has the right text (`GITHUB_PRIVATE_KEY` on Step 4). I suggest either closing this issue or referencing it to the internal team.

**Comment by janiceilene** [comment]
Thanks for looking into that @rsese! @github/docs-content-ecosystem Can we close this issue?

**Comment by jmarlena** [comment]
Yes, we can close this issue.
