### ISSUE TITLE
markdown ifversion bleeding into user view for workflow-syntax-for-github-actions example-3

### ISSUE THREAD

**Issue by jsoref** [github/docs#13040]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-3

### What part(s) of the article would you like to see updated?

The `{% ifversion ... %}` content shouldn't be rendered to end users, it appears like this to me:

```
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' {% ifversion ghec or ghes > 3.3 or ghae-issue-5511 %}
        type: choice
        options:
        - info
        - warning
        - debug {% endif %}
      tags:
        description: 'Test scenario tags'
        required: false {% ifversion ghec or ghes > 3.3 or ghae-issue-5511 %}
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true {% endif %}
  
jobs:
  print-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input tag to STDOUT
        run: echo The tag is ${{ github.event.inputs.tag }}
```

<details><summary>Click for an image showing the problem...</summary>

![image](https://user-images.githubusercontent.com/2119212/146307392-d584e74d-526a-46a8-b01c-1356258731d6.png)

</details>

### Additional information

I think this was introduced by: https://github.com/github/docs/commit/ad605a410ce12b95c4f8d30e4e1de01a9767bb91

----
_Added by a maintainer_

## Content design plan

The condition that's being wrongly displayed in the example was added by the commit highlighted by @jsoref. This condition originally worked as intended, however, a later commit added [`{% raw %}`](https://github.com/github/docs-internal/blob/main/contributing/content-style-guide.md#code-blocks) tags around the whole example. This stopped the liquid versioning being parsed and means that it is now displayed.

You can fix this problem by moving the `{% raw %}` and `{% endraw %}` tags into the example, so that they just enclose `${{ github.event.inputs.tag }}` on line 329 instead of the whole example. As shown in the style guide example: https://github.com/github/docs-internal/blob/main/contributing/content-style-guide.md#code-blocks).

**Comment by ramyaparimi** [comment]
@jsoref Thank you for opening this issue. We appreciate how you clearly mentioned what the issue is with screenshot and what could have caused it. I will get this triaged for a writers review 👀

**Comment by felicitymay** [comment]
Hi @jsoref - thanks for flagging this.

I'm a little puzzled by this bug because I can see that this syntax usually works as expected (see [source](https://github.com/github/docs-internal/blob/f10bfad7bdce4d0086243eb188356a1f5846f021/content/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning.md?plain=1#L250-L253) and output [Configuring code scanning - Analyzing Python dependencies](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#analyzing-python-dependencies)).

I'll ask docs engineering to take a look as it seems like it may be a rendering bug rather than a bug in the source file.

**Comment by felicitymay** [comment]
It looks as if after the PR that you spotted was merged, a later PR added [`{% raw %}`](https://github.com/github/docs-internal/blob/main/contributing/content-style-guide.md#code-blocks) tags around the whole example. This stops the liquid versioning being parsed.

This issue can be fixed by moving the `{% raw %}` and `{% endraw %}` tags so that they just enclose `${{ github.event.inputs.tag }}` on line 329 instead of the whole example. As shown in the example in the style guide.

Is this something you're able to fix? If not, I'll update the description of the issue and add a `help wanted` label.

**Comment by Desires4** [comment]
reading over there some good points dont see no need to change anything

**Comment by jsoref** [comment]
Looks like some refresh fixed it. My guess is a version bump for Enterprise. (Google still remembers a localization with this error, so it was fairly recent.)

**Comment by felicitymay** [comment]
@jsoref - thank you for checking up and closing this. It's much appreciated ✨

**Comment by Desires4** [comment]
Don't close this one let me Work with you on this project tell me what you
need

**Comment by Mason1555** [comment]
I need a project
