### ISSUE TITLE
Custom Domain for GitHub Pages: clarify what values to use for DNS records (ALIAS etc., CNAME)

### ISSUE THREAD

**Issue by alzafacon** [github/docs#13645]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

### What part(s) of the article would you like to see updated?

Docs imply the Host value for CNAME records is `www.example.com`. For example "create a CNAME record that points `www.example.com` to `<user>.github.io`". But the correct Host value is `www`. Instead "create a CNAME record that points `www` to `<user>.github.io.`" could be better (also notice the `.` I added after `<user>.github.io`).

Similarly "To create an `ALIAS` or `ANAME` record, point your apex domain to the default domain for your site." implies the Host value is the apex domain but actually the Host value should be `@`.

### Additional information

The docs already recommend the user to check their DNS providers documentation for details on setting up DNS records. Since the specific Host values could differ from provider to provider.

However I think the docs could be better if the wrong Host values were not implied, either by stating the correct values inline or clearly showing the values of the DNS records, for example:

|ALIAS record|value|
|-|-|
| Host | @ |
|Target  | \<user\>.github.io. |

**Comment by pastasonica** [comment]
.

**Comment by ramyaparimi** [comment]
@alzafacon 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
We appreciate you taking the time to write up this issue and provide all the relative information. ✨ 

I’ve spoken with our team. We kept the language here fairly general since it is different for each provider. The ultimate goal is a CNAME that points [www.example.com](http://www.example.com/)  at <user>.[github.io](http://github.io/) , so we will not be changing the documentation around it. 

Thank you again for your passion in improving GitHub Docs! 💖
