### ISSUE TITLE
Lighthouse issues on docs.github.com

### ISSUE THREAD

**Issue by heiskr** [github/docs#141]
I ran [Lighthouse](https://developers.google.com/web/tools/lighthouse/) on a few pages on docs.github.com, here's some opportunities for us from that:

- [x] Our DOM is excessively large, with the left navigation having over 2400 elements. [Difficult]
- [x] `/javascripts/index.js` has a cache time of 1 minute. If we had a longer cache time, the performance of the page would be slightly higher.  [Difficult]
- [x] `btn-mktg` and `btn-outline-mktg` doesn't meet contrast requirements
- [ ] [aria-hidden="true"] elements contain focusable descendents [Easy]
- [x] Heading elements are not sequentially ordered. [Easy]
  Appears to be from the right sidebar, the `h4` need to be `h3`.
- [x] Form elements missing labels. [Medium]
  I think this might be the search?
- [x] The octicon link in the upper left corner has no name for screenreaders.
- [x] All pages are missing `<!doctype html>` and `<meta charSet="utf-8">`
- [ ] Many pages are missing meta descriptions [Difficult]
- [x] The searching octocat SVG is pretty heavy on the page, and looks like the markup hasn't been optimized.
- [ ] Add `rel="noopener"` to external links, including https://github.com [Easy]

**Comment by TomerPacific** [comment]
@heiskr , I'd like to help. Since this issue notes several problems, I'd appreciate it if you would clarify what would be the definition of done.

**Comment by heiskr** [comment]
@TomerPacific We'd love to get some help clearing out some of these issues :) I would consider this to be done when Lighthouse no longer reports errors on our site, and all four scores are >=95.

Some of these are much easier than others. I've added some labels for the level of effort I think each of these are.

**Comment by TomerPacific** [comment]
@heiskr , got it. I'll start with the easy tasks and make my way from there.

**Comment by TomerPacific** [comment]
@heiskr , regarding the [aria-hidden="true"] elements, what would you like done? The guide from lighthouse suggests adding a hidden attribute to inner elements, but that will not have the desired effect.

**Comment by chiedo** [comment]
This would be a great issue for someone from the community to work on if they're interested!

**Comment by janiceilene** [comment]
@chiedo I'm going to add it over to the "available issues" column and toss on a `help wanted` label. Feel free to move it back if that's not where you'd like it to live!

**Comment by chiedo** [comment]
Thank you @janiceilene ! And noted ✅  for the future

**Comment by Rarajb79** [comment]
[eaa687b7-0ce2-4423-b115-12218c32be97.txt](https://github.com/github/docs/files/6178014/eaa687b7-0ce2-4423-b115-12218c32be97.txt)

**Comment by Rarajb79** [comment]
> @
[google_terms_of_service_en.pdf](https://github.com/github/docs/files/6178063/google_terms_of_service_en.pdf)

**Comment by mehdi40277** [comment]
[https://github.com/github/docs/pull/5987#issuecomment-831698523](https://github.com/github/docs/pull/5987#issuecomment-831698523) At the time of the initial coding, I defined using a formula that had numerical coordinates and each currency code had a unique identity, and at the same time was operating cash under the pseudonym Satoshi Nakamoto. And my goal The induction of banking stability cryptocurrency was created to elevate a revolution in the attitude of the central treasury and the monetary organization, and the idea of ​​creating each sell was in line with a coding program that would create economic transparency in the world and provide financial security to capital owners. Every human being has a new vision and a true belief that the honesty of the thoughts that originate leads the heart to the reasoning of the metaphysical science of the brain. During these several years since the birth of this financial system, many people have abused my position and name and shown themselves in my place. Wow, the growth attitude is to induce the removal of Satoshi Nakamoto and name an identity that, if his name produced an economic revolution, stemmed only from faith and God's direct connection to the intrinsic intellect and intuition that served human society. But I can no longer bear that Such capital that using the sciences of God This kind of plunder is created by opportunists who try to shake this illusion from the darkest parts of everything. The goal is to create the attitude of the birth of superior minds to leave a legacy to the future, as our past left us. In fact, man The further it goes, the closer it actually gets to the past of its predecessors, and this means that we will exist again and again in nature, but with a different appearance and mask that we choose. So the new revolution is the attitude of Bitcoin today towards It starts a new one, and that is creating the business balance of an economic act in relation to certain times, such as the coronary heart disease epidemic in the world, which with this excellence creates the confidence of capital owners in times of such problems and disasters and the existence of Bitcoin financial insurance. The title of Quinn Insurance, which is based on stock exchange transactions, of course, depending on the type of problem, for example, during major illness, the activity to provide medicine, vaccines and items needed by human societies, because the growth of a nation is only when that nation is equal to gender and Race to know that humans based on reason and Judy is judged, not visually. So my friends, brothers, sisters and masters. I once again, as a service to you, proves the motivation of time and not language. So my heart is the place of love and wealth that you have in your heart and You give it to your fellow man with a smile. You are your real wealth. Love is believed to be a seedling in the existence of every hero.

**Comment by heiskr** [comment]
I've rerun Lighthouse on a few pages and removed everything that it no longer reports.

It looks like this one weighs heavier than before, so this would be our highest priority item on this list:

> Add rel="noopener" to external links, including https://github.com [Easy]

This would be great for an open source contributor to help us with!

**Comment by Evavic44** [comment]
> I've rerun Lighthouse on a few pages and removed everything that it no longer reports.
> 
> It looks like this one weighs heavier than before, so this would be our highest priority item on this list:
> 
> > Add rel="noopener" to external links, including https://github.com [Easy]
> 
> This would be great for an open source contributor to help us with!

Hello @heiskr, I would love to work on this issue. Can you please specify the location of the `.html` file the changes are needed? This is my first time contributing to GitHub. Thank you.

**Comment by heiskr** [comment]
Hi @Evavic44 , there's many places we generate links, so realistically we would need to do this in browser JavaScript, at least for the short term. Something like `document.querySelectorAll('a[href^=http], a[href^="//"]')` would probably catch all the external links.
