### ISSUE TITLE
Inconsistent use of pattern matching

### ISSUE THREAD

**Issue by jackton1** [github/docs#15238]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

### What changes are you suggesting?

There seems to be a bug with the pattern matching syntax outlined in the docs.

Pattern | Description of matches | Example matches
-- | -- | --
'*.jsx?' | The ? character matches zero or one of the preceding character. | page.js page.jsx

`*.jsx?` doesn't match `.js|jsx` files as seen in the output below

## CURRENT

```
> const glob = require("@actions/glob");
undefined
> const files = "*.jsx?"
undefined
> const globOptions = {followSymbolicLinks: true};
undefined
> const globber = await glob.create(files, globOptions);
::debug::followSymbolicLinks 'true'
undefined
> let paths = await globber.glob();
::debug::followSymbolicLinks 'true'
::debug::implicitDescendants 'true'
::debug::matchDirectories 'true'
::debug::omitBrokenSymbolicLinks 'true'
::debug::Search path '/.../workspace/glob'
undefined
> paths
[]
```

## WORKAROUND

```
> const glob = require("@actions/glob");
undefined
> const files = "*.jsx\n*.js";
undefined
> const globOptions = {followSymbolicLinks: true};
undefined
> const globber = await glob.create(files, globOptions);
::debug::followSymbolicLinks 'true'
undefined
> let paths = await globber.glob();
::debug::followSymbolicLinks 'true'
::debug::implicitDescendants 'true'
::debug::matchDirectories 'true'
::debug::omitBrokenSymbolicLinks 'true'
::debug::Search path '/.../workspace/glob'
undefined
> paths
[
  '/.../workspace/glob/test.js',
  '/.../workspace/glob/test.jsx',
]
```

**Comment by ramyaparimi** [comment]
@jackton1 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
👋 @jackton1 Thanks for opening this issue!

The syntax [that is in the docs is correct for Actions workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths). It looks like in your example you are using the `@actions/glob` package from the Actions toolkit. In some situations, the toolkit package's globbing behaves differently from workflow syntax globbing.

Because the docs are currently correct for the workflow syntax, I'll close this issue. Feel free to open an issue in the [Actions toolkit repo](https://github.com/actions/toolkit), or give the [product team feedback on GitHub discussions](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback).

**Comment by jackton1** [comment]
@lucascosti Thanks for clearing this up, I’m also curious what package is used for handling the action workflows?

**Comment by lucascosti** [comment]
> @lucascosti Thanks for clearing this up, I’m also curious what package is used for handling the action workflows?

IIRC, it's internally developed code and isn't using a separate package.
