### ISSUE TITLE
Confusing headings in "Configuring the private fork policy for a repository"

### ISSUE THREAD

**Issue by oraclown** [github/docs#15265]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks

### What part(s) of the article would you like to see updated?

The picture under  Step 4 "Under Fork pull request workflows, select your options. For example:" contains an option to make repository secrets available to fork PR workflows, when this is no longer an option. Confusing.

### Additional information

[Here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) is another doc that makes clear this is no longer an option.

I stumbled on this confusing mismatch because tests are failing since the secrets aren't available for a contributor's [PR](https://github.com/tellor-io/telliot-core/runs/5112540322?check_suite_focus=true).

---
_Update from a maintainer_

After discussion (see comments below), we realized that the article is correct but that the headings are confusing. 

### Recommended updates to the article

1. Change heading "Configuring required approval for workflows from public forks" to "Controlling changes from forks to workflows in public repositories".
2. Change heading "Enabling workflows for private repository forks" to "Enabling workflows for forks of private repositories"
3. Change heading "Configuring the private fork policy for a repository" to "Configuring the fork policy for a private repository"

**Comment by ramyaparimi** [comment]
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
@oraclown - many thanks for reporting this bug in the docs. It sounds as if we overlooked this article the last time the UI was revised. I'm going to check our internal issues to see whether any other articles are affected before recommending steps to fix this problem.

**Comment by felicitymay** [comment]
@oraclown - I asked about this and discovered that the [procedure you mention](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks) is only available for _private_ repositories and not public repositories. The repository you link to is a public repository, so I think this is why you don't see these options.

The section of that article that describes the options for _public_ repositories is: [Configuring required approval for workflows from public forks](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-required-approval-for-workflows-from-public-forks).

I think that the headings in this article are confusing because it's not clear that we're talking about the visibility of the parent repository and not the fork.

I suggest we update the article as follows:

1. Change heading "Configuring required approval for workflows from public forks" to "Controlling changes from forks to workflows in public repositories".
2. Change heading "Enabling workflows for private repository forks" to "Enabling workflows for forks of private repositories"
3. Change heading "Configuring the private fork policy for a repository" to "Configuring the fork policy for a private repository"

**Comment by felicitymay** [comment]
Great - I'll update the issue summary accordingly and add a `help wanted` label.

**Comment by felicitymay** [comment]
@oraclown - thank you for raising this issue to highlight the confusing headings in this article ✨

**Comment by MRHACKERSadmin** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks
> 
> ### What part(s) of the article would you like to see updated?
> The picture under Step 4 "Under Fork pull request workflows, select your options. For example:" contains an option to make repository secrets available to fork PR workflows, when this is no longer an option. Confusing.
> 
> ### Additional information
> [Here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) is another doc that makes clear this is no longer an option.
> 
> I stumbled on this confusing mismatch because tests are failing since the secrets aren't available for a contributor's [PR](https://github.com/tellor-io/telliot-core/runs/5112540322?check_suite_focus=true).
> 
> _Update from a maintainer_
> 
> After discussion (see comments below), we realized that the article is correct but that the headings are confusing.
> 
> ### Recommended updates to the article
> 1. Change heading "Configuring required approval for workflows from public forks" to "Controlling changes from forks to workflows in public repositories".
> 2. Change heading "Enabling workflows for private repository forks" to "Enabling workflows for forks of private repositories"
> 3. Change heading "Configuring the private fork policy for a repository" to "Configuring the fork policy for a private repository"
