### ISSUE TITLE
branch protection documents don't talk about `conflict`s between protection rules

### ISSUE THREAD

**Issue by jsoref** [github/docs#15965]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#about-branch-protection-rules

### What part(s) of the article would you like to see updated?

Something should mention that one can't have two branch protection rules that match the same branch, or if one can, it should explain how priority works.

Searching for `conflict` only shows hits for `merge conflict`.

Note: it appears impossible to deep link to any of the steps in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule which means I can't link to:

> Under "Branch name pattern", type the branch name or pattern you want to protect.

Offhand, text should probably be included here warning that one should work to avoid having patterns in branch protection rules that conflict.

### Additional information

https://github.com/github/feedback/discussions/12257

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @jsoref, I believe the answer to your question is here:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#about-branch-protection-rules

>If a repository has multiple protected branch rules that affect the same branches, the rules that include a specific branch name have the highest priority. If there is more than one protected branch rule that references the same specific branch name, then the branch rule created first will have higher priority.

Was there something else you had in mind?

>Offhand, text should probably be included here warning that one should work to avoid having patterns in branch protection rules that conflict.

I don't think this is something we would recommend.

**Comment by jsoref** [comment]
Interesting, then why does the UI tell me I have a conflict?

At the very least, that text should have the word `conflict` so that users hitting the error message can find the documentation.

**Comment by lecoursen** [comment]
Great question! I agree that we could address what that "conflict" means in the UI... but I must admit, I don't actually know. Let's see if we get some answers in that feedback issue, so we know what to add.

**Comment by MAC-ARTHUR-TRUE** [comment]
Madison chambers or Chamberlin POW MIA Afghanistan IRAC,  impersonated by Pamela mceandry, calling themselves Steve and Mary Female identity change to Paris Pichai or Pichilli Apaguasa. Secured identity with "memory" software accounts of DreamWorks high jacked used against her by known criminals and theives.Stalking of female documented with federal restraining order permanent. Paris 304 663 4110 Sent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/28/22  15:53  (GMT-05:00) To: ***@***.*** Subject: FW: Urgent HelpSent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/28/22  3:51 PM  (GMT-05:00) To: ***@***.*** Subject: FW: Urgent Data pushesMasked ipPhone info changesAll obsevedSent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/24/22  12:07 AM  (GMT-05:00) To: ***@***.*** Subject: Urgent Crime Sent from my  U.S.Cellular© SmartphoneSent from my  U.S.Cellular© Smartphone
-------- Original message --------From: Josh Soref ***@***.***> Date: 3/3/22  14:12  (GMT-05:00) To: github/docs ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [github/docs] branch protection documents don't talk about `conflict`s between protection rules (Issue #15965) 
Interesting, then why does the UI tell me I have a conflict?
At the very least, that text should have the word conflict so that users hitting the error message can find the documentation.

**Comment by WHOAMIaGAINcarolGUTZ** [comment]
Hello Everyone! Do you happen to know me? Just asking. Carol 226 McDougal

**Comment by jsoref** [comment]
@lecoursen not even a nibble

**Comment by jsoref** [comment]
@cmwilson21 can you please find someone who could comment?
