### ISSUE TITLE
Separate build & test Node.js or Python

### ISSUE THREAD

**Issue by KonradHoeffner** [github/docs#16219]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python

### What part(s) of the article would you like to see updated?

Right now, Node.js and Python are included in the same article while for example Ruby and Swift each have their own article.
While it makes sense to combine Java and Gradle, Node.js and Python are unrelated and should be separated.

**Comment by MAFIAWA** [comment]
![Uploading FB_IMG_1640286732966.jpg…]()

**Comment by KonradHoeffner** [comment]
@MAFIAWA: Unfortunately, I cannot open the image link you provided, it links back to this issue. Was the upload cancelled?

**Comment by ramyaparimi** [comment]
@KonradHoeffner 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by janiceilene** [comment]
👋 @KonradHoeffner Thanks for opening an issue and sorry about that confusion! The article you're looking at is a long running experiment to see how users interact with the side by side layout. We were also experimenting with the buttons to switch between languages, which is why these two are combined. 

If you'd like to see the original separated articles, they're available at:

- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

Let us know if you have any additional questions or confusion!

**Comment by KonradHoeffner** [comment]
Thanks for the clarification! It works perfectly fine I was just confused why the two unrelated topics are combined in one article but I understand that.
