### ISSUE TITLE
Github add ssh key Mac docs incomplete

### ISSUE THREAD

**Issue by hak33m16** [github/docs#17514]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Specifically the mac documentation here: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

After following all instructions in the guide for adding a new key on a brand new Mac on Monterey, you'll see:
```
The authenticity of host 'github.com (140.82.114.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Even though the user continues, the connection still fails

### What part(s) of the article would you like to see updated?

A section should be added that informs users they need to add github to their known_hosts file (see the top answer here: https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository)

**Comment by FreeSoftwareFiles1** [comment]
A lot of people failed at what you accomplished, simply because they were busy finding problems while you were busy finding solutions. Well done.
[Adobe Photoshop 2020 Free Download](https://freesoftwarefiles.net/photo-editing/adobe-photoshop-2022-free-download/)
[Windows 11 Download](https://freesoftwarefiles.net/operating-systems/windows-11-iso-free-download/)
[Windows 10 Download](https://freesoftwarefiles.net/operating-systems/windows-10-download/)
[MS Office 2021 Free Download](https://freesoftwarefiles.net/office-tools/microsoft-office-2021-professional-plus-free-download)
[GTA 5 Free Download](https://www.apunkagamees.com/gta-5-free-download/)
[GTA 5 Free Download](https://www.apunkagamee.com/gta-5-free-download/)
[Cyberpunk 2077](https://www.apunkagamee.com/cyberpunk-2077-free-download/)
[Cyberpunk 2077](https://www.apunkagamees.com/cyberpunk-2077-free-download/)
[ApunKaGames](https://www.apunkagamees.com)
[ApunKaGames](https://www.apunkagamee.com)

**Comment by Lite-i-c-t-c-HH-hol-D-H-i-a-M-en-H-i-Gi** [comment]
https://drive.google.com/file/d/1AyTn2c8cb8P1M6Q6K4PxyvTpuStJ5HGM/view?usp=drivesdk
aloha-world

**Comment by Lite-i-c-t-c-HH-hol-D-H-i-a-M-en-H-i-Gi** [comment]
*kiss*√

**Comment by mattpollard** [comment]
👋🏻 Hi from the Docs team, @hak33m16. Thanks for your patience while we got to your issue.

The output you shared shows that GitHub.com's host key wasn't accepted when the connection was first attempted on the workstation.

```
...
Host key verification failed.
...
```

Accepting the host key by typing `yes` and pressing Return after your client asks...

```
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

...will add GitHub.com to the _known_hosts_ file and allow a connection.

It sounds like you've solved the issue with some assistance from Stack Overflow, which is great 🙌🏻 Since the SSH client's prompt asks you to confirm your connection and then acts accordingly, we won't change the documentation for now. Let us know if you have further requests 🙏🏻
