### ISSUE TITLE
Mathjax render is not working when in a list.

### ISSUE THREAD

**Issue by flying-yogurt** [github/docs#18125]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

### What part(s) of the article would you like to see updated?

The math expression works fine in markdown files most of time. But sometimes formulas are not displayed correctly in unordered lists. For example:

This $O(n)$ works fine when out of the list.
- A: xxx
- B: xxx
- C: but this one not $O(n)$.
- D: xxx

**Comment by pwelke** [comment]
The same problem persists for ordered lists: 

1. this is fine
2. here's a bug: $O(n^2)$

**Comment by janiceilene** [comment]
Thanks for opening an issue @flying-yogurt and for adding additional context @pwelke! The best place to give product feedback is in the new feedback discussions https://github.com/github/feedback/discussions 💛 

Since there aren't any changes to make in the docs at the moment, I'm going to close this issue now. Thanks so much for your interest in improving the GitHub Docs!
