### ISSUE TITLE
Document how to reference a label in GitHub-flavored Markdown

### ISSUE THREAD

**Issue by TonyGravagno** [github/docs#18537]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

### What part(s) of the article would you like to see updated?

[#referencing-issues-and-pull-requests](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#referencing-issues-and-pull-requests)

I propose adding a new section here, "Referencing Labels". This feature is not directly supported by Github, but it is possible in a standard manner with a feature provided by shields.io. For example: ![label: github/docs/labels/content](https://img.shields.io/github/labels/github/docs/content) is created with image link:    
`![label: Content](https://img.shields.io/github/labels/github/docs/content)`

Documentation: https://shields.io/category/issue-tracking -  See and click topic 'GitHub labels'.

Because this is dynamically generated, the color of the image is always accurate at the time of rendering/viewing, not just at the time of text entry. The alt text covers for missing images or communications issues.

As this is a useful and [requested](https://github.com/isaacs/github/issues/305) feature, I think it would be helpful to add the suggestion to the doc, even if the feature is not built-in to Github itself. If the shields.io service goes away, Github will have much greater issues than this one feature, and the doc can be modified as required.

TY

### Additional information

On approval, I'll submit a PR for the new content.

Someone may suggest adding notes about shields for milestones and other features supported by shields.io. I suggest we process this one request first and consider other such requests on their own merits.

**Comment by PythonCoderAS** [comment]
I don't think this is allowed because shields.io is a third-party service.

**Comment by TonyGravagno** [comment]
> I don't think this is allowed because shields.io is a third-party service.

Thanks for the challenge...

- There's no reason not to reference another site. Other sites are mentioned in these docs for similar purposes.
- In particular, shields.io site is not competitive with Github or Microsoft.
- There is no endorsement or implication of affiliation with a reference to that site.
- That site is non-commercial, publicly supported, and entirely based on the [badges/shields](https://github.com/badges/shields) FOSS hosted here at Github.
- It's not a volatile link. There are 5.7 million instances in Github public repo code where shields.io is already used for dynamic and static badges. The suggestion here is simply to document the established standard for what people already do, and change it later in the almost certain never to happen scenario where the site changes.
- [This doc page](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) documents how to add a dynamic badge for workflow, using data from this site as the source. Because this site doesn't document how to use other dynamic data that is readily available, people in the FOSS community filled the gap. That saved Github/Microsoft some effort and should be rewarded with a reciprocal gesture of recognition. Let's document how to get the data from github.com directly, if it's possible, or, let's document where we know people can use this existing functionality. It's just data.

Ref functionality supported by the Github API, [implemented](https://github.com/badges/shields/commit/9c5ecc2c2dfc6e8410b83e0aadc93c43e50f52f2) in the badge/shields project FOSS (source for shields.io).

See also the [badges/shields PR](https://github.com/badges/shields/pull/3902) for this.

Ping @pfaion @calebcartwright

**Comment by PythonCoderAS** [comment]
@TonyGravagno let me be clear, the issue is describing it enough that it seems to be official. I was thinking something that would be acceptable could be a sentence that just reads "Third-party services like `shields.io` allow dynamically creating images of repository labels."

**Comment by TonyGravagno** [comment]
I agree that would be ideal and I will ensure it's presented like this if the enhancement is approved. Thanks.

**Comment by janiceilene** [comment]
👋 Thanks so much for opening an issue and clearly explaining your reasoning @TonyGravagno! Since this isn't a GitHub feature and is a totally optional thing that users can choose to add if they're interested, we're not going to add it to the docs 💛 

Thank you for your interest and passion in improving the GitHub docs! ✨

**Comment by styfle** [comment]
It seems like GitHub must have a native way to do this because I'm seeing it in this PR: https://github.com/nodejs/node/pull/43310

<img width="910" alt="image" src="https://user-images.githubusercontent.com/229881/174301860-ac330112-b5b5-462b-b01a-c6ae4fef5557.png">

I'm not seeing this feature documented however so perhaps its beta? 🤔

**Comment by PythonCoderAS** [comment]
> It seems like GitHub must have a native way to do this because I'm seeing it in this PR: [nodejs/node#43310](https://github.com/nodejs/node/pull/43310)
> 
> <img alt="image" width="910" src="https://user-images.githubusercontent.com/229881/174301860-ac330112-b5b5-462b-b01a-c6ae4fef5557.png">
> 
> I'm not seeing this feature documented however so perhaps its beta? 🤔

Oh it's simple, just put in a normal link to the label. For example:

```md
https://github.com/github/docs/labels/content
```

-> https://github.com/github/docs/labels/content

**Comment by styfle** [comment]
Cool! I don't see that documented though.

Perhaps it should be added to [Autolinked References and URLs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)

**Comment by PythonCoderAS** [comment]
Maybe open a different issue for that?

**Comment by Sakhilemasina** [comment]
is my job application to glassdoor successful?

**Comment by styfle** [comment]
I created #18704

**Comment by xamidi** [comment]
> Oh it's simple, just put in a normal link to the label. For example:
> 
> https://github.com/github/docs/labels/content
> 
> -> [ content](https://github.com/github/docs/labels/content) This issue or pull request belongs to the Docs Content team

https://github.com/xamidi/pmGenerator/labels/challenge

That's really cool!

I'd like to mention that in case someone wishes to show labels **outside of the repo** that defines them, and (like me) dislikes that `https://img.shields.io/` distorts color and shape of labels, it still can be done.

For example, `https://img.shields.io/github/labels/xamidi/pmGenerator/challenge` is  
[![challenge](https://img.shields.io/github/labels/xamidi/pmGenerator/challenge)](https://img.shields.io/github/labels/xamidi/pmGenerator/challenge),  
but (as in https://github.com/xamidi/pmGenerator/discussions/2) it should be  
[![challenge](https://github.com/user-attachments/assets/4834ecaf-0030-4b26-bb6e-3fa2d8aefa7c)](https://github.com/user-attachments/assets/4834ecaf-0030-4b26-bb6e-3fa2d8aefa7c).

I simply uploaded and linked an SVG
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="63" height="20" role="img" aria-label="challenge">
  <title>challenge</title>
  <g>
    <rect width="63" height="20" fill="#ffcb00" rx="10"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
    <text x="315" y="140" transform="scale(.1)" fill="#333" textLength="530">challenge</text>
  </g>
</svg>
```
to and from this comment.

I took color and dimensions from `img.shields.io`'s code (where color distortion is only due to some `linearGradient` overlay).
