### ISSUE TITLE
Missing Mastering Markdown page (that redirects to Basic Formatting) 

### ISSUE THREAD

**Issue by Veylkh** [github/docs#20424]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### At:
 Get started / Writing on GitHub / Start writing on GitHub / Write & format on GitHub / 

### Both:
- About writing and formatting on GitHub #[Further Readings](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github#further-reading)
- Basic writing and formatting syntax #[Further Readings](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#further-reading)

### What part(s) of the article would you like to see updated?

_I suppose this is (or was intended to be) temporary. But I'm still submitting, just in case that it's not._

At these Markdown formatting pages, the bottom [Further Readings](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#further-reading) has the **Mastering Markdown** link to redirect on the Basic Formatting page (in place of a Mastering Markdown page).

**Comment by cmwilson21** [comment]
@Veylkh Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by jc-clark** [comment]
Thanks for the report @Veylkh. We met about this as a team decided on two next actions: 

- In [About writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github#further-reading), delete the entire "Mastering Markdown" line since the correct article is already linked in the list as "[Basic writing and formatting syntax](https://docs.github.com/en/articles/basic-writing-and-formatting-syntax)"
   <img width="457" alt="image" src="https://user-images.githubusercontent.com/31087804/188701589-677c4143-4816-4720-8954-f4676c0c6301.png">
- In [Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#further-reading), delete the entire "Mastering Markdown" line. 
   <img width="426" alt="image" src="https://user-images.githubusercontent.com/31087804/188702382-d4463944-3fd7-4d5b-80f8-c9a0eb3069c0.png">
   
You or anyone else can open the pull request to make these changes. Let us know if you have any more questions!

**Comment by Veylkh** [comment]
Thank you for the replies.

@jc-clark Are you sure that, at some point, there wasn't a (possibly planned) recipient for this link? Such as another article in the docs or external references.

**Comment by jc-clark** [comment]
No problem, @Veylkh! Great question, there used to be a recipient for this link. The "Mastering Markdown" links are guides that have been deprecated. "Basic writing and formatting syntax" is the most current/updated guide we have for markdown syntax. When we deprecated the "Mastering Markdown" guide, we set up some redirects to "Basic writing and formatting syntax". Understandably, those redirects are causing a bit of confusion. 

As such, the "Mastering Markdown" guide links should be deleted from the documentation.
