### ISSUE TITLE
Warn about scam emails impersonating Github on 

### ISSUE THREAD

**Issue by vedantsinghania05** [github/docs#20546]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/types-of-emails-github-sends

### What part(s) of the article would you like to see updated?

I'm not sure how much of an issue this is, but I think it would be good if a section could be added that talks about identifying a real Github email from a scam email so that users of Github are more aware of not clicking about spam emails that seem like they are from GitHub. On the other hand, if scam Github emails are not much of a problem

**Comment by Porsha054** [comment]
Yes someone hack my email what is this app aways

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Vedant Singhania ***@***.***>
Sent: Sunday, September 11, 2022 6:28:06 PM
To: github/docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [github/docs] Warn about scam emails impersonating Github on (Issue #20546)


Code of Conduct

  *    I have read and agree to the GitHub Docs project's Code of Conduct<https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md>

What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/types-of-emails-github-sends

What part(s) of the article would you like to see updated?

I'm not sure how much of an issue this is, but I think it would be good if a section could be added that talks about identifying a real Github email from a scam email so that users of Github are more aware of not clicking about spam emails that seem like they are from GitHub. On the other hand, if scam Github emails are not much of a problem

Additional information

No response

**Comment by janiceilene** [comment]
@vedantsinghania05 Thanks so much for opening an issue! I've spoken with the team and this isn't something we're going to add to the docs 💛 

Thank you for your interest and passion in improving the GitHub Docs ✨
