### ISSUE TITLE
GITHub Api missing repository language if repo is forked (@get /user/repos)

### ISSUE THREAD

**Issue by AlexShanTE** [github/docs#20679]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/repos#list-repositories-for-a-user

### What changes are you suggesting?

**What feature or product is affected?**

 REST API

**What is the problem?**

At the moment, the request to the API (@GET
/user/repos ) returns a list of repositories. But if the repository is forked, then the result of the language from the api for it is always null 

![image](https://user-images.githubusercontent.com/98952360/190875379-4fc3b9ca-3c33-43b2-8047-b80546c5d7b8.png)

What is the new or expected behavior?

Returning the correct language or list of languages

**Comment by cmwilson21** [comment]
@AlexShanTE Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @AlexShanTE! This question would be best answered by our wonderful [support team](https://support.github.com/contact) 💛 If it turns out there's anything to update in the docs, please come back and let us know!

Thank you for your interest and passion in improving the GitHub Docs 💖
