### ISSUE TITLE
Per these docs we should be able to add callouts to markdown files.

### ISSUE THREAD

**Issue by Msalgado1988** [github/docs#20762]
Per these docs we should be able to add callouts to markdown files.

https://github.com/github/docs/blob/main/contributing/content-style-guide.md#callouts

```md
{* note *}

**Note:** This is a note

{* endnote *}
```

But in my usage it shows this text as is; no callout or formatting. See gist:

https://gist.github.com/samuelneff/eac051f64b15b635811b5ee1149eeb51

Am I doing something wrong? Are the docs wrong? Does this only work in certain contexts?

_Originally posted by @samuelneff in https://github.com/github/docs/discussions/20727_

**Comment by cmwilson21** [comment]
@Msalgado1988 Thanks for opening an issue and discussion! 

The syntax for callouts includes a `%` where the `*` appears in your example. However, please note that the style guide referenced in your issue is specifically for contributing to the Docs repo. These callouts are customized for use in the Docs and won’t work in gists or Markdown files outside of the repo.

Hope that clarifies some things. I'll go ahead and close out this issue. Thank you again! 💛
