### ISSUE TITLE
GitHub Pages (+ raw) bandwidth limits

### ISSUE THREAD

**Issue by peter-kehl** [github/docs#21321]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits = https://github.com/github/docs/blob/main/content/pages/getting-started-with-github-pages/about-github-pages.md

### What part(s) of the article would you like to see updated?

"Usage limits"

1. "soft bandwidth limit of 100 GB per month" > Please, add either
 - 'excluding use of other GitHub features such as releases' (as per the existing "making use of other GitHub features such as releases" below on the same page). Or (even better, if it is so - as I hope):
 - 'excluding use of other GitHub features (such as all from URLs under `https://github.com/user-or-organization/repo`), like'
   - 'downloads of individual files - not through GitHub Pages - but from GitHub web interface (URLs under https://github.com/user-or-organization/repo`, and/or from under `https://raw.githubusercontent.com`)',
   - 'downloads through `Releases` feature',
   - '"Download ZIP" feature of the main branch, other branches, tags or commits',
   - 'downloads of any images/media attached to GitHub issues and pull requests (and their comments), Projects, Discussions'.
2. Is this soft bandwidth limit **per repository**, or **total per owner** (user/GitHub organization)?
3. At least some more indication/explanation of criteria, bands/scale of limits, and consequences (of GitHub Pages traffic over), for
 - a legitimate open source/free repository, if the project maintainers don't have any other options (no backing company/foundation, no CDN, no funds for hosting their resources elsewhere).
   
   For example, a repo may provides files used by other legitimate open source/free GitHub Pages-enabled repos (or open source/free content outside of GitHub). Those "consumer" projects share (link to) the files direct (rather than forking). Why? So that they are always up-to-date.
   
   Such a project may start sincerely expecting not to overcome the soft limit of 100GB per month. Only later they become popular/widely used. They minimize their CSS & JS, and compress images. But even then, their users make them go over the soft limit, if many projects refer to them. Disabling/limiting the access would break those (other) innocent projects.
   
   (Yes, we can use `https://raw.githubusercontent.com`, but not for GitHub Pages-generated/processed content.)
 - a free content, but a **non-software** (for example, manuals/docs, community/support group), repository uses GitHub Pages (again, with the reasons and scenario as above).
4. Is there any bandwidth limit for access through `https://raw.githubusercontent.com/`? (And if so, is it totaled together/included in the GitHub Pages limit, or separate?)
5. In (any) GitHub  project's Settings > Pages (`https://github.com/owner/repo/settings/pages` there is no indication of the bandwidth used. (Using third party, like Google Analytics, actually increases the traffic, slows down pages, and is inaccurate.)
   I did look at related GitHub APIs:
    - https://docs.github.com/en/rest/pages
    - https://docs.github.com/en/rest/repos/repos
    - https://docs.github.com/en/rest/rate-limit
   But none of the above APIs mention bandwidth usage. The most relevant was:
    - https://docs.github.com/en/rest/metrics/traffic#get-page-views > "page views"... "number of views"
   But that doesn't show the bandwidth - only `count`, `views` and `uniques`.
   
   Are there any plans of bandwidth API, a dashboard, or at least an indicator? If so, what's the tracking issue?
### Additional information

If you provide answers, I'm willing to create a pull request.

Thank you for GitHub and GitHub Pages.
You rock.

**Comment by cmwilson21** [comment]
@peter-kehl Thanks for opening an issue! You rock, too! 😄 

Thanks for asking such clear questions and offering to make the PR. I'll get this triaged for review! 👀

**Comment by felicitymay** [comment]
@peter-kehl - I agree with Courtney, your questions look very clear and we'll follow up with a subject matter expert to find answsers.

**Comment by felicitymay** [comment]
Hi @peter-kehl. I had a chat with a subject matter expert about your questions. I'm adding a summary of their answers below. 

The "Usage limits" information that you ask about is part of the section [Limits on use of GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#limits-on-use-of-github-pages).  Consequently it describes the limits that apply to the GitHub Pages feature. These limits are separate from limits on other features. 

> "GitHub Pages sites have a _soft_ bandwidth limit of 100GB per month."
- This talks about "GitHub Pages sites" rather than "repositories that run GitHub Pages".  This is intended to indicate that the limit applies only the the pages site and not the underlying repository.

You give an example of an open source/free repository, that exceeds their bandwidth and the difficult situation that might arise. If this situation arose, GitHub would contact the maintainers and work with them to find a solution. Our bandwidth limits are intended to ensure that the system is not abused, degrading the experience for other users. 

The bandwidth limits are soft, which allows a site to continue operating while the open source maintainers work with GitHub to resolve cases like the one that you describe.

Your final question seems like a feature request. The best place to raise this is in the [Pages section of our community discussions](https://github.com/community/community/discussions/categories/pages).

**Comment by peter-kehl** [comment]
Thank you @felicitymay.

After the above I had only one outstanding question: Whether GitHub pages of multiple projects belonging to the same GitHub user/organization shared the 100GB  (soft) bandwidth limit.

https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites says that "there are three types of GitHub Pages sites: project, user, and organization." Based on that it sounds like GitHub pages of multiple sites (based on different repositories) all belonging to the same GitHub user/organization  have separate (soft) bandwidth limits.

**Comment by felicitymay** [comment]
Hi @peter-kehl - apologies for the slow response, I've been out of action ill.

Regarding your final point. I checked our terms and conditions, and they suggest that people contact support if they have questions over whether their intended use would be within the allowed usage: https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#pages. I think that this is going to be your best course of action.
