### ISSUE TITLE
Add section with special characters that need to be escaped when used in GitHub secret value

### ISSUE THREAD

**Issue by GuillaumeFalourd** [github/docs#21626]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/encrypted-secrets

### What part(s) of the article would you like to see updated?

It could be interesting to add a section to the **Encrypted Secrets** page (like the "Naming your secrets" section) informing what rules have to be followed, such as which special characters need to be escaped when used in a GitHub secret value (_e.g: use `\$` instead of `$`_). 

### Additional information

[Question about this behavior on StackOverflow](https://stackoverflow.com/questions/74204204/how-can-we-identify-the-special-characters-that-cannot-be-directly-given-as-gith) _(There are others)_.

**Comment by lucascosti** [comment]
Hi, @GuillaumeFalourd thanks for opening this issue. GitHub Actions secrets should store as whatever you provide as-is, with no escaping necessary.

However, when you **use** secret values, you will need to handle any special characters that might be in the secret, as with any other string.

For example, if you had the value `$thisisasecret and may have $special%characters that could be interpreted as shell stuff ` as a secret, and then attempted to use the secret like: 

```
echo ${{ secrets.MY_SECRET}} > tempfile.txt
```

it would not include the whole secret string, because it would be the like trying to run:

```
echo $thisisasecret and may have $special%characters that could be interpreted as shell stuff > tempfile.txt
```

which most shells would try to do interpolations and substitutions for environment variables and alike. The file would contain something like `and may have %characters that could be interpreted as shell stuff`.

If you wanted the value literally as-is, you would need to quote the secret value, for example:

```
echo '${{ secrets.MY_SECRET}}' > tempfile.txt
```

Which is the same as handling any other string, environment variable, or context in GitHub Actions 🙂
