### ISSUE TITLE
Instructions for installing the github-pages gem are confusing

### ISSUE THREAD

**Issue by monfresh** [github/docs#2177]
### What article on docs.github.com is affected?

[Creating a GitHub Pages site with Jekyll](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll#creating-your-site)

### What part(s) of the article would you like to see updated?

Steps 8 - 10 are confusing. If you search for `could not find gem github-pages` in your favorite search engine, you'll find that the instructions caused people to do one or more of the following things:

- they didn't uncomment the `# gem "github-pages"` line
- they tried to run `bundle update github-pages`
- they replaced `VERSION` with the version of `jekyll` listed on the [Dependency versions](https://pages.github.com/versions/) page instead of the `github-pages` version.

Step 7 is also both confusing and incorrect. Running `jekyll 3.9.0 new .` does not work. The `jekyll new` command does not accept a version number, at least not like it is documented in GitHub docs. Also, the Bundler section is more confusing than helpful because for `bundle exec` to work, a Gemfile must exist in the directory, but the instructions don’t mention that. Instead of adding more steps, I think it's best to simplify step 7 to just `jekyll new .`, which will create the Jekyll site using whatever version of Jekyll is currently installed (most likely 4.2.0). 

In step 8, they are told to comment out the jekyll gem, so it doesn't matter if they used a more recent version of jekyll to create the site initially. What matters is that after they save the Gemfile, they need to run `bundle update` because github-pages only supports jekyll 3.9.0 currently. Running `bundle install` will result in dependency issues.

See the linked PR below that I submitted to fix this.

### Additional information

Examples of people who got stuck because of the documentation: 

- https://talk.jekyllrb.com/t/why-cant-i-install-the-github-pages-plug-in-when-i-set-up-jekyll/3743
- https://talk.jekyllrb.com/t/how-to-install-github-pages-with-jekyll/3510

**Comment by BenWhetton** [comment]
I also encountered this issue just last week. It would have been nice if #2178 had been merged already! It's likely costing users a lot of time to have these kinds of errors in such a key guide.
I have a sligtly different solution to propose than #2178 which uses the github-pages gem to ensure the correct version of jekyll is used to set up the jekyll scaffolding. This works even without a system-wide jekyll installation and will ensure that there are not compatibility issues if jekyll 4+ changes the behavior of `jekyll new` in some way

### The problem as I would describe it:
When following the [GitHub Pages Jekyll guide], the command in step 7: `bundle exec jekyll VERSION new .` does not work for multiple reasons:
- Bundler has not been initialised
- Jekyll has not been installed by bunder
- The default bundler install path may require root permissions to install gems.
- The command is incorrect. After resolving the other problems, `bundle exec jekyll _VERSION_ new .` works. However `_VERSION_` is undocumented so it would be best to avoid it if possible.

### Proposed solution

I worked through setting up a new Jekyll GitHub Pages site last week. By cross referencing various stackoverflow answers (which I forgot to keep links to) and the [Jekyll bundler guide], I came up with the following procedure which I believe solves all of the above problems. This should replace the bundler version of step 7 of the [GitHub Pages Jekyll guide]:
- Initialise bundler: `bundle init`
- Configure bundler install path (optional but necessary for to avoid permissions issues in many situations): `bundle config set --local path 'vendor/bundle` (as shown in the [Jekyll bundler guide])
- Add the github-pages gem `bundle add --group=":jekyll-plugins" github-pages`.
  This will install the correct version of Jekyll currently supported by github-pages without the user having to manually check what the correct version is and install that specific version. This step is not in the [Jekyll bundler guide] because it does not cover Github Pages-specific steps. Otherwise, I would simply recommend linking to that guide rather than duplicating it. The resulting Gemfile will look like this:
  ```
  # frozen_string_literal: true
  
  source "https://rubygems.org"
  
  git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
  
  # gem "rails"
  
  gem "github-pages", "~> 209", :group => :":jekyll-plugins"
  ```
- Create a Jekyll scaffold
  ```shell
  bundle exec jekyll new --force --skip-bundle .
  bundle install
  ```
  (as shown in the [Jekyll bundler guide])

Now the user can continue with the rest of the [GitHub Pages Jekyll guide] from step 8 (with some of the fixes proposed in #2178).
I would recommend adding a link to the [Jekyll bundler guide] somewhere in the [GitHub Pages Jekyll guide] as well.

I also have a question about step 9. It would be useful to add a comment to explain what this step is for. Is the goal to prevent `bundle update` from performing an undesired major update of the `github-pages` gem?

It is a little confusing having the bundler and non-bundler instructions in the same guide. Perhaps it could be restructured in a way that makes it more clear.

The solution in #2178 is certainly an improvement. I think it would be good to add a link to the [Jekyll bundler guide] and to add the optional "Configure bundler install path" step. I personally like the pure bundler approach from the solution proposed above since it avoids having to install jekyll outside of bundler and it ensures that the procedure is not affected by any non-backwards compatible changes to the behavior of `jekyll new`.

[GitHub Pages Jekyll guide]: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll
[Jekyll bundler guide]: https://jekyllrb.com/tutorials/using-jekyll-with-bundler/

**Comment by janiceilene** [comment]
Thanks for the thorough explanation @BenWhetton! I've triaged it to let the team take a look 👀

**Comment by ReimarBauer** [comment]
I'd ran in that common "versions" problem too. The hint with the undocumented version string `_3.9.0_` helped also a bit, not sure about if it is forgotten or deprecated. I agree to @BenWhetton suggestions. 
The documentation should show the bundle approach.  `bundle exec jekyll serve` was for me the only option without versioning conflicts of 18n to try our pages locally.

**Comment by hubwriter** [comment]
For ease of looking at what needs changed, here's the relevant section of the page before the changes in #2178 were merged:

<img src="https://user-images.githubusercontent.com/54933897/108506086-2d9ce680-72b0-11eb-946d-3e0e16da5423.png" width=500 />

As of writing, these steps now look like this:

<img src="https://user-images.githubusercontent.com/54933897/108506325-7e144400-72b0-11eb-9d59-2fca075b58d3.png" width=500 />

**Comment by hubwriter** [comment]
Generally in the documentation we choose one way of doing things and document that - rather than overcomplicate things by documenting alternative ways of doing the same thing. Given that the prerequisites section of this help article tells the reader to install Bundler, I think @BenWhetton's suggestion for documenting the Bundler method is a good one. We should replace the current steps 7-10 with steps for using Bundler. We should document the steps directly in this help article rather than requiring the reader to go to https://jekyllrb.com/tutorials/using-jekyll-with-bundler/ and then come back here.

Thanks @BenWhetton for providing this information.

**Comment by thomaswolff** [comment]
@BenWhetton Just wanted to drop by and say thanks for your detailed explanation. I followed the guide on [https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll) as per writing this comment, and I ended up with a blank site on GitHub Pages. Starting from scratch, following your proposed step 7 solved the issue.

**Comment by taiya** [comment]
@thomaswolff thanks for summarizing, this helped getting further, but then later, when "testing" the website as for [this official guide](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll) I run into yet [another documented bug](https://github.com/jekyll/jekyll/issues/5423) when executing `bundle exec jekyll serve` (see code block below)

Overall, really seems github docs needs some major polish to ensure the documentation is flawless (which is quite surprising as in the past I found github docs top-notch).

**And if a local jekyll environment is so brittle to setup, why not just have a docker container?**

```
bundle exec jekyll serve
Configuration file: /Users/atagliasacchi/website/_config.yml
            Source: /Users/atagliasacchi/website
       Destination: /Users/atagliasacchi/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.709 seconds.
 Auto-regeneration: enabled for '/Users/atagliasacchi/website'
bundler: failed to load command: jekyll (/Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/bin/jekyll)
/Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:184:in `require_relative'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:184:in `setup'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:102:in `process'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `load'
        from /Users/atagliasacchi/website/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `load'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:28:in `run'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/cli.rb:475:in `exec'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/exe/bundle:49:in `block in <top (required)>'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.24/exe/bundle:37:in `<top (required)>'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/bin/bundle:23:in `load'
        from /Users/atagliasacchi/.local/share/gem/ruby/3.0.0/bin/bundle:23:in `<main>'
```

**Comment by taiya** [comment]
Meanwhile, following [this blog post](https://medium.com/@sebagomez/setting-up-a-github-page-with-jekyll-and-a-docker-container-c712e448649b) with a few tweaks (version 3.5 was needed, otherwise I had [an error](https://gist.github.com/taiya/fdd39a815b2f0a8aab01863a1fe454fa)):

```
git clone https://github.com/jarrekk/Jalpc.git $HOME/jalpc
docker run -v "$HOME/jalpc:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll:3.5 jekyll serve
```

And once everything is ready, just open `http://localhost:4000`.

**Comment by hubwriter** [comment]
We've updated the instructions for creating a site, changing steps 7 and 12.
The steps now look like this:
![image](https://user-images.githubusercontent.com/54933897/129175764-188cb459-fc11-4153-a6b5-0acba2dca7f8.png)

We've tested these instructions and I believe this resolves the issue.
Accordingly, I'm going to close this issue.

Many thanks to everyone who commented above. ✨

**Comment by zengzzzzz** [comment]
> ### docs.github.com 上的哪些文章受到影响？
> [使用 Jekyll 创建 GitHub Pages 站点](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll#creating-your-site)
> 
> ### 您希望更新文章的哪一部分？
> 步骤 8 - 10 令人困惑。如果您在自己喜欢的搜索引擎中进行搜索`could not find gem github-pages`，您会发现这些说明会导致人们执行以下一项或多项操作：
> 
> * 他们没有取消注释该`# gem "github-pages"`行
> * 他们试图逃跑`bundle update github-pages`
> * 他们替换为[依赖版本](https://pages.github.com/versions/)页面上列出的`VERSION`版本而不是版本。`jekyll`[](https://pages.github.com/versions/)`github-pages`
> 
> 第 7 步也是令人困惑和不正确的。运行`jekyll 3.9.0 new .`不起作用。该`jekyll new`命令不接受版本号，至少不像 GitHub 文档中记录的那样。此外，Bundler 部分更令人困惑而不是有用，因为要`bundle exec`工作，Gemfile 必须存在于目录中，但说明中没有提到这一点。我认为最好将第 7 步简化为 ，而不是添加更多步骤`jekyll new .`，这将使用当前安装的任何版本的 Jekyll（很可能是 4.2.0）创建 Jekyll 站点。
> 
> 在第 8 步中，他们被告知要注释掉 jekyll gem，因此他们最初是否使用更新版本的 jekyll 来创建站点并不重要。重要的是在他们保存 Gemfile 之后，他们需要运行，`bundle update`因为 github-pages 目前只支持 jekyll 3.9.0。运行`bundle install`会导致依赖问题。
> 
> 请参阅下面我提交的用于解决此问题的链接 PR。
> 
> ### 附加信息
> 由于文档而陷入困境的人的例子：
> 
> * https://talk.jekyllrb.com/t/why-cant-i-install-the-github-pages-plug-in-when-i-set-up-jekyll/3743
> * https://talk.jekyllrb.com/t/how-to-install-github-pages-with-jekyll/3510

thanks

**Comment by yhyu13** [comment]
@hubwriter Back from 2023, for git-pages version `288`, we are having dependency problems with `bundle install` again, and here is my solution to all these dependency error:

```
sudo gem install colorator -v 1.1.0
sudo gem install forwardable-extended -v 2.6.0
sudo apt-get install ruby-dev
sudo gem install racc -v 1.6.2
sudo gem install commonmarker -v 0.23.8
sudo gem install http_parser.rb -v 0.8.0
sudo gem install jekyll-watch -v 2.2.1
sudo gem install jekyll-sass-converter -v 1.5.2
```
There might be more in your case~

Basically, you need to install missing package with `gem`, and if required, install `ruby-dev` as well

If you have permission error on write to `/var/lib/gems/` and `/usr/local/bin`, try
```
sudo chown -R $(whoami) /var/lib/gems/
sudo chown -R $(whoami) /usr/local/bin
```

Good lunk!
