### ISSUE TITLE
Error rendering a table

### ISSUE THREAD

**Issue by rajbos** [github/docs#22102]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

A markdown table is not rendering correctly at [about-billing-for-github-actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

Result:
![image](https://user-images.githubusercontent.com/6085745/202550360-f6beac51-8d28-47a8-9c65-5ce889436623.png)

### What part(s) of the article would you like to see updated?

Fix the rendering 😄 

### Additional information

I have tried to find the file, but the both the [table definition] (https://github.com/github/docs/blob/main/data/reusables/billing/billing-hosted-runners.md) as well as the [if statement](https://github.com/github/docs/blob/8017c76bba46bf37e530601a92097069b381b4cb/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md?plain=1#L70) look OK.

I guess it must be somewhere in the code that handles the IF statement to inject an extra empty line?

**Comment by cmwilson21** [comment]
@rajbos After some digging and help from the team, I applied this [whitespace fix](https://github.com/github/docs/tree/main/content#whitespace-control). Since I was already testing it, I went ahead and made [the PR](https://github.com/github/docs/pull/22137). 

Would you mind taking a look at [the preview](https://docs-22137-91b62c.preview.ghdocs.com/en/enterprise-cloud@latest/billing/managing-billing-for-github-actions/about-billing-for-github-actions) and giving a 👍?

**Comment by rajbos** [comment]
Awesome. Looks great 🐿️
