### ISSUE TITLE
"Migrating from GitLab CI/CD to GitHub Actions" article uses Gitlab CI_COMMIT_REF_SLUG without equivalent Github variable

### ISSUE THREAD

**Issue by jeverling** [github/docs#22249]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions#caching

### What part(s) of the article would you like to see updated?

The article uses the following example for how to translate caching of workflow files:

```yaml
image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/
```

There is no equivalent variable being shown for Github, instead the cache key is set to `key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}`.

I think it would be better to use an example, where there is actually an equivalent variable in Github.

**Comment by cmwilson21** [comment]
@jeverling Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
👋 @jeverling I'm not super familiar with GitLab CI/CD caching, but I think the GitLab example is shown that way because it's [the recommended way of specifying the scope of a GitLab cache](https://docs.gitlab.com/ee/ci/caching/#share-caches-between-jobs-in-the-same-branch) (i.e. to limit the cache access to the branch).

It doesn't have an equivalent GitHub variable because GitHub Actions caches are by default scoped to the branches they were created on ([more info here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache)).

So from a migration POV, the GitLab example shown is similar to the GitHub one in terms of the behavior for both systems.
