### ISSUE TITLE
Documentation of GitHub packages is partly outdated

### ISSUE THREAD

**Issue by Morinator** [github/docs#22455]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-user-owned-package-on-github

### What part(s) of the article would you like to see updated?

When going on the packages-tab of my organization, there is no button to connect to a repository.

My view:
![image](https://user-images.githubusercontent.com/25711926/205511923-92399015-dd8e-49dd-9a70-1e29047e5f29.png)

Shown in docs:
![image](https://user-images.githubusercontent.com/25711926/205511958-231261b9-1668-4a17-bae9-60ed4b49e3e4.png)

**Comment by cmwilson21** [comment]
@Morinator Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by isaacmbrown** [comment]
Hi @Morinator, thanks for raising this issue. You're seeing that page because you do not currently have any packages owned by your organization. If you did, you would see a list of packages on this page. You could then click the package and, on the package's page, click **Connect Repository**.

I'll close this issue as no docs updates are required on this particular point. 🙂
