### ISSUE TITLE
Document limitation with reusable workflows

### ISSUE THREAD

**Issue by unchris** [github/docs#22746]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

### What part(s) of the article would you like to see updated?

The [Limitations](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations) section.

If you create a reusable workflow in repository A and that workflow uses a composite action defined also in repository A, you cannot use the reusable workflow from repository B.

This [community discussion](https://github.com/orgs/community/discussions/18601) does a good job illustrating the issue, but basically the upstream workflow assumes that the composite action will be in the context of repository B's files when it should be looking in repository A's files.

The error you receive in repository B's actions output is similar to the below, which I copied from the linked discussion thread:

> Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/CLIENT/REPO/generate-docker-tags@master'. Did you forget to run actions/checkout before running your local action?

**Comment by Simran-B** [comment]
Just wondering: it sounds like it would be trivial to fix the runner software to look in the right repo, but the security aspect might not be as simple? (checking for allowed actions)

**Comment by cmwilson21** [comment]
@Simran-B Thank you for opening an issue and linking it to your PR! ✨

**Comment by unchris** [comment]
> Just wondering: it sounds like it would be trivial to fix the runner software to look in the right repo, but the security aspect might not be as simple? (checking for allowed actions)

Indeed, I'd be happy to withdraw this issue and PR if GitHub can instead remove the limitation. It would be great to have Reusable Composite Actions

**Comment by dixieland55** [comment]
Let me tell you this. Something you might want to know and I might just have an idea what to do about conduct and security and guidelines. I might have a solution to all these problems. So this is my day consist of when I wake up. Well this morning I woke up got my phone looking through my emails well I noticed something odd I was thinking well here I go again 5 to 6 hours explaining myself again because that's what I have been doing since March 2022. Because believe me I am incident. So I probably got your attention now. So this is my story so anyway I noticed GOOGLE it listening to my conversation to my new phone and I am thinking this is still not over yet. Well I also noticed that they are using my old email address to. So I am thinking wait minute if they are listening to my conversations on my new phone that means they got into my new phone so at this point you are wondering why dose this person have two phones for. Well the answer is have to you ever been through through 11 months of hell? Welcome to my world I am going to blow everything out in the water now. Here it goes . My old phone got hacked ok I have been quite about it. Because for one I am trying to prove my incidents to everyone but I am tired I have been fighting tooth and nail with the legal stuff and everything else but anyway I am stressed out because I am tired explaining myself again and again and I am not sure what to do with all of this going on well anyway I gotten threatened three times and the first time was when I refused to sign a agreement and they told me if I didn't sign  it they would do illegal things and have it lead back to me that's exactly what is happening and been going on for 11 months now. The second time was when I downloaded edge so I could learn about documents and things well this hackers are you ready for this!!! Well they said if don't install that app I would have to pay them 300 hundred dollars well I installed it. So I did what they told me to do then I found out they sold my information twice online and things are just getting worse everyday sometimes I cry about it because here I am minding my own business and I don't talk to a whole lot of people because I am considered a home body I don't like getting around a whole of people because I have anxiety so anyway I am just can't figure out why they target me for I don't have any money I can't work so why did these people target me for. The answer is I have to much evidence on them so they are making my life hell. I am willing to do anything I can to prove my incidents I got to phone bills and paying for extra security but still they get through the security any time they want and listen to your conversations and send them back to you. You think security can help you and they change your passwords everyday sometimes every 5 minutes to just mess with you well that's enough to stress a person out and not to mention if you think you are a victim and the legal system thinks you are a criminal and you are just a bad person and they are letting the bad people get away let them keep on punishing me for what they are doing to me. I am sorry to say this SECURITY MY ASS.!!! And Guidelines please I do the guidelines and when I do the documents disappear just like that. All the work I have done gose out the window 🪟 because of the HACKERS and let me tell you this isn't OVER YET believe me my mom didn't raise me to sit back and these people run over me. I am going to take this all the way to the supreme Court if I have to and I will prove my incidents and I am doing it the legal way and believe me when I am done I am going to start a business for the internet and it will be for the people like me and you and nobody will be able to get through I promise you that that's why I am so excited to learn more about the internet and I am doing this because I am tired of people pushing me around and I have never stolen anything in my life to let people still it out of your bank account and buying things in your name well it has to stop and these people are bad people and that's all I can say for now but be careful and to let you know I probably have to install this app because they did something and I can't explain it but good luck and stay safe and until next time.
