### ISSUE TITLE
Add a `Build and test Rust` workflow sample to docs

### ISSUE THREAD

**Issue by dili91** [github/docs#23181]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration

### What changes are you suggesting?

👋 While reading the docs yesterday I noticed that docs do not mention a sample for building and testing an application written in Rust just yet.

### Additional information

I can help with that if of interest

**Comment by cmwilson21** [comment]
@dili91 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue and offering to write a Rust guide! This sounds like a great contribution. ✨  I want to highlight some points to help your contribution be a success and a positive experience for you:

- We have had some friction with similar contributions in the past that had copy-paste errors (e.g. a non-Python guide that included content copied from the Python guide) or that didn't follow best practices. Please double check all content and use a standard Rust linter before submitting your PR. If the team does not feel that is meets our standards, we may close the PR.
- Our team does not have much Rust knowledge, so it will be helpful if you can provide demos your example workflow along with your PR. (e.g. share a workflow run log)
- Our team is very busy working on new releases right now. Since your PR will likely be large, bear in mind that it will take longer for us to find time to review it.
