### ISSUE TITLE
Describe the filters used in Insights

### ISSUE THREAD

**Issue by VargaElod23** [github/docs#23658]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-summary-of-repository-activity

### What part(s) of the article would you like to see updated?

I recently started to implement an endpoint to count the unique commits of a repo. However, using all possible filtering on OIDs and duplicates with slightly differing names I wasn't able to get certain repositories to a commit count as low as on the Insights page for all branches.
I would request:
- A description of the filters used to end up with that number.
- A possible external link that leads to https://docs.github.com/en/graphql/overview/explorer a triage query (if Gql is used).

### Additional information

Example repo: https://github.com/Taraxa-project/taraxa-platform/pulse/monthly.

-  Number of commits I got: 594 

-  Number on pulse: 270 <- this number feels very, very low to the activity of the repo.

---
[maintainers edit]
Content plan found [here](https://github.com/github/docs/issues/23658#issuecomment-1435270053)

**Comment by cmwilson21** [comment]
@VargaElod23 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by saritai** [comment]
@VargaElod23 👋 Hello! Thanks for your patience on this! ✨  I asked an SME about this and it seems that the discrepancy is because the commit count in Pulse does not include merges. Does that make sense based on the commits you are seeing in your count (the `message` will probably say that it is a merge)?  

It does say that it excludes merges on the [Pulse page](https://github.com/Taraxa-project/taraxa-platform/pulse/monthly), but it doesn't mention this in "[Viewing a summary of repository activity](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-summary-of-repository-activity)" about it. I'd say we could add a brief sentence that makes it clear that it shows commit count excluding merges! 

If you (or anyone else) is interested, feel free to open a PR to add this clarification! 🙇‍♀️

**Comment by aidrous** [comment]
#24155

**Comment by Agro00000** [comment]
вс, 26 Фев 2023, 4:06 ATHMANE ***@***.***>:

**Comment by VargaElod23** [comment]
@saritai What are you guys including exactly under "merges"? 

1. Merge commits? I excluded those already and still got a much bigger count.
2. All commits in branches that have been merged into develop? In that case, the second part of the explanation is kinda iffy: `and 164 commits to all branches`.

Thing is, any hard I try, I can't get (at least with the upper filter set) to numbers as low as the Pulse page shows, so that's why I'm curious. ❓

**Comment by saritai** [comment]
@VargaElod23 👋 Hello! I think this question would best be handled by our wonderful [support team](https://support.github.com/request). Please reach out to them about the difference in numbers that you are seeing. 

If there’s anything in the documentation that you have suggestions for updating, please feel free to open an issue. Thanks! :yellow_heart:

**Comment by VargaElod23** [comment]
Well, a detailed description of the filters in the Insights page would come a long way, maybe as a section in the docs and just linked to the Insights page. What do you think @saritai ?

**Comment by saritai** [comment]
Hello @VargaElod23, and thanks for the suggestion! After chatting with the team, we’ve decided to remove it from the help wanted board to discuss it a bit more internally! Thank you for raising this issue 💖
