### ISSUE TITLE
Creating a Github pages repo as private will not work even after changing visibility

### ISSUE THREAD

**Issue by chrislgarry** [github/docs#2418]
I made a website following the Github pages [documentation](https://pages.github.com/), but accidentally made the repository private upon creation. Changing it to public afterwards, my webpage was still not visible. Documentation I've found states the repository must be public if you you're not a Pro user, however it doesn't mention it must be public upon creation time. My fix was to delete the repository and recreate it with public visibility upon creation. Something in the documentation stating this edge case would be helpful. I suspect changing visibility after the fact does not initiate DNS, hosting, etc.

**Comment by chrislgarry** [comment]
If there is a particular place to fix and make a PR, I'm happy to do so. Thanks!

**Comment by janiceilene** [comment]
@chrislgarry Thanks so much for opening an issue! I'll triage this for the team to take a look at and figure out the best course of action 👀

**Comment by chrislgarry** [comment]
@janiceilene thank you! Apologies for the lack of actionable data (logs, specific code responsible, etc.). Didnt have much time to chase it down. Hopefully it's pretty straightforward 🙆‍♂️

**Comment by jih559** [comment]
#2418

**Comment by felicitymay** [comment]
Hi @chrislgarry - many thanks for flagging this unexpected behavior. I'll check with the pages team on this and then we can work out the best way to document this limitation.

**Comment by felicitymay** [comment]
The pages team have got back to me with the following explanation:

> This is expected and the user could have enabled pages once the repository was made public by selecting a source branch for Pages in their repository settings. We enable Pages automatically only on push. Not on any other events (such as repository switches from private to public for instance).

It sounds as if https://pages.github.com/ could do with a link out to a troubleshooting guide at the end to give tips like this. The content on that page is maintained in a different repository, so I'll forward your feedback on to the relevant team.

I was looking at the https://docs.github.com site (which is published to from the `docs` repository) to see if this was explained here. Possibly it would be worth updating step 4 of [Creating a repository for your site ](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site#creating-a-repository-for-your-site) and [Creating a repository for your site ](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll#creating-a-repository-for-your-site) (Jekyll) to recommend that this is a public site, since GitHub Pages are displayed publicly. As well as avoiding GitHub Free users encountering your problem, it might also help other users reduce the chance of accidentally publishing private information to a public pages site.

**Comment by felicitymay** [comment]
I've raised #3262 to make the information about this on docs.github.com clearer.

**Comment by felicitymay** [comment]
I'll raise an internal issue with the relevant team to ask them to amend https://pages.github.com/ so that this is clearer too.

**Comment by Jana-kasuar** [comment]
`gh --version`

**Comment by felicitymay** [comment]
:grin: https://pages.github.com/ now updated to suggest creating a public repository.

**Comment by chrislgarry** [comment]
@felicitymay  @janiceilene thank you very much!

**Comment by magnussentio** [comment]
So I'm facing the same issue, but slightly different: My repo was committed as public, github pages deployment was completely fine. I changed my repo to private (not realizing only public repos can be deployed), obviously the github page no longer worked. I then changed my repo back to public, and still my github pages does not redeploy. So it sounds like my only solution is to delete my repo and recommit it only as public? This seems really cumbersome.

**Comment by cmwilson21** [comment]
Hey @magnussentio 👋 This question would best be handled by our [support team](https://support.github.com/request). Please reach out to them. 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue. 💛

**Comment by sibyabin** [comment]
Hey @magnussentio  - I have got in to the same issue . But i was able to resolve it by re-enabling the GitHub Pages in the repository's settings. it seems that the github pages settings on the repo is removed while making the repo private ( which makes sense)
