### ISSUE TITLE
Possible vulnerability due to bad action example.

### ISSUE THREAD

**Issue by FeeeeK** [github/docs#24675]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Almost every article with actions, for example: 
https://docs.github.com/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

### What part(s) of the article would you like to see updated?

Removal of `${{ }}` in all conditions.

Because of bug in action runners (actions/runner#1173), it can lead to vulnerability.
There is no error in the examples themselves ([example run](https://github.com/FeeeeK/every-pr-here-will-be-merged/actions/runs/4525561200)), but if you combine this condition with another one, the action will run even if the author isn't dependabot ([example run](https://github.com/FeeeeK/every-pr-here-will-be-merged/actions/runs/4525565582)); ([example pull request with vulnerability](https://github.com/FeeeeK/every-pr-here-will-be-merged/pull/2))
![image](https://user-images.githubusercontent.com/26704473/227790784-6d341230-3952-496f-8ce1-10a86ac15540.png)
![image](https://user-images.githubusercontent.com/26704473/227790803-4b6004ea-492e-4417-a755-8a8de6530f73.png)

**Comment by Nishnha** [comment]
After taking a look through the [Dependabot documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions), I don't think any of our examples are affected.

This issue concern lines where `${{ }}` is used multiple times outside of a string.
In the Dependabot docs, we always use a single variable interpolation statement as a string.

For example: `if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}`

This seems like more of a bug than a vulnerability since it would only really affect workflows on an individual's repo, but I would double check with the Actions team.

**Comment by jc-clark** [comment]
👋 Hey there @FeeeeK. Thank you for this issue and your patience while we're working through the backlog of GitHub Actions issues. 

We recently made a few small, but critical changes to the docs about the `${{ }}` expression syntax that may help here: 

- In [`jobs.<job_id>.if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)

  > When you use expressions in an `if` conditional, you can, optionally, omit the `${{ }}` expression syntax because GitHub Actions automatically evaluates the `if` conditional as an expression. However, this exception does not apply everywhere.
  > 
  > You must always use the `${{ }}` expression syntax or escape with `''`, `""`, or `()` when the expression starts with `!`, since `!` is reserved notation in YAML format. For example:
  > 
  > `if: ${{ ! startsWith(github.ref, 'refs/tags/') }}`
  > 
  > For more information, see "[Expressions](https://docs.github.com/en/actions/learn-github-actions/expressions)."

- In "[About expressions](https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions)"

  > Expressions are commonly used with the conditional `if` keyword in a workflow file to determine whether a step should run. When an `if` conditional is true, the step will run.
  > 
  > You need to use specific syntax to tell GitHub to evaluate an expression rather than treat it as a string.
  > 
  > `${{ <expression> }}`
  > 
  > Note: The exception to this rule is when you are using expressions in an `if` clause, where, optionally, you can usually omit `${{` and `}}`. For more information about `if` conditionals, see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)."
  
However, I do notice that several of the examples in "[Automating Dependabot with GitHub Actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions)" do contain the `${{ }}` expression syntax within an `if` conditional—[here](https://github.com/github/docs-internal/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L145), [here](https://github.com/github/docs-internal/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L182), [here](https://github.com/github/docs-internal/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L190), [here](https://github.com/github/docs-internal/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L214), [here](https://github.com/github/docs-internal/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L255), and [here](https://github.com/github/docs-internal/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L263). 

Since the expression syntax isn't required within an `if` conditional, it may be that all we need to do for this page of the documentation is remove the expression syntax from the examples I listed above. 

What do you think about this?

**Comment by FeeeeK** [comment]
Hello, @jc-clark, yes, right now I think removing it from the example would be enough.
By the way, the links you provided lead to https://github.com/github/docs-internal and I don't think it's a public repository

**Comment by jc-clark** [comment]
Oh excellent point, thank you! I just fixed the links to point to the public repository. Let me know if those links work for you. 

For now, I'll add the `help-wanted` label to this issue for anyone in the open source community to help make a PR to fix this. 

The PR should remove the `${{ }}` expression syntax within the `if` conditionals [here](https://github.com/github/docs/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L145), [here](https://github.com/github/docs/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L182), [here](https://github.com/github/docs/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L190), [here](https://github.com/github/docs/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L214), [here](https://github.com/github/docs/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L255), and [here](https://github.com/github/docs/blob/9b4bf39699b8181006b08be9521410805f541535/content/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.md?plain=1#L263).
