### ISSUE TITLE
docs: links `[text](#target)` in reuseables need a review

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#25088]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Just to record that the problem described in #25086 may occur in other reusables.

### What part(s) of the article would you like to see updated?

In reusables, using `[text](#target)` may cause invalid links in the rendered doc pages.

Suppose a reusable containing `[text](#target)` is included by pages `content/path/to/page-a.md` and `content/path/to/page-b.md`.  This requires both pages have a section titled `Target` or like.  If any of the pages don't define such an anchor, invalid links are created.  Therefore in most cases in reusables the links in form `[text](#target)` should be adapted to `[text][/path/to/page-x#target]`.

### Additional information

Running `grep -rn '](#' data/**/*.md | wc -l` gives `47` (on 1b9019427572), among which 2 will be resolved by #25087.

**Comment by cmwilson21** [comment]
@muzimuzhi Thanks for opening another issue to point out potential additional broken links. I'll get this triaged for review! :zap:

**Comment by myarb** [comment]
I've added the `engineering` label here so they can review with a possible script solution in mind 👍🏼

**Comment by peterbe** [comment]
The complication is that sometimes it's OK. A reusable that uses in-page anchor links might be working fine when used in more than one page. E.g. if 2 pages use the same re-usable that both contain `[See the "Next steps"](#next-steps)` it can work on multiple pages that have that sub-heading. So it can't be a hard rule that all reusable in-page anchor links need a pathname. 

There are multiple nuances about this and how can script and test this. I'll bring *this* problem up in the internal issue: https://github.com/github/docs-engineering/issues/2428 since it involves both input from writers, PMs and engineering.

**Comment by cmwilson21** [comment]
@muzimuzhi Thanks again for opening this issue and bringing it to our attention! ✨ 

I am, however, going to go ahead and close this issue as we are tracking this internally now. 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
