### ISSUE TITLE
Update to newer `azure/login` action using node16

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#25104]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

It's about the workflow files in `.github/workflows` directory.  Sorry I didn't find a better issue template to report this.

### What part(s) of the article would you like to see updated?

I noticed the workflow run https://github.com/github/docs/actions/runs/4737193099 throws a warning

> **[Build and deploy Azure preview environment](https://github.com/github/docs/actions/runs/4737193099/jobs/8409692590)**
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: `azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf`. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

- `azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf` corresponds to [v1.4.3](https://github.com/Azure/login/tree/v1.4.3).
- The least version using node16 is [v1.4.5](https://github.com/Azure/login/tree/v1.4.5), https://github.com/Azure/login/commit/24848bc889cfc0a8313c2b3e378ac0d625b9bc16.
- The latest release is [v1.4.6](https://github.com/Azure/login/tree/v1.4.6), https://github.com/Azure/login/commit/92a5484dfaf04ca78a94597f4f19fea633851fa2.

So the SHA-ref could be upgraded to either
- `azure/login@24848bc889cfc0a8313c2b3e378ac0d625b9bc16` for v1.4.5 or
- `azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2` for v1.4.6

Note `azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf` is used in six workflow files, and that's all uses of `azure/login` in `.github/workflows`.
```
grep -rn 'azure/login@1f63701' .github
.github/workflows/azure-staging-build-deploy.yml:48:        uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
.github/workflows/translation-health-report.yml:97:        uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
.github/workflows/main-preview-docker-cache.yml:33:        uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
.github/workflows/azure-prod-build-deploy.yml:37:        uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
.github/workflows/azure-preview-env-deploy.yml:74:        uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
.github/workflows/azure-preview-env-destroy.yml:38:        uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
```

**Comment by Cruzillian** [comment]
***@***.***
CruzLove Baby!
Y'all are great, and I mean that... It takes the whole lot of us to make
this all happen. So WHY would I even consider destroying something that so
much heart and soul went into making?! Because I'm being mistakingly judged
as one to be bitter about being sincerely excluded and treated like
a"liability", and swept under the rug? Look y'all, I'm gonna level with
you.. Facts are facts.. It's not that I DON'T appreciate money or have a
poor understanding of it's significance...I have NO love for money. Money
comes and goes, but m my dreams, Y'ALL'S dreams is what really matter.
Well, to ME at least. And with all due respect they should matter most to
you (the individual). I don't ever compromise my goals or dreams for anyone
or anything. And I fully accept it when it's apparent that sometimes my
goals and dreams just aren't part of God's greater plan to prosper us...
ALL of us. Because I kinda feel stupid when that happens. You know, like I
just didn't have what it took. And yeah it gets my heart to hurting a bit
and all, but I just check myself out of "vagina hurting BITCH mode" and
tell myself, "Damn, I feel stupid..." And keep moving forward.
Love y'all
-Julian Cruz III "JC"

**Comment by muzimuzhi** [comment]
@cmwilson21 Unfortunately no, the #24540 you mentioned only updates node12 action usages in files in directories `content`, `contributing`, and `data/reusables`, aka in doc examples.  Current issue reports node12 action usages in files in directory `.github/workflows`, aka the workflow files used by this repo itself.

Actually I did see #24540 before opening current issue. I should mention it at the first time.

**Comment by muzimuzhi** [comment]
> So the SHA-ref could be upgraded to either
> 
> * `azure/login@24848bc889cfc0a8313c2b3e378ac0d625b9bc16` for v1.4.5 or
> * `azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2` for v1.4.6

I'd like to leave the decision (upgrade to which version? though from release notes the difference is minimal) to the GitHub docs team/maintainers, hence didn't open a PR.

**Comment by cmwilson21** [comment]
@muzimuzhi Thanks for coming back and confirming! And thanks again for opening the issue 💖 

@heiskr Thanks for taking care of this one internally! 👍

**Comment by cmwilson21** [comment]
Closing this one out as it has been taken care of internally 💛

**Comment by muzimuzhi** [comment]
Just for the info, it's resolved by https://github.com/github/docs/commit/aad2cefd7c0c42a6715b6f6e9de6fae953fa6697.
