### ISSUE TITLE
Environment Protection Rules section has self contradicting information

### ISSUE THREAD

**Issue by Aninita** [github/docs#25466]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

### What part(s) of the article would you like to see updated?

Section to be changed:
"Note: Deployment protection rules are only available in public repositories if you are using GitHub Free, GitHub Pro, or GitHub Team. For access to deployment protection rules in private or internal repositories, you must use **GitHub Pro, GitHub Team**, or GitHub Enterprise. For more information on switching your subscription, see "[Upgrading your GitHub subscription](https://docs.github.com/en/billing/managing-billing-for-your-github-account/upgrading-your-github-subscription)."

What to change:
Github Pro and Github Team is mentioned as required to have Environment Protection Rules, but according to information in https://github.com/pricing it is only Github Enterprise that has this option. Pro is not mentioned, so here I don't know.

Perhaps this section should start with "Note: Environment deployment protection rules..." for clarification and alignment with the pricing information.

**Comment by cmwilson21** [comment]
@Aninita Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by kochalex** [comment]
My company is one teams and deployment protection rules are not available in the product for our private repositories.

**Comment by jc-clark** [comment]
Hey @Aninita thank you for raising this issue! I changed this article and deleted the note in question since it contained inaccurate information. Hopefully that solves the issue. 

The green banner at the top of the page outlines the plans needed for certain protection rules: 

> Environments, environment secrets, and environment protection rules are available in public repositories for all products. For access to environments, environment secrets, and deployment branches in private or internal repositories, you must use GitHub Pro, GitHub Team, or GitHub Enterprise. For access to other environment protection rules in private or internal repositories, you must use GitHub Enterprise. For more information, see "[GitHub’s products](https://docs.github.com/en/get-started/learning-about-github/githubs-products)."

@kochalex - The text in this box does say "for access to other environment protection rules..." which, I believe, is referring to what you listed `wait timer` and `required reviewers`. I can see how that information is a bit obscure and outdated though (these should be called deployment protection rules, not environment protection rules). I went ahead and opened an internal improvement issue to make the text on this banner more explicit. 

We'll be able to fix that up! 

For now, I'll close this issue out since we're working on fixing the text in another issue. Feel free to reopen if I missed something! Happy to take a closer look.
