### ISSUE TITLE
Please add some clarification on how to configure git to handle line endings

### ISSUE THREAD

**Issue by TristanHehnen** [github/docs#25578]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows#refreshing-a-repository-after-changing-line-endings

### What part(s) of the article would you like to see updated?

The four-step guide to refresh the repo is unclear to me, there seems to be information missing. Could you please include the steps (backup, delete and restore the files) of the second paragraph and also at what step the `.gitattributes` file is to be introduced? Further, does the "restore" in the second paragraph mean `git restore .` or is it something else?

How I followed the steps:
I did clone a repo (did not yet contain a `.gitattributes`) which has `LF` line endings and added a slightly adjusted version of the example  `.gitattributes`.  Following steps 1 and 2, this new file is not tracked/commited. Do I need to put in an extra commit for the  `.gitattributes` or is this the expected result? (I then decided to add it to the commit in step 1. I also specifically changed a file to `CRLF` which is added to the same commit, to check if the procedure works.)

After that, I copied the content of the directory, deleted all files (except the `.git` directory) and copied the files back in. Then proceeded with step 2. However, `git status` (step 3) does not recognise any changes to the files so there is no new commit to be made (step 4). Maybe I've misunderstood something in the "backup, delete and restore the files" procedure - could there some more information added, please?

While adding the  `.gitattributes` and the specifically adjusted test file to the commit in step 1, a message was presented that the file endings will be changed the next time git touches the files. Apparently, neither `git add`, `git commit` and `git push` are considered "touched by git", even though the files were changed explicitly. I deleted my local repo and cloned the pushed version again, then the line endings seemed to be set as expected. 
Is this the expected behaviour, to delete and clone the repo again after these steps?

**Comment by cmwilson21** [comment]
@TristanHehnen Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

In the mean time, feel free to check in with our wonderful [support team](https://support.github.com/request) with these issues. ✨

**Comment by isaacmbrown** [comment]
Hi @TristanHehnen, thank you for opening this issue! I agree that this procedure is looking slightly confusing right now.

From what I can work out, `git add --renormalize .` should automatically update all tracked files in the repository to use the specified line endings. For example, from `git-scm.com: 

> **--renormalize**
> Apply the "clean" process freshly to all tracked files to forcibly add them again to the index.

To me, this means you don't need to go through the process of first deleting all your files and then restoring them. I think what has probably happened is that when the `--renormalize` flag was added to Git, we updated the procedure, but didn't think to update the introductory paragraph you're talking about. **But I'm going to check this is the case.**

> Following steps 1 and 2, this new file is not tracked/commited. Do I need to put in an extra commit for the .gitattributes or is this the expected result? (I then decided to add it to the commit in step 1. I also specifically changed a file to CRLF which is added to the same commit, to check if the procedure works.)

I think this section is to be taken in isolation. It assumes you have either already committed a `.gitattributes` file, or set up the configuration option: "When you set the core.autocrlf option or commit a .gitattributes file, you may find that Git reports changes to files that you have not modified." **This may be something we should clarify.**

**Comment by isaacmbrown** [comment]
https://git-scm.com/docs/gitattributes#_end_of_line_conversion shows an example using `git add --renormalize` straight after updating the `.gitattributes` file, without first deleting and restoring the contents of the repository:

> From a clean working directory:

```
$ echo "* text=auto" >.gitattributes
$ git add --renormalize .
$ git status        # Show files that will be normalized
$ git commit -m "Introduce end-of-line normalization"
```

I believe this is the approach we'll want to take here. More notes to follow.

**Comment by isaacmbrown** [comment]
> After that, I copied the content of the directory, deleted all files (except the .git directory) and copied the files back in. Then proceeded with step 2. However, git status (step 3) does not recognise any changes to the files so there is no new commit to be made (step 4). Maybe I've misunderstood something in the "backup, delete and restore the files" procedure - could there some more information added, please?

Git won't recognise any changes to the files if you just remove them all and add them straight back, without committing in between. If you were to do this, the procedure would need to be something like:

1. Add and commit `.gitattributes`
2. Remove all files in the repository except `/.git`
3. Start the procedure in the docs at step 1

However, I don't think this is necessary in the context of what we're trying to do.

> While adding the .gitattributes and the specifically adjusted test file to the commit in step 1, a message was presented that the file endings will be changed the next time git touches the files. Apparently, neither git add, git commit and git push are considered "touched by git", even though the files were changed explicitly.

As I understand it, Git "touches" a file if it updates its content in your working directory on your behalf. This happens, for example, if you check out a different branch, or merge in another branch, where the contents of a file is different. In these situations, Git will also update the line endings to match your new configuration. Modifying a file yourself won't trigger this, and nor will `git add` `git commit` or `git push` -- these don't actually "touch" a file; they are operations on the Git database.

> I deleted my local repo and cloned the pushed version again, then the line endings seemed to be set as expected. Is this the expected behaviour, to delete and clone the repo again after these steps? 

This is apparently because `git add --renormalize` affects your staging area, but not your working directory. It adds files to your staging area with corrected line endings, which you can then commit and push. However, it doesn't actually affect the local versions of the files in your working directory. That's why re-cloning the repository set the line endings as expected. I think we can document this.

I think we need to reframe this section of the docs slightly -- it is about updating line endings so that other contributors to a repository don't run into lots of modified files. If I'm a user who runs into lots of modified files, I probably just want to back out of the changes so I can commit just the files I'm intending to.

**Comment by Radman0915** [comment]
سلام واقعا مورد اعتمادیداما میتوانید زبانهای بینهاد گوگل رابرای اینجا بزاریدکه نیازبه ترانسلیت نباشه

**Comment by isaacmbrown** [comment]
We actually updated this section independently as part of another issue: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows#refreshing-a-repository-after-changing-line-endings

It looks like we removed the `git add --renormalize .` command altogether, and outlined the steps for removing and restoring files.
