### ISSUE TITLE
ui: sidebar with brand color

### ISSUE THREAD

**Issue by kamaroolkarim** [github/docs#265]
### What is the current behavior?

May I know the reason you guys are using blue color on sidebar? The background color is great but I think it has breached your design system which it supposedly to come in black.

![Screen Shot 2020-10-08 at 20 36 47](https://user-images.githubusercontent.com/6109672/95459295-064f1800-09a6-11eb-949f-db192de988a7.png)

### What changes are you suggesting?

As a Product Designer myself, I think it's better to follow the GitHub design system for the documentation as well. 

![Screen Shot 2020-10-08 at 20 24 57](https://user-images.githubusercontent.com/6109672/95458476-cb001980-09a4-11eb-8bba-1a66dee9cc08.png)

![Screen Shot 2020-10-08 at 20 50 28](https://user-images.githubusercontent.com/6109672/95460742-e882b280-09a7-11eb-9cf8-b6462a93c8be.png)

**Comment by janiceilene** [comment]
Thanks for the feedback @kamaroolkarim!

Both the black you’ve shown and the blue that we’re currently using are “brand” colors. For public information about our style guidelines, you can consult https://primer.style. The Docs site was designed by our in-house creative team and conforms to both our branding and style guidelines as well as industry best practices for web accessibility. Because of this, we’re not looking to make design changes especially with regard to the use of color in the documentation.

Thanks for your passion and interest in our new open source documentation!

**Comment by kamaroolkarim** [comment]
alright @janiceilene . thank you for your clarification 😃
