### ISSUE TITLE
UI/UX: Navbar active link's styling for all section should be same for better user experience

### ISSUE THREAD

**Issue by dwarcash** [github/docs#268]
### What is the current behavior?

👉 Opening navbar, in language selector, selected language as **active link styling is not same** as the version selector's

👉 In mobile site, selected language in drop down is **not much visible** as the selected one

![Screenshot 2020-10-08 190922](https://user-images.githubusercontent.com/71209082/95468466-2b3e8d80-099c-11eb-963b-d18c455f6a0f.jpg)
![Screenshot 2020-10-08 192407](https://user-images.githubusercontent.com/71209082/95468472-2c6fba80-099c-11eb-8216-048d3b703ee1.jpg)
![Screenshot 2020-10-08 190857](https://user-images.githubusercontent.com/71209082/95468475-2d085100-099c-11eb-9a8b-3cbdee9634b7.jpg)

### What changes are you suggesting?

👉 For better User Experience, **active links should be same** on both sections

👉 In mobile view, setting active language styling same as version section **has a better user experience**

![Screenshot 2020-10-08 195605](https://user-images.githubusercontent.com/71209082/95472836-1e706880-09a1-11eb-9e7a-606414c7d2e2.jpg)
![Screenshot 2020-10-08 195652](https://user-images.githubusercontent.com/71209082/95472841-1f08ff00-09a1-11eb-826d-2b243f2199a3.jpg)
 

**Additional information**
No additional information

**Comment by janiceilene** [comment]
Thanks for the feedback @dwarcash!

Both the black you’ve shown and the blue that we’re currently using are “brand” colors. For public information about our style guidelines, you can consult https://primer.style. The Docs site was designed by our in-house creative team and conforms to both our branding and style guidelines as well as industry best practices for web accessibility. Because of this, we’re not looking to make design changes especially with regard to the use of color in the documentation.

Thanks for your passion and interest in our new open source documentation!

**Comment by janiceilene** [comment]
Thanks for opening an issue @dwarcash! I'll triage this for @github/docs-engineering to respond 🌟

**Comment by dwarcash** [comment]
Thanks for reopening @janiceilene !
