### ISSUE TITLE
Environment variable docs are inconsistent about GITHUB_ prefix

### ISSUE THREAD

**Issue by nex3** [github/docs#2693]
The [Naming Conventions for Environment Variables](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#naming-conventions-for-environment-variables) documentation says:

> **Note:** GitHub reserves the `GITHUB_` environment variable prefix for internal use by GitHub. Setting an environment variable or secret with the `GITHUB_` prefix will result in an error.

However, the example in [`jobs.<job_id>.steps[*].env`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv) sets a `GITHUB_TOKEN` environment variable. Which is correct?

**Comment by janiceilene** [comment]
Thanks for opening an issue @nex3! I'll triage this for the team to take a look 👀

**Comment by hubwriter** [comment]
Hi @nex3 - Many thanks for raising this issue. 👍 

Both of the pages you refer to are correct. The `GITHUB_` name is reserved for use by GitHub. One such use is the `GITHUB_TOKEN` secret that allows you to reference an automatically created GitHub App installation access token in an Actions workflow, as shown in the example on the second page you refer to.

For more information about `GITHUB_TOKEN` see: https://docs.github.com/en/actions/reference/authentication-in-a-workflow

I'm going to close this issue, but thanks for checking this with us and, of course, if you'd like to discuss this more please get back to us.

**Comment by nex3** [comment]
@hubwriter The issue is that the example in `jobs.<job_id>.steps[*].env` doesn't just reference the `GITHUB_TOKEN` secret, it actually *sets* an environment variable named `GITHUB_TOKEN` to the value of that secret, which is forbidden according to the environment variable docs.

**Comment by hubwriter** [comment]
@nex3 - Thanks for coming back about that. 👍🎖️ 
I think we need to change the env var name here: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv 
I'll get that confirmed here and then we can ask for a community quick fix of that page.

**Comment by hubwriter** [comment]
The text in the note box is incorrect. The `GITHUB_TOKEN` environment variable is often set in a workflow, and we have examples of this in the documentation. I've tested setting environment variables in workflows and using the `GITHUB_` prefix does not result in an error. However, if you try to set a value to the default ones listed in the table [here](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables), the assignment does not work.

So we should remove the note on that page and replace it with a statement about trying to reuse the names of the default env vars.

i.e. in `content/actions/reference/environment-variables.md`, change:

```
{% note %}

**Note:** {% data variables.product.prodname_dotcom %} reserves the `GITHUB_` environment variable 
prefix for internal use by {% data variables.product.prodname_dotcom %}. 
Setting an environment variable or secret with the `GITHUB_` prefix will result in an error.

{% endnote %}
```

to a simple paragraph (rather than a note):

```
When you set a custom environment variable, you cannot use any of the default environment variable names 
listed above with the prefix `GITHUB_`. If you attempt to override the value of one of these default 
environment variables, the assignment is ignored.
```

@nex3 - Many thanks again for raising this, and for coming back when I incorrectly closed the issue. Kudos to you for bringing this to our attention.
