### ISSUE TITLE
Remote URL is not showing up

### ISSUE THREAD

**Issue by TonyStark-47** [github/docs#27088]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github

### In this section: [Adding a local repository to GitHub using Git](https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github#adding-a-local-repository-to-github-using-git) at 5th point:
The command should be `$ git remote add origin https://github.com/OWNER/REPOSITORY.git` instead of `git remote add origin`

**Screenshots:**
![Screenshot from 2023-07-26 22-53-13](https://github.com/github/docs/assets/73957207/88c68005-b667-4049-83e0-30de68b4761c)

**Screenshot of code:**

![Screenshot from 2023-07-26 23-05-01](https://github.com/github/docs/assets/73957207/987cc6f1-5386-4562-8b3a-08569665a8a7)

**Comment by cmwilson21** [comment]
@TonyStark-47 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by subatoi** [comment]
Hi @TonyStark-47 many thanks for this—

The reason for it is because the reusable `unstage-codeblock` contains an `<em>` tag that means that anything in angle brackets in a `shell` code fence doesn't render correctly at the moment. We're working on a longer term fix but for the moment, I've raised a PR to fix this internally with you as co-committer, since it's a bug and we should ideally fix it ASAP.

You'll see this issue close when the PR merges. 

Thanks again for your interest and help ✨
