### ISSUE TITLE
Markdown render issue in "Adding your SSH key to the ssh-agent"

### ISSUE THREAD

**Issue by james-pcdr** [github/docs#27081]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Confirmed on both Firefox and Chrome.

### What changes are you suggesting?

Steps:
1. Navigate to the above-mentioned page
2. For the Operating System, click "Windows"
3. Scroll down to the section "Adding your SSH key to the ssh-agent"

Expected Result: there should be six correctly-rendered steps in this section.
Actual Result: After step 2, the steps are rendering incorrectly. This is evidenced by the following visible (unrendered) markup:

- `[AUTOTITLE]` 
- `</div>`
- `<div class="ghd-tool linux">`

### Additional information

Within the Linux tab of the same page, the section "Adding your SSH key to the ssh-agent" is mostly empty. It's possible that the Windows issue described above is causing this.

**Comment by subatoi** [comment]
Hi @james-pcdr and thanks for spotting this and raising the issue!

You're absolutely right about the bug: the indentations on some of the reusable content don't line up correctly, which is what causes this behaviour.

Since this is a bug, we'll fix it internally and close this issue from our internal repository, but we'll add you as a co-committer on the PR.

You should see this issue close when that happens, soon.

Thanks again for your interest and help in the GitHub docs ✨
