### ISSUE TITLE
Add missing status code to list repositories for a user

### ISSUE THREAD

**Issue by emileferreira** [github/docs#27124]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user

### What part(s) of the article would you like to see updated?

When requesting the list of repositories for a nonexistent user, a `404` status code is returned. This behaviour is not documented for the `/users/{username}/repos` endpoint. I suggest that this be added to the documentation.

### Additional information

I believe that this content is generated from internal code, so I cannot make a pull request.

**Comment by cmwilson21** [comment]
@emileferreira Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for this issue! We generally don't require common responses (like 404, 429, 500) to be documented, though some endpoints do document these responses. I shared your issue internally to suggest that we either consistently document or don't document 404 responses. Since this needs to be addressed internally, I am going to close this issue.
