### ISSUE TITLE
Clickable link issue for stubby thumbs

### ISSUE THREAD

**Issue by nntrn** [github/docs#27453]
clickable region for sidebar links are misleading because they have block-level hovers but only clickable inline

<img height="324" src="https://github.com/github/docs/assets/17685332/d19b7537-39f7-42d8-9817-b8e384949e54">

---
_Originally posted by @nntrn in https://github.com/github/docs/issues/27422#issuecomment-1677833410_

**Comment by cmwilson21** [comment]
@nntrn 😄 Thanks for opening an issue! I meant to direct you to do this from your PR, so thanks for reading my mind 😆 

I'll get this triaged for review, but would you mind updating the top with a quick description? Or a copy/paste from your PR, just so the reviewer can quickly read over it? That'll really help!

**Comment by cmwilson21** [comment]
@nntrn Thank you! 🎉

**Comment by cmwilson21** [comment]
@nntrn Thanks again for opening an issue! I reported this to the team and they are already working on it internally! Since it's a known bug that they are currently working on, I'm going to go ahead and close this issue 💛 

Thanks again for raising it, and thanks for your interest in improving the docs! ✨
