### ISSUE TITLE
REST API explain that Packages are created using a package manager

### ISSUE THREAD

**Issue by mirobertod** [github/docs#27853]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

There is no doc for creating new packages or editing permissions for an already existing one.

----

_Maintainer update_

## Response to question on missing congtent

I checked in with an subject matter expert on this issue. They said:

> Packages can be published through client CLIs such as npm or docker, or through Actions, but not via the REST API.

## Content updates required to fix this issue

We can make this clearer to users by updating the introductory section for the REST API Packages reference docs. This part of the article is not automatically generated and can be fixed with a pull request to this repository. Any changes must be restricted to this section of the article: https://github.com/github/docs/blob/main/content/rest/packages/packages.md?plain=1#L17-L30.

Update the [About GitHub Packages](https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#about-github-packages) section as follows:

1. Revise the first paragraph to mention that GitHub Packages supports a range of package managers for publishing packages and that once you have published a package you can use the REST API to manage it.
2. Include a link to [Introduction to GitHub Packages](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#supported-clients-and-formats) for more information.

**Comment by cmwilson21** [comment]
@mirobertod Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
Based on the current documentation, it seems unlikely that we have support for creating or editing packages:

- The article about publishing packages has no information about API options: [Publishing a package](https://docs.github.com/en/packages/learn-github-packages/publishing-a-package).
- The article about deleting and restoring packages has an API section, which aligns with the endpoints reported by the REST API for packages: [Packages API support](https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package#packages-api-support).

I'll add a request for a subject matter expert to check into this, but this looks as if this is undocumented because it's not supported.

**Comment by felicitymay** [comment]
Hi @mirobertod 👋🏻 

I checked in with an subject matter expert on this issue. They said:

> Packages can be published through client CLIs such as npm or docker, or through Actions, but not via the REST API.

I think we could make this clearer by updating the [introduction to the REST API endpoints for Packages](https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28) to mention that GitHub supports a range of package managers, and link to [Introduction to GitHub Packages](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#supported-clients-and-formats).
