### ISSUE TITLE
Java instructions are bad

### ISSUE THREAD

**Issue by AMDphreak** [github/docs#28170]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

What is up with these instructions on the Java page? It tells you to use a template then immediately tells you to add a dev container configuration, when it already has one.

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/setting-up-your-java-project-for-codespaces

So which one is it? Whoever made this document needs to get their ducks in a row. Another thing: don't obfuscate steps by linking to another page mid-paragraph. If you need instructions from another document, you put those at the top of the article, where a person can decide if those articles are more relevant or less relevant before reading this one. Yeah, nothing makes my day like someone putting a #include right in the middle of an algorithm.

### What part(s) of the article would you like to see updated?

Java

### Additional information

From Discussion https://github.com/github/docs/discussions/28124#discussion-5608900

**Comment by cmwilson21** [comment]
@AMDphreak Thanks for opening an issue! I'll get this triaged for review! :zap:

**Comment by hubwriter** [comment]
@AMDphreak - Many thanks for raising this issue.

The purpose of this tutorial is (as stated in the introduction) to "step you through the process of opening the project in a codespace, and adding and modifying a predefined dev container configuration." The intention is that "After you complete this tutorial, you'll be able to add a dev container configuration to your own repository."

It's useful to use a template repository, for the purpose of a tutorial, because it provides a ready-made repository for us to work with in the tutorial, however we want to show readers how they can add a devcontainer configuration to their Java repository which, if they haven't set it up for Codespaces yet, is unlikely to contain one. We therefore step you through the process of how to add a devcontainer configuration file.

I hope this explains things. I'm going to close this issue as works-as-designed.

But thanks again for raising this.
👍
