### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by iulia-b** [github/docs#2910]
Testing a feature on public repo inside an org
#2910 
https://github.com/lemongrasss/private-repo/issues/3
??

**Comment by iulia-b** [comment]
closing test issue

**Comment by iulia-b** [comment]
@lukewar this is public

**Comment by lukewar** [comment]
Cool! From: Iulia Bejan <notifications@github.com>Date: Thursday, 21 January 2021 at 12:41To: github/docs <docs@noreply.github.com>Cc: Lukasz Warchol <lukewar@github.com>, Mention <mention@noreply.github.com>Subject: Re: [github/docs] Test issue (#2910)Reopened #2910.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lukewar** [comment]
Yay!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
