### ISSUE TITLE
Standardized slack alert fails broke various workflows 

### ISSUE THREAD

**Issue by jsoref** [github/docs#29269]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Anything that triggers the no-response.yaml or triage-issue-commentsbworkflows

### What changes are you suggesting?

Add a `uses: actions/checkout@v4` step to workflows that use a local action 

### Additional information

@heiskr added a uses without ensuring the repository was available: https://github.com/github/docs/commit/4a534c5d82018cb2d14fb6978b7de3c359a08ad1

https://github.com/github/docs/actions/runs/6533452061
https://github.com/github/docs/actions/runs/6533452064

**Comment by peterbe** [comment]
"Triage new issue comments" is now working. Latest here: https://github.com/github/docs/actions/runs/6613849067/job/17962533820

"No response" is now working. Latest here: https://github.com/github/docs/actions/runs/6614085668/job/17963257755

In both of those latest runs, the step doesn't actually send anything to Slack but that's because there wasn't a prior failure. But the links that @jsoref pointed out were about the composite action even being able to start at all due to the lack of a actions/checkout step above it.
