### ISSUE TITLE
Example of caching npm packages errantly uses `npm ci` to install

### ISSUE THREAD

**Issue by matatk** [github/docs#2955]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/guides/building-and-testing-nodejs#example-caching-dependencies

### What part(s) of the article would you like to see updated?

The example that shows how to cache npm packages includes use of the `npm ci` command. However [`npm ci` deletes any existing "node_modules/" directory when it starts](https://docs.npmjs.com/cli/v6/commands/npm-ci) so I think you should have `npm install` there instead.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @matatk! I'll triage this for the team to take a look 👀

**Comment by lumaxis** [comment]
Hey @matatk! It's true that any existing `node_modules` folder gets deleted when `npm ci` is run and I can understand how that can be confusing here.

However, in most cases, since Actions workflows run in a clean environment on a runner, there usually is no existing `node_modules` folder anyway. Therefore, it makes more sense to cache the `~/.npm` folder which contains the "global" npm cache (more on that in our [`npm cache` docs](https://docs.npmjs.com/cli/v6/commands/npm-cache#details), if you're interested).

Additionally, `npm ci` does have some performance benefits over `npm i` in cases where `node_modules` are missing, plus there are a few behavioral differences too where it ensures the consistency of the `package-lock.json` for example: https://docs.npmjs.com/cli/v7/commands/npm-ci#description

Hope that helps clear this up! Let me know if you have further questions.

**Comment by janiceilene** [comment]
It doesn't sound like we need any updates to the docs, so I'm going to close this 💖 Let me know if there's anything I missed!

**Comment by matatk** [comment]
Thanks @lumaxis for your very helpful explanation—this all makes sense to me now, and I will switch to `npm ci` in my own Actions workflows.
