### ISSUE TITLE
Shell code formatting is incorrect 

### ISSUE THREAD

**Issue by igorjcl** [github/docs#29644]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/pt/authentication/troubleshooting-ssh/error-permission-denied-publickey#make-sure-you-have-a-key-that-is-being-used

### What part(s) of the article would you like to see updated?

Shell code formatting is incorrect:

![image](https://github.com/github/docs/assets/16910056/7f5ec475-028c-452c-a3ef-95c7ebc9a489)

This incorrect formatting can make it difficult to read the documentation.

**Comment by subatoi** [comment]
Thanks @igorjcl—could I just clarify, do you mean this section of the content? https://github.com/github/docs/blob/main/content/authentication/troubleshooting-ssh/error-permission-denied-publickey.md?plain=1#L63-L68

Because part of the comment is syntax-highlighted? 

![Image](https://github.com/github/docs/assets/32935794/838e5877-079e-4871-b5f5-5c388db1b049)

**Comment by igorjcl** [comment]
@subatoi, I found the problem in the file windows_git_for_windows_turn_on_ssh_agent.md, which is being used when using Windows.

https://github.com/github/docs/blob/aa81d709ed1a4de2c5c580d95cbf1eaedc604f5a/data/reusables/desktop/windows_git_for_windows_turn_on_ssh_agent.md?plain=1#L1C1-L7C8

**Comment by subatoi** [comment]
@igorjcl Ah, thank you very much! I didn't realise you'd actually taken a screenshot of the rendering; I thought it was one of the Markdown. I'll look into that now 👍
