### ISSUE TITLE
Permissions required for fine-grained personal access tokens document does not mention about Private repository invitations

### ISSUE THREAD

**Issue by meetDeveloper** [github/docs#29711]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens

### What part(s) of the article would you like to see updated?

I was going through permissions we can configure when creating a fine grained personal access token and noticed that I had option to grant `Private repository invitations` permission as shown in image below.

<img width="768" alt="image" src="https://github.com/github/docs/assets/32453612/9f14d82b-d5b5-487c-93e0-00a16245607c">

However, when I visited [Permissions required for fine-grained personal access tokens](https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28), I was not able to find any such permission listed there.

**Comment by skedwards88** [comment]
Thanks for this issue! I'm checking on this internally.

**Comment by skedwards88** [comment]
I bumped the SME team again.

**Comment by skedwards88** [comment]
From talking with our SMEs, it sounds like this permission is used for the `GET /user/repository_invitations` endpoint. The endpoint can still be used without this permission, but repos that the token does not have permission to view will not be returned. The SME team is working on a fix. Since these docs are autogenerated and will be fixed automatically following the SME fix, I'm going to close out this issue. Thanks again for raising it!
