### ISSUE TITLE
Wrong link for list of GH hosted runners

### ISSUE THREAD

**Issue by sebbASF** [github/docs#30323]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#using-a-github-hosted-runner

### What changes are you suggesting?

The above-mentioned paragraph says:

For the full list of runner types, see "[Using GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)."

However that page does not have the information; it is currently further down the same page at:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

### Additional information

Also the page URL has a duplicated path element:

.../about-github-hosted-runners/about-github-hosted-runners#...

Was this intended?

### How to fix (maintainer note)

On line 41 https://github.com/github/docs/blob/main/content/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners.md?plain=1#L41

The AUTOTITLE path currently links to /actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

It _should_ be linking to /actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by myarb** [comment]
@sebbASF Thanks for opening an issue! I’ll get this triaged for review :sparkles:

**Comment by subatoi** [comment]
Hi @sebbASF thanks for raising an issue!

There's a few things to note here:

> For the full list of runner types, see "[Using GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)."

> However that page does not have the information; it is currently further down the same page at:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

The reason it shows up as "Using GitHub-hosted runners" is because we use something called "AUTOTITLE". You can see on [line 41 of the page in question](https://github.com/github/docs/blob/main/content/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners.md?plain=1#L41) how it's used there and you can read more about how AUTOTITLE works [in our public docs on the subject](https://docs.github.com/en/contributing/writing-for-github-docs/using-markdown-and-liquid-in-github-docs#internal-links-with-autotitle).

Essentially, AUTOTITLE won't work with anchors but will render the whole title.

_However_, in this case, as you'll note on line 41, the AUTOTITLE reference there is linking to `/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources`. It should be linking to `/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources`, so it's missing part of the path.

That's the change we need to make here, and you or anyone else is welcome to do so!

Finally, to your last point:

> Also the page URL has a duplicated path element:

> .../about-github-hosted-runners/about-github-hosted-runners#...

> Was this intended?

This is following our [content model](https://docs.github.com/en/contributing/writing-for-github-docs/templates#conceptual-article-template). I agree it's a little bit awkward here but it's essentially because "larger" runners are under the same umbrella as "GitHub-hosted runners" and we need to make both sets of content discoverable. You can see the same path structure for example in https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners. Nonetheless I'll pass your feedback on to the Docs team who manage this content.

Thanks again for your interest in the docs!

**Comment by mark-mxwl** [comment]
I've created a PR for this issue. Thx @sebbASF for spotting this one, and thx @subatoi for confirming the correct link! 👏

**Comment by Adelao4** [comment]
Noted
