### ISSUE TITLE
Problem with selecting licenses following the instruction

### ISSUE THREAD

**Issue by alin256** [github/docs#30950]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

The article contains a lot of licenses for which there are no available templates currently on GitHub. I cannot make BSD 4-Clause License show correctly on my repository sidebar even though it is listed on the help page. 
However, I can find older repositories for which it shows correctly: https://github.com/m-bain/whisperX

Is there some magic keyword that makes license text linkable to the license name as here: 
<img width="1169" alt="Screenshot 2024-01-05 at 15 12 22" src="https://github.com/github/docs/assets/7563037/3ef7a982-348b-4532-ae02-1967a2b3ee11">

### What part(s) of the article would you like to see updated?

List of licenses on the page should be updated here
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

or an explanation of how to add a license should be modified here:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by nguyenalex836** [comment]
@alin256 Thank you for opening this issue! ✨ 

You're right in that the relevant [doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) does not include instructions on how to add the less commonly used licenses (e.g. BSD-4 Clause), which requires copy / pasting the license text in. I'll have our team review this in order to explore adding these instructions to the doc.

In the meantime, to add the BSD-4 Clause license - you can reference this [helpful appendix](https://choosealicense.com/licenses/bsd-4-clause/#), select the BSD-4 Clause license, and copy/paste the license text in manually -

<img width="916" alt="image" src="https://github.com/github/docs/assets/150945400/5ff1d216-8b6d-457f-a48e-cf0807add759">

![image](https://github.com/github/docs/assets/150945400/f881dfd4-353d-4846-a1dd-947e8702fc73)

This will populate the populate the sidebar with the correct license, which I tested on my end -

![image](https://github.com/github/docs/assets/150945400/338f03ab-68dc-4dbe-ba60-80d155498188)

The appendix referenced above can be found in this [doc](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), just as a heads up 💛 Submitting this now for our team to review updating the doc instructions!

**Comment by alin256** [comment]
Dear @nguyenalex836,

I raised this issue because copy-pasting does not work. I.e. the license identifier on the right and the license description on the top does not correlate with the pasted text. 

For example in my repository, after some experimentation, I choose BSD-3-Clause template and rewrote everything inside it still to have BSD-3-Clause written over it. Because at some point I applied the BSD-3-Clause template.

![IMG_0192](https://github.com/github/docs/assets/7563037/abca4190-c022-48a3-9529-a079c31b0a59)

**Comment by nguyenalex836** [comment]
@alin256 Thank you for letting me know! You would need to create a new `LICENSE.md` file in order to paste in the BSD-4 Clause license content - 

1. Go to your repo and click "Add file" ---> "Create new file"

![image](https://github.com/github/docs/assets/150945400/e13b9a9f-1155-4294-9c55-076a949dbc36)

2. Instead of choosing a license template, name the new file `LICENSE.md`

<img width="473" alt="image" src="https://github.com/github/docs/assets/150945400/5143e956-ab46-46c6-862b-69c42308346c">

3. Go to https://choosealicense.com/licenses/bsd-4-clause/# and copy the license text

![image](https://github.com/github/docs/assets/150945400/d93c24b5-9994-410f-ac9b-007a83bd28de)

4. Go back to your new `LICENSE.md` file and paste the license text in

![image](https://github.com/github/docs/assets/150945400/7619d7b3-81df-4980-b1c4-844639154ecc)

5. Commit your changes / create the new file

6. You may then delete the BSD-3 Clause license you have been previously working with ✅ 

If after following these instructions you are still unsuccessful, I would strongly suggest reaching out to our fantastic [support team](https://support.github.com/request) for additional assistance 💛

**Comment by alin256** [comment]
Dear @nguyenalex836,

For some reason, your solution works (maybe the magic is calling it .md?!).
It would be a great help for GitHub users if the manual you provided is communicated on the relevant help page.

Would it work from any of the licenses listed in https://choosealicense.com/appendix/ ?

**Comment by nguyenalex836** [comment]
@alin256 Glad to hear that!

> It would be a great help for GitHub users if the manual you provided is communicated on the relevant help page.

I will let our team speak to this when they review this issue!

> Would it work from any of the licenses listed in https://choosealicense.com/appendix/ ?

I am unsure, but questions like these would be best addressed by our fantastic [support team](https://support.github.com/request) 💛

**Comment by alin256** [comment]
@nguyenalex836 

I encountered a problem when modifying the data in the bsd-4-clause that we discussed.
If I put full details of my project in the LICENSE.md, as the clause #3, the  BSD-4-Clause license label disappears from the repository.

I assume there is some comparison of the license file to a template which breaks if the project name is too long. I tried back and forth, e.g. this commit:

"This product includes software developed by the DISTINGUISH project (Decision support using neural networks to predict geological uncertainties when geosteering, Research Council of Norway grant #344236)."

https://github.com/geosteering-no/spade-gan-inversion/commit/f60f08956d19f74166dfe28297ece2390cf7b27c

Can you follow up with the backend team to clarify how the underlying logic works.

**Comment by nguyenalex836** [comment]
Hi @alin256 - the topics you raised in your last comment would be best addressed by our fantastic [support team](https://support.github.com/request). I'm going to go ahead and close this issue 💛
