### ISSUE TITLE
Deleting Pull Request on Enterprise

### ISSUE THREAD

**Issue by natashamm** [github/docs#31455]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.9/admin

### What part(s) of the article would you like to see updated?

Add a section to the Enterprise administrator docs about how to delete a pull request.

**Comment by nguyenalex836** [comment]
Hi @natashamm 👋 ! While you are unable to delete a pull request, you can [close a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/closing-a-pull-request) ✨ 

If you need a pull request removed due to it containing sensitive information, you can reach out to our 
[support team](https://support.github.com/contact) for assistance. I'll go ahead and close this issue 💛

**Comment by natashamm** [comment]
Hi @nguyenalex836 I was actually referring to deleting a pull request on a self-hosted GitHub **_Enterprise_** instance. In my opinion it would be worth putting in the documentation because it is different from the process on GitHub.com.

To delete a pull request on GitHub enterprise:
1. Go to pull requests on the repository
2. Open the site admin dashboard
3. Go to Issues & Pull Requests
4. Click on the number of the pull request you want to delete
... etc.

**Comment by nguyenalex836** [comment]
@natashamm Apologies - thanks for clarifying, and providing those steps to reference! I'll get this triaged for review ✨

**Comment by mchammer01** [comment]
This needs to be re-opened.

**Comment by rachaelrenk** [comment]
Howdy @natashamm 👋  PR deletion for Enterprise Server is mostly cosmetic, even in the case of cleaning up sensitive data. We'll address this gap/suggestion internally, so closing this for now. Thanks again for taking the time to open this issue!
