### ISSUE TITLE
[DOCS] Spelling error in a Spanish translation

### ISSUE THREAD

**Issue by Panquesito7** [github/docs#31559]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/es/get-started/exploring-integrations/github-developer-program#ready-to-join-the-github-developer-program

### What part(s) of the article would you like to see updated?

The Spanish text in the mentioned section has a spelling error: `comañías` should be changed to `compañías`.

**Comment by nguyenalex836** [comment]
@Panquesito7 Thanks for reaching out, and flagging this! Since we us an internal, automated solution for translations, I will flag your request for our team 💛 

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨

**Comment by nguyenalex836** [comment]
@Panquesito7 Thank you again for raising the flag on this spelling error! While we do not have an ETA on when this will be fixed, the appropriate team has been notified ✨ I'll go ahead and close out this issue 💛
