### ISSUE TITLE
Add Windows Shell syntax examples to GitHub Actions Workflow commands

### ISSUE THREAD

**Issue by jessehouwing** [github/docs#31567]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?ref=jessehouwing.net&tool=powershell

### What part(s) of the article would you like to see updated?

Code samples in Windows Shell syntax.

In the past I've already contributed the `PowerShell` samples, I want to propose we add the Windows Shell examples as well. I have a blog post on that subject and it still draws quite a bit of traffic.

### Additional information

https://jessehouwing.net/github-actions-workflow-commands-in-cmd/

**Comment by nguyenalex836** [comment]
@jessehouwing Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by SiaraMist** [comment]
Hey @jessehouwing, thanks for opening this issue. 

We really appreciate the PowerShell examples you contributed in the past! Because Microsoft has switched to PowerShell over `CMD.EXE` as [their default shell](https://support.microsoft.com/en-us/windows/powershell-is-replacing-command-prompt-fdb690cf-876c-d866-2124-21b6fb29a45f) and they encourage people to use PowerShell instead, I don't see a case for [adding a new tool switcher](https://docs.github.com/en/contributing/writing-for-github-docs/creating-tool-switchers-in-articles) and updating all of our examples to include a Windows shell version. In light of that, I'm going to close out this issue.

Thank you for your thoughtful idea and contributions to the docs! 💛
