### ISSUE TITLE
translation error in Japanese

### ISSUE THREAD

**Issue by gyvm** [github/docs#31850]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#あなたの-github-pages-サイトに-apex-ドメインを使用する

### What part(s) of the article would you like to see updated?

[Using a subdomain for your GitHub Pages site](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#using-a-subdomain-for-your-github-pages-site) is translated to Japanese as "Using a apex for your GitHub Pages site"

Incorrect: `あなたの GitHub Pages サイトに Apex ドメインを使用する`
Correct: `あなたの GitHub Pages サイトにサブドメインを使用する`

**Comment by nguyenalex836** [comment]
@gyvm Thanks for reaching out, and flagging this! Since we us an internal, automated solution for translations, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
