### ISSUE TITLE
Suggested improvements to explanation of id-token: write

### ISSUE THREAD

**Issue by simonw** [github/docs#32320]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The explanation of what `id-token: read/write/none` means in a GitHub Actions workflow is still really confusing. Previous issues about this include:
- https://github.com/github/docs/issues/14626
- https://github.com/github/docs/issues/25952
- https://github.com/github/docs/issues/26481

I guess the most relevant article is this one: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings

### What part(s) of the article would you like to see updated?

Here's my understanding of this feature. Feel free to use any of this copy, or correct me if I got something wrong!

----

The `id-token: write` permission provides a workflow the ability to interact with external services that use OpenID Connect (OIDC).

The `write` value can be better interpreted as meaning "enabled" - no writes occur with this permission, and it does not imply that the workflow has the ability to write to anything within GitHub.

Instead, this permission allows the workflow to request an access token from an OIDC supporting external service, such as [PyPI](https://docs.pypi.org/trusted-publishers/) or [AWS](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) or [Google Cloud](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform).

When the GitHub Action workflow runs it will request a token from the relevant service. That service will be able to identify the workflow and repository that is making the request and will only return a token for workflows that it has been configured to allow.

A value of `id-token: read` is treated the same as `id-token: none` (the default) - workflows without `id-token: write` will be unable to request tokens from external services using OIDC.

**Comment by simonw** [comment]
The table on this page also mentions `id-token`, and reference `read` permissions: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

![CleanShot 2024-04-01 at 09 28 20@2x](https://github.com/github/docs/assets/9599/5c81c5ff-9f10-44af-977c-7cf42fdaaa0c)

I don't understand the relevance of `read` here.

**Comment by nguyenalex836** [comment]
@simonw Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@simonw Hello! 👋 Thank you for your patience while our team reviewed this issue! After discussing this issue with our technical writing team, we are going to loop in one of our Actions SMEs, given the complexity of this topic. 

We'll provide another update once the Actions SME has reviewed 💛

**Comment by nguyenalex836** [comment]
Received [response](https://github.slack.com/archives/C024S10L62E/p1713472249427089?thread_ts=1712333656.554029&cid=C024S10L62E) with some additional context - will wait for specific SME to chime in

**Comment by danielcompton** [comment]
@nguyenalex836 I can't speak for @simonw but for me that doesn't really make sense, or at least doesn't fully explain what `id-token: read` means.

**Comment by nguyenalex836** [comment]
@danielcompton Thank you for letting me know! 💛 Would you be open to raising a new, separate issue that includes the specific points that you are looking for clarity on regarding `id-token: read`?

**Comment by janbrasna** [comment]
I don't think this topic needs a new issue every single time a stale bot closes out the previous one;) I'm afraid it needs a better documentation explaining what the actual permission setting is and what it is for (not the whole OIDC workflow, that one clearly states when you need the permission, own-org vs. outside-org reusables etc. — but what the actual values for that permission mean, and if/when/how they can be set). Ex without the [great writeup about OIDC use for deploy-pages](https://github.com/actions/deploy-pages/issues/329#issuecomment-2030341950) I could have only guessed why such permission is necessary to grant, without any more explanation than to just blindly follow the boilerplate.

(In case of `deploy-pages`, the token here contains more info about the source event/repo protections wrt the environment to be deployed to, in a standardized way, that's not implicit on `GITHUB_TOKEN`, and GH apparently chose to consume their own OIDC mechanism instead of getting that info via GH API using the default token scope I guess…)

Connecting to cloud providers like AWS or GCP is pretty well documented here, but the issues cropping up repeatedly are about the **lack of documentation for**:
1. why **GH itself needs the permission** (and OIDC flow to start with) for Pages deployment (only mentioned by the authors above),
2. what does the **"read" permission really mean**, and why it can't be set, even though it's supposedly a valid value being used by default in some scenarios (and if that's a maximum permission for PRs from forks, what that means in real life, compared to "none").

I see it being rather unpopular topic with how often it ends up closed out by stale bot, but perhaps it's too obvious for engineers architecting the functionality, but without any visibility into how that values are then used for what in GHA code, we the end users are then left in the dark to just blindly trust the actions' instructions, or keep running in circles between unresolved issues trying to asses the potential impact this setting could have if not used correctly.

But if you really want, there's another confused consumer: 
- #33483 ;D

**Comment by nguyenalex836** [comment]
@janbrasna Thank you for the incredibly thoughtful comment! This is certainly a nuanced topic, but just to get us all on the same page, the next development / response on the `id-token:` front will be documented on the issue you linked above once our team has had a chance to discuss this further 💛 https://github.com/github/docs/issues/33483
