### ISSUE TITLE
LFX Mentorship is a new name for CommunityBridge

### ISSUE THREAD

**Issue by idvoretskyi** [github/docs#3241]
### What is the current behavior?

https://github.com/github/docs/blob/main/content/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository.md#about-funding-files

### What changes are you suggesting?

Community Bridge is now called LFX (specifically, LFX Mentorship for the mentoring purposes) - https://lfx.linuxfoundation.org/blog/introducing-lfx-tools-for-everyone/

Please update the wording where necessary.

**Comment by ethanpalm** [comment]
👋  Hi @idvoretskyi, this is a great addition to make our docs more accurate! You or anyone else are welcome to open a PR ✨

For whoever opens a PR, it would be helpful to refer to LFX Mentorship as "LFX Mentorship (formerly CommunityBridges)" since the syntax isn't changing and people may still search for CommunityBridges.

**Comment by idvoretskyi** [comment]
@ethanpalm great, I'm happy to submit a PR.

Is there any other place that needs to be updated except (https://github.com/github/docs/blob/main/content/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository.md#about-funding-files)?

**Comment by ethanpalm** [comment]
@idvoretskyi, I searched and that's the only article in the repo that mentions CommunityBridge. 👍

**Comment by idvoretskyi** [comment]
@ethanpalm here we go - https://github.com/github/docs/pull/3928
