### ISSUE TITLE
Documentation on generating a new SSH key incorrect for Windows

### ISSUE THREAD

**Issue by aissshah** [github/docs#3243]
### What is the current behavior?

The commands in [this article](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) on step 2 do not work on Windows.

### What changes are you suggesting?

The commands should be changed from `$ ssh-keygen -t ed25519 -C "your_email@example.com"` to `$ ssh-keygen.exe -t ed25519 -C "your_email@example.com"`

### Additional information

I was using Git bash on Windows 10

**Comment by aissshah** [comment]
Happy to work on this if required :)

**Comment by janiceilene** [comment]
👋 Thanks so much for opening an issue @aissshah! I've triaged this to have someone from the team take a look 👀

**Comment by shati-patel** [comment]
Hi @aissshah! Thank you for checking out our docs and opening this issue 😊 

The `ssh-keygen` command usually comes "built in" to Git Bash on Windows, so that's frustrating it doesn't work for you 😞  
Could I ask which version of Git Bash you're using? For example, in my case: 

   ```
   $ git --version
   git version 2.28.0.windows.1
   ```
   
   If you have an old version, it might be worth downloading a [newer version](https://gitforwindows.org/) of "Git for Windows". Let us know if you still have difficulties!

**Comment by aissshah** [comment]
Ahh that's a good shout. Turns out my version was `2.27.0.windows.1`

**Comment by aissshah** [comment]
@shati-patel I've updated my git version and the command works now. Interesting that it needed an exe for older versions though.

Anyways, thank you for the help! 😊

**Comment by shati-patel** [comment]
> @shati-patel I've updated my git version and the command works now. Interesting that it needed an exe for older versions though.
> 
> Anyways, thank you for the help! 😊

Hooray, I'm glad to hear that it worked 🎉 

I'll close this issue for now, but we can revisit it if it turns out to be a common problem!
