### ISSUE TITLE
Section headings on the main Spanish documentation page aren't translated

### ISSUE THREAD

**Issue by jsoref** [github/docs#32494]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/es

### What changes are you suggesting?

Translate these section headings:
* Get started
* Collaborative coding
* CI/CD and DevOps
* Security
* Client apps
* Project management
* Developers
* Enterprise and Teams
* Community
* More docs

### Additional information

Note that the next section headings are in Spanish:
* Introducción
* Popular (it's the same word in both languages; and the item changes for other languages)
* Ayuda y soporte técnico

<img width="963" alt="image" src="https://github.com/github/docs/assets/2119212/9f0115b7-db43-45a9-9be0-b6f05e875ea6">

(The same applies for other languages, I checked French and Russian, ...)

Note that there are `brand` terms that would never be translated including `GitHub` and `GitHub Actions`. I do not believe that the categories count as brand terms.

**Comment by nguyenalex836** [comment]
@Jsoref Thank you for flagging this! Since we us an internal, automated solution for our translated docs, I'll surface this request to our localization team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
