### ISSUE TITLE
Self-hosted Linux-based runners do not start properly when SELinux is enabled

### ISSUE THREAD

**Issue by bschonec** [github/docs#32592]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/configuring-the-self-hosted-runner-application-as-a-service#installing-the-service

### What part(s) of the article would you like to see updated?

There should be some reference to the proper SELinux context when enabling the runners on systemd-enabled distributions.

In "Step 6: Start the runner" of [this article](https://blog.dyrector.io/2023-11-08-are-github-self-hosted-runners-good-tutorial/) it mentions a minimal context for runsvc.sh.  I needed to "chcon -R system_u:object_r:usr_t:s0  <path to runner>" for the runner to start via systemd scripts.

**Comment by nguyenalex836** [comment]
@bschonec Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by namka279** [comment]
#32592

**Comment by namka279** [comment]
- [ ] [](url)

>

**Comment by Jeremiegmoore** [comment]
> * [ ]
> 
> >

**Comment by Jeremiegmoore** [comment]
> > * [ ]
> > 
> > >

**Comment by Jeremiegmoore** [comment]
> > * [ ]
> > 
> > >

[](url)

**Comment by ericsciple** [comment]
The problem is your admin can configure the SELinux on the machine to lock down all kinds of permission. When the runner fails to configure or start due SELinux, the customer needs to work with their admin to track down the required permission.

We had small patch [like this](https://github.com/actions/runner/blob/70746ff593636b07ad251a1525a3fabd1a7a36e9/src/Misc/layoutbin/systemd.svc.sh.template#L85) for SELinux, but might not able to catch all cases, especially for cases that needs to run arbitrary commands on the customer's machine like the one mentioned in the issue:

> chcon -R system_u:object_r:usr_t:s0

**Comment by bschonec** [comment]
@ericsciple, you are correct but the original reason for me opening this issue is that there isn't any mention of this in the documentation.
