### ISSUE TITLE
Translate docs.github.com to Arabic.

### ISSUE THREAD

**Issue by AbdelatifAitBara** [github/docs#32607]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All the website.

### What changes are you suggesting?

Translate all the docs into Arabic.

### Additional information

Hi,

I'm ready to start the project of translating the docs of GitHub Into Arabic, because it is the 4th most spoken language around the world with around 362 Million Native Speakers.

It will really be nice to allow people who speak only Arabic to understand GitHub.

Thank you.
Best regards.
Abdelatif.

**Comment by nguyenalex836** [comment]
@AbdelatifAitBara Thanks for reaching out! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
