### ISSUE TITLE
Docker container action does not get inputs that have hyphen in the name

### ISSUE THREAD

**Issue by ijpatricio** [github/docs#32671]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

### What part(s) of the article would you like to see updated?

So I followed the instructions on the page, and used an input like so:

```
        with:
          who-to-greet: Arnold
```

it turns out, after long trial and error, that hypen makes it not available on the Docker container.

I would suggest to make that a warning callout, and use underscores in the example.

I'm ready to make that PR if you agree with this, just let me know.

### Additional information

Below, you'll find what I tired, and marked them as working or not!

You can also see the action repo, so just reach out if any questions! https://github.com/unitedbycode/alfredo

![image](https://github.com/github/docs/assets/26031459/534e7c98-b721-4583-bd76-5edee45ec3d0)

**Comment by Mpl198** [comment]
Urgent Action Required: Potential Data Breach & Unauthorized Google Account
Access via Compromised GitHub Account


Dear GitHub Support,


This email serves as an urgent plea for immediate assistance regarding a
suspected data breach and unauthorized access to my Google accounts
(including primary account ***@***.***) likely facilitated through
GitHub. And lately ***@***.***

Background

* I am not a developer and never use GitHub.

* Despite proper credentials and two-factor authentication, I've been
locked out of my primary Google account for 15 months, raising serious
concerns of a potential breach.

* This situation has caused significant stress, anxiety, and disrupted my
daily life due to hampered communication and access to crucial accounts.

I've changed 5 Samsung A53 5gs, 3 Google pixel pro 7, phone number 5 house
routers

**Evidence Suggests:**

* Unauthorized code may have been uploaded to my GitHub account,
compromising my Google accounts.

* The ongoing lockouts, unwanted Google policy changes, iOS framework on an
Android devices, incorrect OS, cookie issues, and suspected finger/face
mirroring further strengthen these concerns.

**Request for Immediate Action:**

* **Account Security:** Please secure my GitHub account and prevent further
unauthorized access.

* **Code Identification & Removal:** If possible, identify the unauthorized
code and remove it from my account.

* **Regaining Google Account Access:** Guide me on regaining access to my
primary Google account considering the compromised GitHub link.

**Additional Information:**

* Due to the severity of the situation, I will be reporting this incident
to authorities like Action Fraud for a potential cybercrime investigation.

**Impact and Next Steps:**

This ongoing situation has had a significant negative impact on my mental
well-being and daily life. I expect prompt attention to this critical
issue. Please cooperate in resolving these problems and helping me regain
control of my accounts.

**Compensation:**

While my primary focus is regaining control and securing my accounts, I
will explore potential compensation options for the vulnerabilities caused.

Sincerely,

Michael Lennon

+447760354794

**Comment by nguyenalex836** [comment]
@ijpatricio Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by ijpatricio** [comment]
@nguyenalex836 glad I can help!! Let me know if should I do that PR to docs, thank you for all your work!

**Comment by sunbrye** [comment]
Hi @ijpatricio 👋 Thanks for taking the time to fill out this issue! ⭐ After reviewing and testing the workflow and action file, we believe that the error you ran into may not be related to hyphen syntax. Attached is the successful log output from the examples provided from [Creating a Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action).
We will close the issue with no further actions. Thank you for understanding and being a valued part of our community.

![Image](https://github.com/user-attachments/assets/09e8a1da-a3f9-4b27-a023-6ad5f62fe169)
