### ISSUE TITLE
Placeholder for multilingual support is displayed in the GitHub Pages documentation

### ISSUE THREAD

**Issue by takeshiemoto** [github/docs#32923]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I have confirmed a bug on the Japanese version of the 'About GitHub Pages' page, where the multilingual support placeholder is being displayed as is

https://docs.github.com/ja/pages/getting-started-with-github-pages/about-github-pages

<img width="1039" alt="image" src="https://github.com/github/docs/assets/45647252/557844dd-6c40-4a62-962c-fb421f4076a7">

I have confirmed that there is a problem in at least the following browsers.
- Chrome 124.0.6367.201（Official Build）（arm64）
- Safari 17.4.1
- FIrefox 125.0.3 

### What changes are you suggesting?

It should correctly display 'GitHub Pages'.

**Comment by nguyenalex836** [comment]
@takeshiemoto Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
