### ISSUE TITLE
Command is wrong and does not work correctly

### ISSUE THREAD

**Issue by la-png** [github/docs#33077]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection?platform=linux

### What part(s) of the article would you like to see updated?

The command in #2 is incorrect for all operating systems. This will not work. The English version is correct, so the omission may have occurred during translation.

`ssh -T git@`
`ssh -T git@github.com`

### Additional information

This problem occurs in the JA version and not in the EN version. Other languages have not been checked.

**Comment by nguyenalex836** [comment]
@la-png Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
