### ISSUE TITLE
The Japanese translation of “Pull request” is incorrect.

### ISSUE THREAD

**Issue by isso-719** [github/docs#33388]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- Example
  - https://docs.github.com/ja/get-started/using-github/github-flow#:~:text=%E7%99%BA%E7%94%9F%E3%81%97%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82-,%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A6%E3%82%A7%E3%82%B9%E3%83%88,-%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B

- Affected Articles (TOO MANY)
  - https://docs.github.com/ja/search?query=%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A6%E3%82%A7%E3%82%B9%E3%83%88

### What changes are you suggesting?

Pull request is called “プルリクエスト” in Japanese.
"プルリクウェスト" is an incorrect.

### Additional information

- InCorrect
<img width="784" alt="image" src="https://github.com/github/docs/assets/39211268/bb36bf27-95ae-4768-9ef9-78f78ec3b2c5">

- Correct
<img width="758" alt="image" src="https://github.com/github/docs/assets/39211268/fe91461b-be84-4633-a8dc-7e13f954607b">

**Comment by nguyenalex836** [comment]
@isso-719 Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
