### ISSUE TITLE
Package authentication documentation has confusing PAT wording

### ISSUE THREAD

**Issue by syntastical** [github/docs#33925]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry
https://docs.github.com/en/packages/learn-github-packages/publishing-a-package

### What changes are you suggesting?

Remove the reusable section that states 
`GitHub Packages only supports authentication using a personal access token (classic). For more information, see "[Managing your personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)."`. But this isn't true, and is directly contradicted by references to using `GITHUB_SECRET` in GitHub actions.

**Comment by nguyenalex836** [comment]
@syntastical Thank you for opening an issue and linking it to your PR! ✨

**Comment by yydslaomaque** [comment]
可以

**Comment by felicitymay** [comment]
@syntastical - thanks for raising this issue. It's always good to know when documentation is confusing.

The note that you find confusing is intended to explain that classic PAT can be used to access the package registry, but that fine-grained PATs are not supported. For information about the two types of tokens see: [Managing your personal access tokens - GitHub Docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens).

I think that the best solution here would be to update the text of the file that contains the note, rather than to delete the reference to the note: https://github.com/github/docs/blob/main/data/reusables/package_registry/packages-classic-pat-only.md?plain=1

I suggest that this amendment would be clearer. What do you think?
```
{% data variables.product.prodname_registry %} supports authentication using a {% data variables.product.pat_v1 %}. Authentication using {% data variables.product.pat_v2_plural %} is not supported. For more information, see "[AUTOTITLE](/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)."
```

Which should look like this:

> GitHub Packages supports authentication using a personal access token (classic). Authentication using fine-grained personal access tokens is not supported. For more information, see "[AUTOTITLE](/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)."

**Comment by felicitymay** [comment]
Someone else has raised an issue about this subject too and it's left me wondering what the accurate answer is here. I'm going to tag this for review by a subject matter expert.

**Comment by nguyenalex836** [comment]
@syntastical Hello! 👋 We received confirmation from an SME that GitHub Packages supports the legacy PAT and GITHUB_TOKEN, but no fine-grained access tokens. 

Once you have updated your [PR](https://github.com/github/docs/pull/33926/files) with the [guidance](https://github.com/github/docs/issues/33925#issuecomment-2225613443) @felicitymay provided above, we will be happy to get your PR merged 💛

**Comment by syntastical** [comment]
@nguyenalex836 sounds good, sorry I've been away. I'll circle back to this ASAP.
