### ISSUE TITLE
Error in Docs

### ISSUE THREAD

**Issue by everyofflineuser** [github/docs#34066]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Я обнаружил ошибку в GitHub Pages](https://docs.github.com/ru/get-started/exploring-integrations/github-developer-program)

### What part(s) of the article would you like to see updated?

![vivaldi_w9DabsCxee](https://github.com/user-attachments/assets/06f85bc0-e595-4292-8fd7-fb5bb57f061a)

**Comment by nguyenalex836** [comment]
@everyofflineuser Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
