### ISSUE TITLE
Specify definition of "updated"

### ISSUE THREAD

**Issue by jidanni** [github/docs#3406]
1.  Visit https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated
1. Wonder what the exact meaning of "updated" is.
2. Look in https://docs.github.com/en/github/getting-started-with-github/github-glossary -- No definition there either.

Therefore mention or link to somewhere that says e.g., "adding a comment updates an issue." or explicitly says it doesn't etc.

**Comment by Geno2tattedXXX** [comment]
![automerge](https://github.com/github/docs/actions/workflows/automerge.yml/badge.svg)

**Comment by Geno2tattedXXX** [comment]
![automerge](https://github.com/github/docs/actions/workflows/automerge.yml/badge.svg)

**Comment by Geno2tattedXXX** [comment]
> 1. Visit https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated
> 2. Wonder what the exact meaning of "updated" is.
> 3. Look in https://docs.github.com/en/github/getting-started-with-github/github-glossary -- No definition there either.
> 
> Therefore mention or link to somewhere that says e.g., "adding a comment updates an issue." or explicitly says it doesn't etc.

![automerge](https://github.com/github/docs/actions/workflows/automerge.yml/badge.svg)

**Comment by janiceilene** [comment]
👋 @jidanni The definition of the word "updated" varies within the docs, so we wouldn't add that to the glossary. In the article you linked, the section is talking about issues _and_ pull requests and there are a lot of ways those could be updated. It could be a comment, a commit, a suggestion, approval, etc. which is why we use the more generalized word "update." I'm going to close this issue now. Thanks for your passion and interest in the GitHub Docs!

**Comment by jidanni** [comment]
OK, it probably means anything that makes the webpage grow longer. Like adding a comment.
