### ISSUE TITLE
Team notifications being sent despite disabled in Team Settings

### ISSUE THREAD

**Issue by programarivm** [github/docs#34499]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/organizing-members-into-teams/configuring-team-notifications

https://github.blog/news-insights/introducing-team-mentions/

### What part(s) of the article would you like to see updated?

Hi there,

ChesslaBlab is a GitHub organization with over 1,000 people.

We're using team mentions once a month to send a notification to all members through GitHub Discussions, however, it seems as if everone is being notified when someone writes a new comment in the discussion. 

Is it documented how to disable notifications after the initial one has been sent? 

See https://github.com/orgs/chesslablab/discussions/435

Is this a bug or a feature?

Thanks for the help,

**Comment by jsoref** [comment]
Note to GitHub staff the `(Recommended)` suffix should be *removed* from any team with >20 members for exactly the reasons that caused this ticket to be opened. Instead, `Secret` should get the `(Recommended)` tag.

### References
* [Bedlam3](https://www.linkedin.com/pulse/surviving-bedlam3-email-storm-brought-down-microsoft-richard-bliss)

**Comment by nguyenalex836** [comment]
@programarivm Thank you for opening an issue! ✨ 

> however, it seems as if everone is being notified when someone writes a new comment in the discussion.
> Is it documented how to disable notifications after the initial one has been sent?
> Is this a bug or a feature?

It does not look like we currently have documentation on how to disable notifications after the initial notification has been sent, though this may be related to what the expected behavior of these notifications is. 

While our Docs team wouldn't be the best group to speak to expected behavior of these notifications, per the guidance from @jsoref, opening a [support ticket](https://support.github.com/contact/bug-report) with the context he provided would the best path toward determining what may be going wrong 💛  

If after reaching out to our Support team there are updates that should be made to these docs, please feel free to reopen this issue, and we can work together on updating them!
