### ISSUE TITLE
pnpm dependabot documentation incorrect

### ISSUE THREAD

**Issue by jamescrowley** [github/docs#34495]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories

### What part(s) of the article would you like to see updated?

This section: 
<img width="757" alt="Screenshot 2024-09-05 at 10 36 57" src="https://github.com/user-attachments/assets/4cd479d7-0f3f-43f2-914b-91d54b391faa">

shows security updates being supported for pnpm v7,8,9, but security updates are not supported for pnpm v9 (apparently GitHub has an internal ticket tracking this)

Also flagged here: https://github.com/dependabot/dependabot-core/issues/10534

**Comment by nguyenalex836** [comment]
@jamescrowley Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by subatoi** [comment]
@jamescrowley 👋 Thank you for this—for raising it and for the fact that you raised an issue first.

I've confirmed you're absolutely right, so we need to fix this. We're in a bit of an unusual situation as we're freezing the docs repo next week, so I wanted to get this fix in as soon as possible rather than opening it up to contributors. I thought about adding you as a co-committer but I noticed you don't make use of the no-reply function in your commits, so I didn't want to go ahead and do that without your permission.

You'll notice this issue close shortly when we merge in the fix, and the docs will reflect the change shortly thereafter.

Please do know that we really appreciate your help here—I'll just cc in @nguyenalex836 for 👀 as well.

**Comment by jamescrowley** [comment]
Cheers @subatoi 🙏 I didn’t actually know about the no-reply email option on github so thanks for sharing that too!
