### ISSUE TITLE
distributionManagement isn't really needed in the pom.xml file

### ISSUE THREAD

**Issue by sixcorners** [github/docs#34775]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-maven

### What part(s) of the article would you like to see updated?

Instead of messing with the distributionManagement xml element in the pom.xml file you could just change the mvn command to `mvn --batch-mode -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }} deploy`. It's way easier than copy/paste/editing the fragment of xml and integrating it into some kind of parent pom and keeping these ids in sync.
The user property is documented here: https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#altDeploymentRepository

I guess you could keep the distributionManagement stuff for people who prefer to do it that way.

**Comment by nguyenalex836** [comment]
@sixcorners Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by sixcorners** [comment]
I bet you could also put the altDeploymentRepository into the generated settings.xml file as a property in an activated by default profile. Not sure though

**Comment by Mohelgohary70** [comment]
[](url)

**Comment by Mohelgohary70** [comment]
content/admin/configuring-settings/configuring-private-networking-for-hosted-compute-products/index.md

**Comment by nguyenalex836** [comment]
Hello @sixcorners! Thank you for your patience while our SME team reviewed 💛 

Upon review, Our SME team found this change would have a few considerable impacts which we are unfortunately unable to investigate further right now due to bandwidth. While we are unable to accept this contribution at this time, we appreciate your willingness to contribute! 🙇

If you're looking for other issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues ✨ thanks again!
