### ISSUE TITLE
"Using workflow templates" not fully translated in Korean

### ISSUE THREAD

**Issue by chocoPenguin** [github/docs#34786]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ko/actions/writing-workflows/using-workflow-templates

### What part(s) of the article would you like to see updated?

This page's language is Korean, but mixed with English.
So hard to understand.
![image](https://github.com/user-attachments/assets/aa1922d3-c1de-499d-b8da-42ca35e02071)

**Comment by nguyenalex836** [comment]
@chocoPenguin Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1002636).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
