### ISSUE TITLE
`converted_to_discussion` event type incorrectly marked as unavailable in timeline events REST API

### ISSUE THREAD

**Issue by Fs00** [github/docs#35045]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types

### What part(s) of the article would you like to see updated?

The `converted_to_discussion` event type is flagged as unavailable for the timeline events API in the docs. However, this doesn't appear to be the case in practice, since the event can be seen in timeline API responses such as https://api.github.com/repos/servo/servo/issues/30494/timeline.
If this is confirmed to be the intended behavior (I would be surprised if it wasn't, at this point), I can open a PR to fix the article.

### Additional information

The documentation for the `converted_to_discussion` event type was added in PR #21028 by an external contributor. It is possible that the inconsistency above was introduced accidentally and slipped through the review.

**Comment by nguyenalex836** [comment]
@Fs00 Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by felicitymay** [comment]
@Fs00 - many thanks for highlighting this apparent bug in the docs and giving such a clear explanation.

Rather than thinking that the original contribution in 2022 might have been wrong, it seems possible that the event was added to the timeline more recently.

We've been steadily automating the generation of articles like this one because they are so difficult to maintain, but clearly this one has not yet been automated. For an example of a similar, automated file, see: [Webhook events and payloads](https://docs.github.com/en/webhooks/webhook-events-and-payloads), see source: https://github.com/github/docs/blob/main/content/webhooks/webhook-events-and-payloads.md?plain=1.

I checked the definition of the event in an internal repository to confirm your experience is correct ✅ 

If you have time to create a PR to fix this bug, that would be great.

**Comment by Fs00** [comment]
Thank you @felicitymay for your quick answer. I'll try to open a PR in the next few days to address the issue.
I agree with you that automatically generating that article's content should be the way to go. I've noticed that there are many issue event types that are returned by the API but aren't documented. When I find the time, I'll open another issue so that you don't lose track of the problem.
