### ISSUE TITLE
Support dark mode.

### ISSUE THREAD

**Issue by lc6464** [github/docs#3522]
### What is the current behavior?
The [https://docs.github.com](https://docs.github.com) website does not support dark mode.
Browser: `Microsoft Edge 88.0.705.63`

### What changes are you suggesting?
Hope to add support for dark mode.

### Additional information
Microsoft Edge supports dark mode CSS media queries.
![image](https://user-images.githubusercontent.com/64722907/107136017-a60fb900-693a-11eb-82bd-49c23d639357.png)

**Comment by chiedo** [comment]
@simpsoka FYI!

**Comment by simpsoka** [comment]
Thanks for opening this issue about dark mode for docs! 

This has [come up in the past](https://github.com/github/docs/issues/551#issuecomment-759777311), and we're actually in the middle of a site re-design, so we're rolling that out first and then we can look into supporting dark mode so that we get it to support the new design (not the old one). 

With the new design, we're also looking at modular CSS - which will also help with adding darkmode. So I'm going to close this out for now and then we can get it on our backlog!
