### ISSUE TITLE
Wrong description of the `Settings / Security / Code security` feature

### ISSUE THREAD

**Issue by akordowski** [github/docs#35325]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Multiple articles.

### What part(s) of the article would you like to see updated?

Regarding the issue #35324 I noticed that in the GitHub docs the **Settings / Security / Code security** feature is refered as "Code security and analysis". This term occurs 32 times over 19 files in the docs. This should be updated to the correct name "Code security".

### Additional information

I could provide a PR to fix this issues.

**Comment by nguyenalex836** [comment]
@akordowski Thank you for opening this issue and linking your PR! ✨ Once we've received a response from the team regarding the related issue - https://github.com/github/docs/issues/35324, we'll review this issue and PR as well 💛

**Comment by subatoi** [comment]
@akordowski 👋 Many apologies, but the comment I made here applies here too https://github.com/github/docs/issues/35324#issuecomment-2486234675

I'll discuss this internally as soon as I can, but because of the complications around versioning involved, I'm not sure if we'll be able to accept your PR.

However, I'd be happy to add you as a co-committer on any PRs we do raise. I'll leave this open for now, and we'll get back to you as soon as we can.

**Comment by akordowski** [comment]
@subatoi @nguyenalex836 As the PR is closed I close this issue as well.
