### ISSUE TITLE
GitHub Wiki does not support WikiMedia format links like the doc says

### ISSUE THREAD

**Issue by benelan** [github/docs#35396]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#adding-links

### What part(s) of the article would you like to see updated?

The GitHub documentation above says:
> With MediaWiki syntax, the link syntax is `[[Link Text|nameofwikipage]]`.

However, MediaWiki syntax would be `[[nameofwikipage|Link Text]]` according to their [documentation](https://www.mediawiki.org/wiki/Help:Links#Piped_links). 

Using the MediaWiki syntax for piped links does not work in GitHub wikis.

I would consider this a bug with the GitHub Wiki itself, as it should follow MediaWiki syntax to properly integrate with other tools. 

However, the documentation should at least make clear that GitHub's wiki link syntax does NOT align with the MediaWiki syntax.

**Comment by nguyenalex836** [comment]
@benelan Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by subatoi** [comment]
@benelan 👋 Thanks for raising this and thanks for raising an issue first. We really appreciate it.

You're quite correct—

1. Under "[Adding links](https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#adding-links)" we should change the wording to imply "one of the following formats", and change the bullet with the MediaWiki example accordingly.

1. Under "[Supported MediaWiki formats](https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#supported-mediawiki-formats)", we should remove the bullet that says "Links".

You're welcome to open a PR to fix this. Or, if you prefer that someone else does, we can open this up to contributors generally. 

If you're comfortable and you decide to raise a PR, I'd recommend that you mark it as "`closes`" this issue. Since we're only able to help in this repo in the context of problems with the docs, we can't guarantee a timeframe for a response about what may actually constitute a bug here. We'll raise your point internally and do our best to come back to you in this issue, even if it's closed, but you could also consider starting a discussion in https://github.com/orgs/community/discussions, or if your plan includes it, raising a ticket with GitHub Support.

If it's identified that this indeed a bug at a later time, we'll revert these changes.

Let me know what you think—thank you!

**Comment by nguyenalex836** [comment]
I've went ahead and added the `help wanted` label so that anyone in the community may open a PR for this update 💛
