### ISSUE TITLE
Update documentation for `git filter-branch`

### ISSUE THREAD

**Issue by joel-coffman** [github/docs#3617]
### What article on docs.github.com is affected?

[Removing sensitive data from a repository](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository)

### What part(s) of the article would you like to see updated?

The aforementioned article recommends using `git filter-branch` and BFG Repo-Cleaner to purge files from the repository's history and includes examples of how to use each tool. To the best of my knowledge, these commands work correctly, but Git's documentation for `git-filter-branch` includes the following [warning](https://git-scm.com/docs/git-filter-branch#_warning):

> **`git filter-branch`** has a plethora of pitfalls that can produce non-obvious manglings of the intended history rewrite (and can leave you with little time to investigate such problems since it has such abysmal performance). These safety and performance issues cannot be backward compatibly fixed and as such, its use is not recommended. Please use an alternative history filtering tool such as [git filter-repo](https://github.com/newren/git-filter-repo/).

Thus, it seems like GitHub might want to update its documentation to follow the current recommendation to use [git filter-repo](https://github.com/newren/git-filter-repo/).

### Additional information

I'm happy to contribute the necessary change that replaces the recommendation to use `git filter-branch` with `git filter-repo` following confirmation that it is desirable (i.e., I don't want to update the documentation if the change will never be accepted for some reason).

**Comment by janiceilene** [comment]
@joel-coffman Thank so much for opening an issue @joel-coffman! I'll triage this for the team to take a look 👀

**Comment by lee-dohm** [comment]
Thanks very much for the suggestion @joel-coffman!

While we share your concerns that `git filter-branch` can be challenging and problematic, we already have a third party tool, [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/), in the documentation that makes the process much simpler. The reason for keeping `git filter-branch` in there is so that there is a completely git-native method of achieving what people want if they're wary of using third-party tools. Replacing the one git-native method with a second third-party tool would remove that advantage.

Since we don't have any current complaints that the documentation as-is isn't working, we're going to err on the side of caution here and keep things as they are.

Thanks very much for your passion and interest in improving the GitHub official documentation!

**Comment by Florian-Schoenherr** [comment]
@lee-dohm 
I can share that I used git-filter-branch (due to it being non-third-party) but wasted several days on it. A team member then tried it with BFG instead, which worked in a matter of minutes.

**Comment by lee-dohm** [comment]
Thanks very much for that feedback @Florian-Schoenherr! It's quite helpful to the team to know what in our documentation works well for people as well as what could be improved. Thank you for taking the time to let us know 👍

**Comment by Florian-Schoenherr** [comment]
@lee-dohm thanks to you guys! (with all the spam-bots and stuff, it's probably pretty interesting to work on this lol)

**Comment by newren** [comment]
(Full disclosure: I'm the author of git filter-repo, so folks might consider me biased.  However, I have also contributed to git filter-branch, and have contributed many patches to git fast-export and fast-import among other areas in git.  Further, I think that removing the recommendation of git filter-branch, leaving only BFG Repo Cleaner as a recommended solution and not even mentioning git filter-repo would be a satisfactory resolution to this problem.  Mentioning/recommending git filter-repo would be nice, but by no means necessary.  However, I find the continued recommendation to use git filter-branch very problematic.)

> The reason for keeping `git filter-branch` in there is so that there is a completely git-native method of achieving what people want if they're wary of using third-party tools. Replacing the one git-native method with a second third-party tool would remove that advantage.
> 
> Since we don't have any current complaints that the documentation as-is isn't working, we're going to err on the side of caution here and keep things as they are.

The documentation as-is is dangerous.  git filter-branch will even tell folks so the instant they attempt to run it with any combination of flags:
```
$ git filter-branch -h
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as 'git filter-repo'
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
```
Pushing people to a tool with such warnings seems rather unfriendly.

Further, while the desire to use a 'git native' solution is understandable, I'm also curious what you will do when there is no git native solution?  This deprecation notice is there for a while, then the plan is to remove filter-branch from git.git[1][2] because it is unsafe to use.  It is also impossible to modify git filter-branch to make it safe without completely breaking backward compatibility[3].  You could recommend git filter-repo instead of git filter-branch, or you could just remove the git filter-branch recommendation and leave just BFG Repo Cleaner as the only recommended solution.  Either would be a dramatic improvement over the current page.

It appears this was closed under the pair of presumptions that the git project was merely recommending git filter-repo as a better tool than git filter-branch, and that git filter-branch will remain in git.git indefinitely.  If so, I think it should be reopened.  I believe both presumptions are false: git filter-branch is generally unsafe to use and has been declared as such, and the long term plan (after a sufficient deprecation notice) is still to remove git filter-branch from git.git.

[1] https://lore.kernel.org/git/xmqqlfvlne3k.fsf@gitster-ct.c.googlers.com/
[2] https://lore.kernel.org/git/a784a61e-1320-be1e-9dfb-d533a01827ec@gmail.com/
[3] https://lore.kernel.org/git/CABPp-BEDOH-row-hxY4u_cP30ptqOpcCvPibwyZ2wBu142qUbA@mail.gmail.com/

**Comment by lee-dohm** [comment]
Thanks for the extra info @newren and the detailed background!

I closed the issue for the following reasons:

1. The "better than `git filter-branch`" tool that we already have documented is one that the documentation team has vetted in the past, the GitHub Support staff is familiar with, and people have reported back to us that they've had success with
2. Some people are not comfortable with third party tools and want a completely git native solution, so we have documented `git filter-branch` instructions
3. While I know that nothing is "forever" in software, the git native solution is still available currently and we do recommend the safer option first

> It appears this was closed under the pair of presumptions that the git project was merely recommending git filter-repo as a better tool than git filter-branch, and that git filter-branch will remain in git.git indefinitely.

Neither of these entered my mind when deciding to close the issue. When deciding how to document a process, we're more motivated by trying to put ourselves into the mindset of the people that will consume the documentation and answer questions such as:
 
* Can the average reader understand and follow it?
* Will the reader follow the process or recommendations? (In other words, will they trust it?)

And when contemplating making changes, we have to take into consideration how often we'll have to update the documentation to keep it up-to-date, the support burden if people have questions about what the documentation recommends, etc. Consequently, this can make us somewhat risk-averse when considering changes, especially with regard to processes having to do with deleting content out of people's repositories. This will, obviously, nudge us toward erring on the side of caution.

So, I agree that the right thing to do is probably to remove the `git filter-branch` instructions when there is no longer a git native option. Unfortunately, because we know that some people will demand a git native solution if one exists, we will have to be honest and transparent and tell them that there is one, even if it is a bad one.

I hope that makes our thought processes more clear. Thanks again for sharing your expert insight and knowledge to help improve our docs!

**Comment by Florian-Schoenherr** [comment]
@lee-dohm not to sound condescending, but can you name me a "Some people"?
I don't have any insight into what people want of github, but if this is the sole reason why, can you share an example of that?
Maybe a discussion with some people who always want git-native, if any of them come to mind.
(And no, I don't want to argue with them 😅, I'm just baffled that this reasoning exists)

**Comment by lee-dohm** [comment]
@Florian-Schoenherr I don't have a public example handy and due to privacy concerns, even if I had a private example available, I wouldn't be able to give you a person's or company's name. I'm not sure if this is exactly what you meant but I wanted to be clear.

The examples that come to mind were employees of corporations that had strict security policies where new applications had to be approved, even for software developers. Since git had been previously approved for use and the third-party utilities for this purpose had not, only git-native solutions were acceptable.

I'm sure that, in this day and age of malware and even trusted software from major corporations being infused with malicious payloads, you can understand people wanting to be cautious what software they use to access or maintain their, often immensely valuable, intellectual property.

**Comment by Florian-Schoenherr** [comment]
@lee-dohm I had some kind of github issue in mind, but it would make sense that it's related to corporate stuff. Thanks for the clarification, now I get it. Have a nice day! 😄
