### ISSUE TITLE
"include all branches" option on creating a repository from a template REST endpoint

### ISSUE THREAD

**Issue by gijswijs** [github/docs#410]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-using-a-template

### What part(s) of the article would you like to see updated?

The functionality for [creating a repository from a template](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) supports a "include all branches" option, but the REST endpoint for that same functionality does not mention that option. Either this is because the REST endpoint actually *does not* support that option, in which case I think this should be mentioned in the docs, **OR** the endpoint *does* support this option, but the docs haven't been updated accordingly.

Either way I think the docs should be updated to reflect this.

**Comment by casals** [comment]
There's a preview notice on top of this subsection, linking it to last year's `baptiste-preview`. Probably any other previews (current and future) will contain only a subset of the web features at first, especially since there's a lot of bug squashing involved even for the basic features. In this case, there are still standing bugs with template repos (i.e. templates + classroom + assignments), and since this endpoint is marked as preview for almost an year I wouldn't expect any nem parameters so soon.

All that being said - IMHO perhaps what could help is a big note at the top of the API documentation stating that everything marked as preview might not reflect the full features you can find when using the web interface, or something like that.

**Comment by gijswijs** [comment]
> There's a preview notice on ~~top~~ of this subsection, linking it to last year's baptiste-preview

You mean bottom, right? 😄 

In the [old documentation](https://developer.github.com/v3/repos/#create-a-repository-using-a-template) the notice *was* at the top:

![image](https://user-images.githubusercontent.com/7912094/96062792-282a2c80-0ec9-11eb-8ed1-6654b9c94fcb.png)

But in the [new documentation](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-using-a-template) it is at the bottom.

It's way easier to overlook at the bottom. Should I create a new issue for placing he notices at the top?

**Comment by casals** [comment]
Oh - yeah, *top* - brain typo. :)

But absolutely - IMHO (i) each preview note box sould come at the top of each subsection and (ii) this warning box (from your screenshot) should be part of the note box, or at least follow the note bow for every subsection (case study: if someone get to a subsection in this page following an anchor link from a different page, they'll never see the top/bottom of the page, thus missing the -very important- warning). I'd say a new issue explaining this situation is necessary, yes.

**Comment by Psyruss** [comment]
https://github.community/t/greetings/92772?u=psyruss

**Comment by lucascosti** [comment]
@gijswijs Thanks for opening this issue

> The functionality for creating a repository from a template supports a "include all branches" option, but the REST endpoint for that same functionality does not mention that option. Either this is because the REST endpoint actually does not support that option, in which case I think this should be mentioned in the docs, OR the endpoint does support this option, but the docs haven't been updated accordingly.

I've just had a look at the endpoint code, and there is an undocumented parameter `include_all_branches` that is a boolean that controls that option.

Because the rest docs are generated from an internal source, I'll make the change internally to update the endpoint's docs.

Keep in mind that because this endpoint is still under preview, it's functionality might change in the future. 

> It's way easier to overlook at the bottom. Should I create a new issue for placing he notices at the top?

Thanks for this feedback. A new issue would be great.

**Comment by gijswijs** [comment]
I've created an issue for the UI with regards to the preview notice. See #980.

Great news about the undocumented parameter! For me this issue is closed now, but I'll let you decide whether you want to keep it open until you have updated the internal source.

**Comment by lucascosti** [comment]
> For me this issue is closed now, but I'll let you decide whether you want to keep it open until you have updated the internal source.

Thanks! I'll keep this issue open for our internal tracking. When it's fixed by the internal PR, it'll be closed (but it might take a few more days after that for the fix to appear in the live docs). 🙂

**Comment by gijswijs** [comment]
By the way, I tested the undocumented feature `include_all_branches` at the REST endpoint and it works!

**Comment by lucascosti** [comment]
Thanks again for this, @gijswijs. The updated docs should be rolling out now: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-using-a-template

🎉
