### ISSUE TITLE
Stop recommending to change git's default core.excludesfile setting

### ISSUE THREAD

**Issue by maruel** [github/docs#4137]
### What article on docs.github.com is affected?

content/github/using-git/ignoring-files.md

### What part(s) of the article would you like to see updated?

Leverage git's default core.excludesfile setting instead of telling users to change it, which leads to user confusion as seen on stack overflow. Searching on the web for [gitignore_global] tells several stories about this.

### Additional information

**Comment by Jeremiah-England** [comment]
I believe the SO question he is referring to is [here][1]. The top answer, like this documentation, does not mention that there is a default location that git already looks, presumably because the author didn't know. For a while now I've been explicitly configuring these files on my computer due to that answer.

Today reading the man pages I discovered that there was already a default location! That made me happy because it removes the extra step of explicitly declaring the config location when I setup Git on a computers now, and removes the slight overhead of deciding whether to use `~/.global_gitignore`, `~/.gitignore`, or whatever this time. My computers have ended up different here which I don't like. It also keeps my home directory a little cleaner. Putting it in the git directory in the user configurations directory seems like the right place, and I didn't think of that before.

I also understand why someone would not want to do that if they are not familiar with their user configurations directory. So it's worth mentioning that you can put it in your home directory or wherever you want with the config option. But I don't understand why it is not mentioned that there is a default location already. Is that just an oversite or do people think it's a bad location and that you shouldn't use it?

[1]: https://stackoverflow.com/questions/7335420/global-git-ignore

**Comment by hillearth** [comment]
J

**Comment by dalakatt** [comment]
- Jeremiah discussed the default location for git's core.excludesfile.
   - Jeremiah noted that the documentation and a top Stack Overflow answer
   omit the default location.
