### ISSUE TITLE
Document personal access token scopes for GitHub packages npm repo

### ISSUE THREAD

**Issue by skwashd** [github/docs#4244]
### What article on docs.github.com is affected?

https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages

### What part(s) of the article would you like to see updated?

The document makes multiple mentions of using a personal access token when authenticating. It doesn't mention what scopes are needed for the token. Having the minimum required scopes documented would be far better than generating a token then discovering that you got it wrong.

Gold star to the team who created the error message included with the 401 response. At least it tells me what scopes I need.

```
npm ERR! 401 Unauthorized - PUT https://npm.pkg.github.com/-/user/org.couchdb.user:skwashd - Error authenticating user: Personal Access Token is invalid. Your token must have the `repo` and read:packages` scopes to login to the GitHub Package Registry.
```

Adding this info would save anyone wanting to authenticate with packages repo a few minutes. They would no longer need to guess which scope/s their token needs.

I get including token scopes in an article talking about repo scopes can get confusion.

**Comment by janiceilene** [comment]
@skwashd Thanks so much for opening an issue! I'll triage this for the team to take a look 👀

**Comment by mattpollard** [comment]
👋🏻 Thanks for opening this issue and detailing your experience, @skwashd 🙇🏻 The article (and each client article in the "[Package client guides for GitHub Packages](https://docs.github.com/en/packages/guides/package-client-guides-for-github-packages)" map topic) begins with an "[Authenticating with a personal access token](https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#authenticating-with-a-personal-access-token)" section. The section specifies that...

> You must use a personal access token with the appropriate scopes to publish and install packages in GitHub Packages.

...and then links to the "About GitHub Packages" article's "[Authenticating to GitHub Packages](https://docs.github.com/en/packages/learn-github-packages/about-github-packages#authenticating-to-github-packages)" section, which includes an "[About scopes and permissions for package registries](https://docs.github.com/en/packages/learn-github-packages/about-github-packages#about-scopes-and-permissions-for-package-registries)" section. The section provides examples and lists the necessary scopes.

Since there are a variety of scopes and the information is relevant for all of the clients, we've structured the articles to lead with the high-level information on authentication, and then detail the client-specific instructions (as opposed to including all of the scope information throughout all of the articles).

Does that help? Let us know if you've got further thoughts on how we could improve this!
