### ISSUE TITLE
values for `failed_reason` are not documented

### ISSUE THREAD

**Issue by asdkant-ey** [github/docs#4423]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/orgs#list-failed-organization-invitations
repo link: https://github.com/github/docs/blob/main/content/rest/reference/orgs.md

### What part(s) of the article would you like to see updated?

In **List failed organization invitations**, the possible values of the `failed_reason` field in each object of the returned list are not documented. It would be useful to know the possible values (my team is writing a self-service web app so users can ask for invitations to be re-sent, and we don't have much context to understand the importance of reading that field and using the information contained)

**Comment by skedwards88** [comment]
@asdkant-ey Here is the information you are looking for:

"no_more_seats": "No seats available."
"trade_controls": "This user isn't able to use this feature due to trade regulations."
"already_accepted": "Invitation already accepted."
"invalid_generic": "Invitation is invalid."
"expired": "Invitation expired. User did not accept this invite for 7 days."

This addition to the docs would need to be made internally, so I will close this issue and open an internal issue. Thank you for your suggestion!
