### ISSUE TITLE
dotnet repos without a package

### ISSUE THREAD

**Issue by 89z** [github/docs#4505]
This page:

https://docs.github.com/en/packages/guides/configuring-dotnet-cli-for-use-with-github-packages

is helpful if the repo owner has created a GitHub package. However not all projects do that, example:

https://github.com/BackInBash/DeezerAPI

so how would one install from a GitHub repo that has not created a package?

**Comment by 89z** [comment]
Here is what I came up with. First download the Zip file from GitHub and extract. Then navigate to the directory containing `Something.csproj`. Then run:

~~~
dotnet pack -o ..
~~~

Then navigate out of this package, and run:

~~~
dotnet new console -o myApp
~~~

Finally, run:

~~~
dotnet add package Something -s ..
~~~

https://docs.microsoft.com/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli

**Comment by janiceilene** [comment]
Thanks for opening an issue @89z! I'll triage this for the team to take a look 👀

**Comment by lee-dohm** [comment]
Hello @89z ! Thanks very much for reaching out.

I can see how this information would be useful in some contexts. However, the documentation page in question is specifically about GitHub Packages and because of this we believe that including your suggested information would distract from the intended use for the page. It would also not be properly searchable if we kept this information in this page. For these reasons, this isn't a change that we would accept. If you find a better place for this information, please do open a new issue.

In the future, please fill out the issue template. This helps us triage issues more efficiently which allows us to get back to people faster, merge PRs more rapidly, and spend less time on the overhead of keeping things neat and tidy.

Thanks very much for your passion and interest in improving the GitHub Documentation!
