### ISSUE TITLE
Add procedural section on how to star repos

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4853]
Issue originally reported/written by @ethanpalm. ✨ 

### What article on docs.github.com is affected?

"[Saving repositories with stars](https://docs.github.com/en/github/getting-started-with-github/saving-repositories-with-stars)"

### What part(s) of the article would you like to see updated?

Currently, "[Saving repositories with stars](https://docs.github.com/en/github/getting-started-with-github/saving-repositories-with-stars)" does not document how to star a repository. New users might not know how to do this procedure and they would expect to find the procedure in this article. To address this, we will add a procedural section in this article that instructs people on how to star a repo.

The audience is new GitHub users and existing users who haven't used stars.

#### Content to update

"[Saving repositories with stars](https://docs.github.com/en/github/getting-started-with-github/saving-repositories-with-stars)"
- [ ] Add procedural section after "About stars" titled "Starring a repository"
  - [ ] Explain the process for starring a repository
  - [ ] Include screenshots where needed to show the procedure

For more information on contributing to this repository, see [CONTRIBUTING.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md)

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by thepushkarp** [comment]
Hey @emilyistoofunky, I'd like to work on this issue.

I also noticed that the screenshots on this page from of the older GitHub UI. Shall I work on updating them as well?

**Comment by emilyistoofunky** [comment]
> I also noticed that the screenshots on this page from of the older GitHub UI. Shall I work on updating them as well?

@thepushkarp Sure, that would be great! Make sure your screenshots don't share any personal information. Under the "[Browsing your friends' stars](https://docs.github.com/en/github/getting-started-with-github/saving-repositories-with-stars#browsing-your-friends-stars)", let's delete that screenshot instead of replacing it. 

Let us know if you have any questions about updating screenshots. ⚡

**Comment by thepushkarp** [comment]
Hey @emilyistoofunky, while working on this, after deleting the screenshot under the "[Browsing your friends' stars](https://docs.github.com/en/github/getting-started-with-github/saving-repositories-with-stars#browsing-your-friends-stars)", I realized that the UI hasn't changed much for the other screenshots and they are still relevant.

The most drastic change was in the profile icons that changed from square to round but since we are not including that screenshot, I felt that the other ones would be fine.

But if we do need to update them, I can make another quick commit in the same PR. Let me know what are your thoughts on this.

**Comment by emilyistoofunky** [comment]
Great catch @thepushkarp. It sounds fine to not update those other screenshots. ⚡
