### ISSUE TITLE
Content updated for GitHub Education's Docs Page

### ISSUE THREAD

**Issue by bassa846** [github/docs#5212]
### What article on docs.github.com is affected?

**About GitHub Campus Program**

_Moderator's note:_ Updated to point to publicly accessible info.

~~We would like to update the [docs page](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/about-github-campus-program) by including the [information here](https://docs.google.com/document/d/1iH1mM2jTTqggvpnfDpRG5QTMBTQV2UwvBtwjnD8t10Y/edit#)~~

We would like to update the [docs page](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/about-github-campus-program) by making [the changes listed in the comment below](https://github.com/github/docs/issues/5212#issuecomment-824442186). 

### What part(s) of the article would you like to see updated?

We want to include questions and answer that we see asked very often. Our program is moving to a self-serve model.
To help support the self-serve model, we want to link our GitHub Docs page with updated content tp our main GitHub Campus Program page. 

### Additional information

@emilyistoofunky mentioned that  we don't use FAQs as a content type on our docs, so would likely rework the information into a format we use. This is perfectly fine with us 👍

**Comment by janiceilene** [comment]
Thanks so much for opening a new issue @bassa846! I'll get this triaged for the team to take a look 👀

**Comment by danna527** [comment]
> ### Какая статья на docs.github.com затронута?
> **О программе GitHub Campus**
> Мы хотели бы обновить [страницу документации](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/about-github-campus-program) , включив [сюда информацию](https://docs.google.com/document/d/1iH1mM2jTTqggvpnfDpRG5QTMBTQV2UwvBtwjnD8t10Y/edit#) .
> 
> ### Какие части статьи вы хотели бы видеть обновленными?
> Мы хотим включить вопросы и ответы, которые нам задают очень часто. Наша программа переходит на модель самообслуживания.
> Чтобы помочь поддерживать модель самообслуживания, мы хотим связать нашу страницу GitHub Docs с обновленным контентом с нашей главной страницей программы GitHub Campus.
> 
> ### Дополнительная информация
> @emilyistoofunky упомянул, что мы не используем часто задаваемые вопросы в качестве типа контента в наших документах, поэтому, скорее всего, мы переработаем информацию в формат, который мы используем. Нас это устраивает👍

**Comment by skedwards88** [comment]
@bassa846 Thank you for opening this issue! 💖 Since the google doc linked in the issue body is not accessible to the public, I have summarized the additions below. I omitted information that is already discoverable elsewhere in the docs and isn't as directly relevant to the GitHub Campus Program. Please comment if I missed or misunderstood anything!

You or anyone else is welcome to open a PR to address these changes.

The [About GitHub Campus Program - GitHub Docs](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/about-github-campus-program) article should be expanded to include this info:

- To the list of what the GitHub Campus Program includes, add "50,000 GitHub Actions minutes and 50GB GitHub Packages storage"
- After the sentence, "Teacher training to master Git and GitHub with our Campus Advisor program," link to the [campus advisor article](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/about-campus-advisors).
- After the list of what the GitHub Campus Program includes, add a paragraph about the licenses.
  - the licenses are for use by the whole school
  - Internal IT departments, academic research groups, collaborators, students, and other non-academic departments are eligible to use the licenses so long as they are not making a profit from its use.
  - Externally funded research groups that are housed at the university may not use the free licenses.
  - The license is free for one year and will automatically renew for free every 2 years. You may continue on the free license so long as you continue to operate within the terms of the agreement.
- Mention that if your school does not issue email addresses, GitHub will reach out to your account administrators with an alternative option to allow you to distribute the student developer pack to your students.
- Add a paragraph about administrating the account:
  - New organizations in your enterprise are automatically added to your enterprise account. To add organizations that existed before your school joined the GitHub Campus Program, please contact [GitHub Support](https://support.github.com/contact). For more information about administrating your enterprise, see "[Setting up and managing your enterprise](https://docs.github.com/en/github/setting-up-and-managing-your-enterprise)."
- To the section that says, "Any school that can agree to the terms of the program is welcome to join", add:
  - Often, a campus CTO/CIO, dean, department chair, or technology officer signs the terms of the program on behalf of the campus.
  - You must offer GitHub to all of your technical and academic departments
  - Your school’s logo will be shared on the [GitHub Education](https://education.github.com/schools) website as a GitHub Campus Program Partner
  - To read more about GitHub's privacy practices, see "[Global Privacy Practices](https://docs.github.com/en/github/site-policy/global-privacy-practices)"
- In the paragraph that says, "individually apply for discounts to use GitHub", link to https://education.github.com/discount_requests/new
- Add a sentence like, "To read about how GitHub is used by educators, see [GitHub Education stories](https://education.github.com/stories)."

**Comment by bassa846** [comment]
@skedwards88 This is perfect! You captured everything.
The only thing that needs to be changed is the link to **_please Contact GitHub Support._**
The education team has a different link for our support channel, which is https://support.github.com/contact/education.

**Comment by skedwards88** [comment]
> The only thing that needs to be changed is the link to please Contact GitHub Support.
> The education team has a different link for our support channel, which is https://support.github.com/contact/education.

Thanks for pointing this out! I edited my comment to include the correct support link.

**Comment by bassa846** [comment]
Hey @skedwards88 😄 
Just checking in to see when the content will be finalized and live on the GitHub Education Docs Page? I still have an [open PR ](https://github.com/github/docs/pull/2172)on this project.

Any updates would be appreciated ❤️

**Comment by janiceilene** [comment]
👋 @bassa846 I'm so sorry about the miscommunication! After the content strategy was written, we thought you all were going to open a PR with the changes. We've added it to the project board for the campus experts to pick up during the program they're currently working on with us 💛 

If it's time sensitive, you're welcome to open a PR to get it merged in sooner! Thank you so much for collaborating with us to improve the education docs!

**Comment by bassa846** [comment]
@janiceilene thanks for your quick reply! I totally overlooked, @skedwards88 comment "You or anyone else is welcome to open a PR to address these changes." sorry about that.

I've gone ahead and [opened a PR](https://github.com/github/docs/pull/6401) to get it merged sooner 😄
