### ISSUE TITLE
Please add how to link forked repo to a project board 

### ISSUE THREAD

**Issue by poovanna886** [github/docs#523]
Add steps to docs.github.com on how to link a forked repo to a project

**Comment by janiceilene** [comment]
👋 @poovanna886 Thanks for opening an issue! Please update this issue using the [content issue template](https://raw.githubusercontent.com/github/docs/main/.github/ISSUE_TEMPLATE/improve-existing-docs.md) to help everyone understand exactly what you're looking for 💛

**Comment by poovanna886** [comment]
---
name: Improve existing docs
about: Add steps on how to link a forked repo to a project board in github.
title: ''
labels:
- content
assignees: ''
---




### What article on docs.github.com is affected?


https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-repository-to-a-project-board
### What part(s) of the article would you like to see updated?


Adding a forked repo to a project can be of immense help to developers so please add this feature on github

### Additional information

**Comment by felicitymay** [comment]
👋🏻 Hi @poovanna886 

Thanks for raising this issue and for adding the extra detail to explain the change that you'd like to see. I'm going to check in with our engineers to find out whether it's possible to add a fork to a project board. It may be disabled because forks often behave differently from other repositories.

**Comment by felicitymay** [comment]
👋🏻 @poovanna886

I talked to the engineers who work on project boards and it seems as if you've uncovered a bug. This is now raised in an internal issue.

Thank you for reporting this problem 🙇🏻‍♀️

**Comment by felicitymay** [comment]
👋🏻 @poovanna886 🎉 

Hi, I have better news. Another engineer on the team asked me to check whether I'd enabled issues for the forked repository, and it turned out that I hadn't. I've updated the comment above with the new information to reduce confusion of anyone else who comes across this issue. You should find that you can link your forked repository to a board if you follow the instructions above first 😄

**Comment by felicitymay** [comment]
### Content design plan

Proposed content design plan to address this issue.

When I looked more closely at [Linking a repository to a project board](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-repository-to-a-project-board), I realized that it already had a note box at the start of the topic that I had entirely overlooked. While it doesn't mention forked repositories, it does explain that only repositories with issues enabled are available to be added. I think that it would be helpful to reposition the note closer to where you are linking repositories, so that it provides troubleshooting assistance and expand it to mention that issues are disabled by default for forks.

Topics to update: 

- [Linking a repository to a project board](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-repository-to-a-project-board)
    - Move the note box from the start of the topic, to just before the "Further reading" heading, so that it's clearly visible while you are reading step 6.
    - Expand the information in the note to explain that issue are disabled by default on forked repositories.
    - Mention that you can check whether issues are enabled for a repository by checking for an "Issues" tab on the main repository page. (The existing suggestion is only possible for repository administrators and this is a simpler check.)
    - Revise the text: *"For information on how to see if issues are disabled for a repository, see"* to something more like *"For information on how to enable or disable issues for a repository, see"*

**Comment by poovanna886** [comment]
Thank you for looking into it! @felicitymay

**Comment by shades-7** [comment]
Hey can I work on this?

**Comment by felicitymay** [comment]
Hi @shades-7 👋🏻 

I'm not aware of anyone else working on this, so that would be great. 

You may want to check the [CONTRIBUTING guide](https://github.com/github/docs/blob/main/CONTRIBUTING.md) for tips, tricks, and things to be sure you do when submitting PRs to the project.

Thanks for the interest!

**Comment by GitauHarrison** [comment]
> 👋🏻 @poovanna886
> 
> I talked to the engineers who work on project boards ~and it seems as if you've uncovered a bug. This is now raised in an internal issue.~
> 
> _Update: One of the engineers later pointed out the fact that you can only add a repository to a project board if issues are enabled for that repository. Forks are created with issues disabled. I hadn't realized this, but it makes sense._
> 
> To enable issues on a forked repository:
> 
> 1. Go to the forked repo.
> 2. Click **Settings**.
> 3. On the Options page, under "Features", check the box next to **Issues**.
> 
> After this, you should find that you can link the repository to your project board in the normal way. I tried this out and it worked for me.
> 
> Thank you for reporting this problem, I'll write a content design plan to update the documentation here to help other users of forks. 🙇🏻‍♀️

I am trying to link my fork to such a repo (private - I have been added as a collaborator to a repo and the related project board) following this guideline:

> 3. On the Options page, under "Features", check the box next to **Issues**.

After refreshing, I still cannot see the link pop up in my fork. 

![no_link](https://github.com/user-attachments/assets/e5c6d23c-91c6-4d25-b71f-678eb4c441c3)

The **Issues** section is checked as recommended.

![checked_issues](https://github.com/user-attachments/assets/8946a875-bbf4-4b1f-85c8-d2f13e15342c)

What could I be missing? I have also followed [this article](https://docs.github.com/en/enterprise-server@3.15/issues/organizing-your-work-with-project-boards/managing-project-boards/linking-a-repository-to-a-project-board) but it is not clear. I intend to see this board live as it is on the main/original repo so I can update it from my fork.

**Comment by felicitymay** [comment]
@GitauHarrison 👋🏻 

This issue is from 2020 and projects have changed a lot since then.

The article that you looked at: [Linking a repository to a project (classic) - GitHub Enterprise Server 3.15 Docs](https://docs.github.com/en/enterprise-server@3.15/issues/organizing-your-work-with-project-boards/managing-project-boards/linking-a-repository-to-a-project-board) is intended for users of GitHub Enterprise Server 3.15 who want to link to a Classic Project.

If you are using GitHub.com, then these instructions are outdated because [Classic Projects have been retired on this platform](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/). The new projects work in a different way from the classic projects. The most similar article I can find is: [Adding your project to a repository - GitHub Docs](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/adding-your-project-to-a-repository). Since it states: _"You can only list projects that are owned by the same user or organization that owns the repository."_ this doesn't seem possible for forked repositories.

I'd recommend asking this question in our community: https://github.com/orgs/community/discussions/categories/projects-and-issues.
