### ISSUE TITLE
Incorrect type for `labels` parameter: "array of undefineds"

### ISSUE THREAD

**Issue by gr2m** [github/docs#549]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#create-an-issue

### What part(s) of the article would you like to see updated?

1. https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#update-an-issue--parameters
2. https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#create-an-issue--parameters

The `labels` parameter's type is listed as `array of undefineds`

### Additional information

<img width="760" alt="image" src="https://user-images.githubusercontent.com/39992/96091537-95fd3680-0e7e-11eb-945a-8ed932e06d83.png">

**Comment by janiceilene** [comment]
Thanks for opening an issue @gr2m 💝

**Comment by casals** [comment]
This seems to be a bit more complicated than content only:

- The content page where the issue is perceived (`docs/edit/main/content/rest/reference/issues.md`) uses an specific include for describing REST operations (`docs/includes/rest_operation.html`);
-The include file above programatically parses the operation descriptions contained in the npm package[ `@github/rest-api-operations`](https://www.npmjs.com/package/@github/rest-api-operations);
- While the referenced repository for this package (https://github.com/github/rest-api-operations) is not publicly available, you can find the same descriptions at https://github.com/github/rest-api-description (was the first deprecated in favor of the latter?)
-  According to the related operation description contained in [`api.github.com.json`](https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json) (line 29364), the `labels` parameter is an array that requires *either* a `string` or an object with multiple parameters.

My guess is that the property parsing mechanism doesn't do well with the `oneOf` array property (which establishes the *either* condition), so it returns `array of undefined` as the property type for `labels` (should be: something like `array of string OR object`).

@janiceilene perhaps the best course of action ehre would be to re-triage this to engineering - what do you think?

**Comment by gr2m** [comment]
Amazing analysis 👍🏼

**Comment by runleonarun** [comment]
@casals and @gr2m 
It looks like you're correct:
```            items:
              oneOf:
                - type: string
                - type: object
```

I will discuss it with the Docs Ecosystem team and triage it on our project board to get it fixed.

**Comment by rachmari** [comment]
@gr2m, this looks like a bug with our internal schema. I don't think we allow creating an issue with an array of label objects only an array of strings. I'm going to verify this with the owner of the API.

**Comment by janiceilene** [comment]
This has been moved to our internal repo, so I'm going to close out this PR. Thank so much!
