### ISSUE TITLE
docs are incorrect for creating webhooks

### ISSUE THREAD

**Issue by kplimack** [github/docs#6060]
### What article on docs.github.com is affected?
https://docs.github.com/en/rest/reference/repos#create-a-repository-webhook

### What part(s) of the article would you like to see updated?

The `events` for which a webhook are mapped are in the top level of the JSON data, but the docs show it in the "Config" hash.

according to the docs, I would do this:
```
{
  "name": "web",
  "config": {
    "url": "https://webhook.service.com/token",
    "insecure_ssl": "0",
    "events": [
      "deployment",
      "pull_request",
      "push"
    ],
    "active": true
  }
}
```
However when I do that, I get this response:
```
{
  "type": "Repository",
  "id": 74,
  "name": "web",
  "active": true,
  "events": [
    "push"
  ],
  "config": {
    "active": "1",
    "events": "[\"deployment\", \"pull_request\", \"push\"]",
    "insecure_ssl": "0"
  }
}
```

When I shift my events to the top level of the JSON, I get what I would expect
```
{
  "type": "Repository",
  "id": 76,
  "name": "web",
  "active": true,
  "events": [
    "deployment",
    "pull_request",
    "push"
  ],
}
```

I am unclear how these docs are autogenerated, or I would take a stab at the PR.

**Comment by ajs256** [comment]
The API docs are auto-generated from an internal repo. A GitHub staff member will usually raise an issue internally once they see this.

**Comment by lucascosti** [comment]
Hi @kplimack, thanks for opening this issue!

It looks like you might be misreading the parameters table. The `events` and `active` properties aren't documented as part of the `config` object, but are top-level parameters. 

![image](https://user-images.githubusercontent.com/4434330/117222974-08039000-ae50-11eb-86ee-cf8b75d34fc3.png)

When the `config` object's properties are expanded, I can definitely understand how the presentation of the child table of the `config` row might not be totally clear:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/4434330/117223206-82ccab00-ae50-11eb-9228-438f263f5f5b.png">

Because the documented properties are correct, I'll close this issue. We have plans to show better example request bodies for our API documentation, but you are welcome to open a new issue for us to look at improving the way that the child table is presented 🙂
