### ISSUE TITLE
Intro for software supply chain map topic

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#6284]
### What article on docs.github.com is affected?

The “[Understanding your software supply chain](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain)” map topic (a map topic is a task-based group of articles)

### What part(s) of the article would you like to see updated?

Write an intro to help orient users to the content on the page. Intros are also displayed in search results. Intros should be one sentence long. For more information on writing intros, see:
- [Information about map topics](https://github.com/github/docs/blob/main/contributing/content-model.md#map-topic)” in the GitHub Docs content model, including guidance on map topic intros
- [Information about writing intros](https://github.com/github/docs/blob/main/contributing/content-model.md#intro) in the GitHub docs content model
- [Information about the `intro` frontmatter property](https://github.com/github/docs/tree/main/content#intro) in the GitHub Docs content directory README
- Make sure your intro is general enough to cover the content in each version of the page (use the version picker in the upper-right corner of the page to see what’s included on the page for different versions of GitHub)

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by mrarif6585** [comment]
https://github.com/github/docs/projects/2#card-60913203

**Comment by dani3lcruise** [comment]
> ### What article on docs.github.com is affected?
> 
> The “[Understanding your software supply chain](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain)” map topic (a map topic is a task-based group of articles)
> ### What part(s) of the article would you like to see updated?
> 
> Write an intro to help orient users to the content on the page. Intros are also displayed in search results. Intros should be one sentence long. For more information on writing intros, see:
> 
>     * [Information about map topics](https://github.com/github/docs/blob/main/contributing/content-model.md#map-topic)” in the GitHub Docs content model, including guidance on map topic intros
> 
>     * [Information about writing intros](https://github.com/github/docs/blob/main/contributing/content-model.md#intro) in the GitHub docs content model
> 
>     * [Information about the `intro` frontmatter property](https://github.com/github/docs/tree/main/content#intro) in the GitHub Docs content directory README
> 
>     * Make sure your intro is general enough to cover the content in each version of the page (use the version picker in the upper-right corner of the page to see what’s included on the page for different versions of GitHub)
> 
> 
> ### Additional information
> 
> This issue is for a special project and is not currently available for contributors to work on.

I could fix this issue with maps in an Macbook controller but my mac's health is not good so keeping put will solve this issue soon once again it opens up

**Comment by dani3lcruise** [comment]
sry a*
macbook

**Comment by elsaxo** [comment]
Gg

**Comment by ivan0117** [comment]
https://github.com/github/docs/projects/2#card-60913203

**Comment by dani3lcruise** [comment]
It's not spam I have to provide the proof from my end will disclose at the right time

**Comment by dc3327** [comment]
Glad to be here . Even though we have never met , we all are familiar with oneanother to a loose extent . I did have several attempts on  my well being in physical form but the world is sick 😷  in nearly every way.   Eyes are everywhere and  always were  . COVID19 , is horrible . It would be much worse to waste an opportunity in the chaos.  A cure  .... Go play in  the sandbox  build  own castle , own shovel  until  the  manufacturer  recalls to avoid  legal cost but owning the right to manufacturer the box means no sandbox is safe . Pixel profiles are history of  creator  and the soul  of an individual.  Human Capital is the  new pink diamond  and more a pink diamond is displayed as wealth of power  but control  over the world and all that is in it including  your intell prop  used for slowing advancement of humanity  more so than  they willing know now . I think you all deserve a  medal for the risk associated with your profession  . Oh i looked at  how game servers  are being uaed to create  and isolate at least 7 stains of covid  ..  In a lab , its surely secure lol  i really see  value in all of this , if you let  me i will ride  the pale horse in the 6.5 metre radius of any other entities  the impede what you do . In many ways . Only jokes  i hate text i could  of handwritten  this  in a third of the time.  Thanks for being nice to the 007 happy guy hahaha . Whatever. Lots of reading 📚  for me

**Comment by deka981** [comment]
Pada tanggal Min, 25 Jul 2021 23.52, dc3327 ***@***.***>
menulis:

**Comment by fh11882** [comment]
- - [ ] []()

**Comment by Amirnateghi19800** [comment]
#11792

**Comment by cadamini** [comment]
maybe something like this?

> The software supply chain is your own software but also 3rd party libraries and containers that impact your software creation and deployment.

**Comment by Dlocc23** [comment]
> ``

**Comment by Garouaoui** [comment]
.

**Comment by Kroner414** [comment]
Hmm

**Comment by cmwilson21** [comment]
Looks like this has been fixed. Closing this issue now.

**Comment by nastyook-babel** [comment]
---
title: GitHub Mobile
intro: 'Triage, collaborate, and manage your work on {% data variables.product.github %} from your mobile device.'
shortTitle: GitHub Mobile
versions:
  fpt: '*'
  ghes: '*'
  ghec: '*'
redirect_from:
  - /get-started/using-github/github-for-mobile
  - /github/getting-started-with-github/github-for-mobile
  - /github/getting-started-with-github/using-github/github-for-mobile
category:
  - Customize your experience
---

## About {% data variables.product.prodname_mobile %}

{% data reusables.mobile.about-mobile %}

{% data variables.product.prodname_mobile %} gives you a way to do high-impact work on {% data variables.product.github %} quickly and from anywhere. {% data variables.product.prodname_mobile %} is a safe and secure way to access your data through a trusted, first-party client application.

With {% data variables.product.prodname_mobile %} you can:

* Manage, triage, and clear notifications
* Read, review, and collaborate on issues and pull requests
* Edit files in pull requests
* Search for, browse, and interact with users, repositories, and organizations
* Receive a push notification when someone mentions your username{% ifversion mobile-code-search %}
* Search through code in a specific repository{% endif %}{% ifversion fpt or ghec %}
* Secure your {% data variables.product.prodname_dotcom_the_website %} account with two-factor authentication
* Verify your sign in attempts on unrecognized devices{% endif %}{% ifversion copilot-chat-for-mobile %}
* Use {% data variables.copilot.copilot_chat %} to ask and receive answers to coding-related questions{% endif %}

The following documentation contains more information about using {% data variables.product.company_short %} features on {% data variables.product.prodname_mobile %}.

* Notifications for {% data variables.product.prodname_mobile %}, see [AUTOTITLE](/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#enabling-push-notifications-with-github-mobile).{% ifversion mobile-code-search %}
* Using {% data variables.product.prodname_dotcom %} code search on {% data variables.product.prodname_mobile %}, see [AUTOTITLE](/search-github/github-code-search/using-github-code-search#using-github-code-search-on-github-mobile).{% endif %}{% ifversion fpt or ghec %}
* Two-factor authentication using {% data variables.product.prodname_mobile %}, see [AUTOTITLE](/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication#configuring-two-factor-authentication-using-github-mobile) and [Authenticating using {% data variables.product.prodname_mobile %}](/authentication/securing-your-account-with-two-factor-authentication-2fa/accessing-github-using-two-factor-authentication#verifying-with-github-mobile). {% endif %}{% ifversion copilot-chat-for-mobile %}
* Using {% data variables.copilot.copilot_mobile %}, see [AUTOTITLE](/copilot/github-copilot-chat/copilot-chat-in-github-mobile/using-github-copilot-chat-in-github-mobile).{% endif %}{% ifversion copilot-chat-for-mobile %}
* Assigning issues to {% data variables.product.prodname_copilot_short %} from {% data variables.product.prodname_mobile %}, see [AUTOTITLE](/copilot/how-tos/use-copilot-agents/cloud-agent/start-copilot-sessions).{% endif %}

## Installing {% data variables.product.prodname_mobile %}

To install {% data variables.product.prodname_mobile %} for Android or iOS, see [{% data variables.product.prodname_mobile %}](https://github.com/mobile).

## Managing accounts

You can be simultaneously signed into mobile with multiple accounts on {% data variables.product.prodname_dotcom_the_website %}, on {% data variables.enterprise.data_residency_site %}, and on {% data variables.product.prodname_ghe_server %}. For more information about our different products, see [AUTOTITLE](/get-started/learning-about-github/githubs-plans).

{% data reusables.mobile.push-notifications-on-ghes %}

{% data variables.product.prodname_mobile %} may not work with your enterprise if you're required to access your enterprise over VPN.

### Signing in with social login

> [!NOTE]
> Social login is only available for {% data variables.product.prodname_free_user %} and {% data variables.product.prodname_ghe_cloud %} users

You can sign in to {% data variables.product.prodname_mobile %} using a supported social login provider. Currently, both Google and Apple are supported for social login on the {% data variables.product.prodname_mobile %} for Android and iOS users. To use this option, make sure you originally created your {% data variables.product.github %} account using the respective social login provider - Google or Apple.

### Prerequisites for {% data variables.enterprise.data_residency_site %} accounts

To access accounts on {% data variables.enterprise.data_residency %} using {% data variables.product.prodname_mobile %}, you need to install {% data variables.product.prodname_mobile %} with at least version iOS 1.182.0 or Android 1.178.0.

### Prerequisites for {% data variables.product.prodname_ghe_server %} accounts

You must install {% data variables.product.prodname_mobile %} 1.4 or later on your device to use {% data variables.product.prodname_mobile %} with {% data variables.product.prodname_ghe_server %}.

To use {% data variables.product.prodname_mobile %} with {% data variables.product.prodname_ghe_server %}, {% data variables.product.prodname_dotcom %} must be version 3.0 or greater, and your enterprise owner must enable mobile support for your enterprise. For more information, see {% ifversion ghes %}[AUTOTITLE](/admin/release-notes) and {% endif %}[Managing {% data variables.product.prodname_mobile %} for your enterprise]({% ifversion not ghes %}/enterprise-server@latest{% endif %}/admin/configuration/configuring-your-enterprise/managing-github-mobile-for-your-enterprise){% ifversion not ghes %} in the {% data variables.product.prodname_ghe_server %} documentation.{% else %}.{% endif %}

During the {% data variables.release-phases.public_preview %} for {% data variables.product.prodname_mobile %} with {% data variables.product.prodname_ghe_server %}, you must be signed in with a personal account on {% data variables.product.prodname_dotcom_the_website %}.

### Adding, switching, or signing out of accounts

You can sign into mobile with any {% data variables.product.github %} account, on {% data variables.product.prodname_dotcom_the_website %}, on {% data variables.enterprise.data_residency_domain %}, or on {% data variables.product.prodname_ghe_server %}. At the bottom of the app, long-press **{% octicon "person" aria-hidden="true" aria-label="person" %} Profile**, then tap **{% octicon "plus" aria-hidden="true" aria-label="plus" %} Add Enterprise Account**. Follow the prompts to sign in.

After signing in with a second account, you can switch between the accounts you're currently logged into within the app. At the bottom of the app, long-press **{% octicon "person" aria-hidden="true" aria-label="person" %} Profile**, then tap the account you want to switch to.

If you no longer need to access an account using {% data variables.product.prodname_mobile %}, you can sign out of that account. At the bottom of the app, long-press **{% octicon "person" aria-hidden="true" aria-label="person" %} Profile**, swipe left on the account to sign out of, then tap **Sign out**.

Alternatively, once logged into one account, access the account switcher to log into other accounts or log out of an existing account by navigating to the **{% octicon "person" aria-hidden="true" aria-label="person" %} Profile** tab, then tapping {% octicon "gear" aria-hidden="true" aria-label="gear" %}, and then tapping **Manage Accounts**.

## Supported languages for {% data variables.product.prodname_mobile %}

{% data variables.product.prodname_mobile %} is available in the following languages.

* English
* Spanish
* Japanese
* Brazilian Portuguese
* Simplified Chinese
* Korean
* German

If you configure the language on your device to a supported language, {% data variables.product.prodname_mobile %} will default to the language. You can change the language for {% data variables.product.prodname_mobile %} in {% data variables.product.prodname_mobile %}'s **Settings** menu.

## Managing Universal Links for {% data variables.product.prodname_mobile %} on iOS

{% data variables.product.prodname_mobile %} automatically enables Universal Links for iOS. When you tap any {% data variables.product.github %} link, the destination URL will open in {% data variables.product.prodname_mobile %} instead of Safari. For more information, see [Universal Links](https://developer.apple.com/ios/universal-links/) on the Apple Developer site.

To disable Universal Links, long-press any {% data variables.product.github %} link, then tap **Open**. Every time you tap a {% data variables.product.github %} link in the future for the same {% data variables.product.github %} instance, the destination URL will open in Safari instead of {% data variables.product.prodname_mobile %}.

To re-enable Universal Links, long-press any {% data variables.product.github %} link, then tap **Open in {% data variables.product.github %}**.

## Sharing feedback

You can submit feature requests or other feedback for {% data variables.product.prodname_mobile %} on [{% data variables.product.prodname_github_community %}](https://github.com/orgs/community/discussions/categories/mobile).

## Opting out of {% data variables.release-phases.public_preview %} releases for iOS

If you're testing a {% data variables.release-phases.public_preview %} release of {% data variables.product.prodname_mobile %} for iOS using TestFlight, you can leave the {% data variables.release-phases.public_preview %} at any time.

1. On your iOS device, open the TestFlight app.
1. Under "Apps," tap **{% data variables.product.prodname_dotcom %}**.
1. At the bottom of the page, tap **Stop Testing**.
