### ISSUE TITLE
::set-output does not document that `value` cannot contain newlines

### ISSUE THREAD

**Issue by jsoref** [github/docs#6693]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

### What part(s) of the article would you like to see updated?

It should indicate that `value` cannot contain newlines.

### Additional information

https://github.community/t/use-ssh-key-from-secret-in-output-set-output/141071/2
https://github.community/t/set-output-truncates-multiline-strings/16852/3

### Content design plan

- Document the solution from https://github.community/t/set-output-truncates-multiline-strings/16852/3 in https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter.

**Comment by 111mma** [comment]
ctf

**Comment by janiceilene** [comment]
Thanks for opening an issue @jsoref! I'll triage this for the team to take a look 👀

**Comment by NhatMode** [comment]
ok

**Comment by lecoursen** [comment]
Thanks @jsoref! The solution in https://github.community/t/set-output-truncates-multiline-strings/16852/3 would be good to document. You or anyone else is welcome to do so!

**Comment by jsoref** [comment]
@lecoursen: I found the solution so icky that I didn't want to be blamed for documenting it (c.f. https://github.community/t/set-output-truncates-multiline-strings/16852/5), hence just filing a bug asking that it be documented as opposed to writing the documentation. 

That said, once it is officially documented, I'll be quite happy to point to it / rely on it to work 😄 .

**Comment by Benzfccr7** [comment]
ตรวจสอบไฟ

**Comment by jsoref** [comment]
Sigh

**Comment by Muhammad-Saleem1Ch** [comment]
thanks for sharing alot of information

**Comment by mark-mxwl** [comment]
It seems that in the time since this issue was posted, it has been solved with the introduction of [GITHUB env files](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). Substituting `set-output` with `$GITHUB_OUTPUT`, in conjunction with a delimiter, allows for multiline output. These options are already documented in the two sections immediately preceding the one linked to this issue.


Ref closed issue #21529 with regard to using a delimiter for multiline output.

As there is a [planned deprecation](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/) for the `set-output` command, I would recommend that this issue be marked as closed.
