### ISSUE TITLE
Shortcuts not working in projects tab

### ISSUE THREAD

**Issue by jelizarovas** [github/docs#6712]
### What is the current behavior?

`j` or `k`, or any of the keys work on selecting any of the project boards, or columns within the project. Open selection, or toggle selection are also not working on this tab

![image](https://user-images.githubusercontent.com/15138718/119283400-c0238d80-bbf1-11eb-98e8-d001c03504f6.png)

### What changes are you suggesting?

1. Add support for `j` `k` to navigate projects and `x`/ `o` to open them would improve keyboard workflow.

2. Add shortcut to focus and navigate columns (possibly `shift `+ `c`) 
3. adding a card (`c`), 
4. removing a card (`backspace `or `delete`)

5. While having a card issue opened in the side panel with shortcut `d`, to be able to open the issue with `o`

**Comment by janiceilene** [comment]
👋 @jelizarovas This repo is only for the content and source code for docs.github.com. It looks like your issue is about github.com. The best place to send your feedback is to https://support.github.com/contact/feedback 💛 I'm going to close this now, but let me know if there were docs updates you were looking for!
