### ISSUE TITLE
Missing headers on webhooks?

### ISSUE THREAD

**Issue by ScottChapman** [github/docs#7005]
during development of a webhook app, I saw some headers that weren't documented. Specifically I saw `x-request-id` and I got that confused with `x-hub-delivery`
@gr2m  ^^

**Comment by janiceilene** [comment]
👋 @ScottChapman Thanks so much for opening an issue! Which article on docs.github.com were you expecting to see those headers in?

**Comment by ScottChapman** [comment]
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#delivery-headers

**Comment by gr2m** [comment]
ref https://github.com/octokit/webhooks.js/issues/579

I've also seen `x-request-start`, which seems like the timestamp from which the 10s timeout is counted?

**Comment by janiceilene** [comment]
Thanks @ScottChapman and @gr2m! I'll get this triaged for review 🎉

**Comment by lee-dohm** [comment]
:wave: Hello @ScottChapman. Thanks for reaching out.

In the future, please fill out the issue template when opening an issue. It helps us triage things easier, means we don't have to go back and forth to get all the required information, and it ensures that anyone that contributes a PR based on your issue has all the information needed in one place without having to go through the entire list of comments attached in order to get started.

@gr2m Do you have any idea if the `x-request-id` and `x-request-start` headers are included in all webhooks or if they are only included in some webhooks what subset they apply to? Any addition to this table will need to indicate to the reader which is applicable.

Let us know!

**Comment by gr2m** [comment]
> @gr2m Do you have any idea if the `x-request-id` and `x-request-start` headers are included in all webhooks or if they are only included in some webhooks what subset they apply to?

I don't know, I was hoping you'd be able to find out easily with the webhooks team?

@wolfy1339 maintains webhook schemas and examples at https://github.com/octokit/webhooks, but we don't track headers at this point. @wolfy1339 do you have any insights on @lee-dohm's question?

**Comment by wolfy1339** [comment]
I've never seen any of these headers myself.
I also don't keep track of headers on the receiving end of webhooks.

**Comment by lee-dohm** [comment]
Thanks for touching base @gr2m and @wolfy1339. I'll check with the team and see if we can get more information. Unfortunately, I can't commit to when the engineering team will be able to prioritize this.

Thanks for your patience.

**Comment by lecoursen** [comment]
Hi @ScottChapman! Sorry for the delay here! I'm going to close this issue and track the missing headers internally. Tracking down all possible headers and when they are expected will require coordination with engineering, so this can't really be addressed here. Thanks for letting us know about it!
