### ISSUE TITLE
eval builtin (SSH)

### ISSUE THREAD

**Issue by fnise-urt** [github/docs#7194]
### What article on docs.github.com is affected?

[Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

### What part(s) of the article would you like to see updated?

generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

```diff
-   # start the ssh-agent in the background
+   # use the builtin to start the agent
```

start_ssh_agent.md

```diff
- 1. Start the ssh-agent in the background.
+ 1. Use the builtin to start the agent.
```

### Additional information

In the words of one OpenSSH developer.

"ssh-agent -s prints out the environment variable settings, which MUST  
be evaluated into the current shell environment for future children to  
collect those options"

**Comment by fnise-urt** [comment]
@lecoursen

start_ssh_agent.md

What circumstance requires sudo to start ssh-agent?

**Comment by lecoursen** [comment]
> What circumstance requires sudo to start ssh-agent?

Before https://github.com/github/docs/pull/7074, "Generating a new SSH key and adding it to the ssh-agent" included this:

>In some Linux environments, you need root access to run the command

I actually wasn't involved in the addition of that line. I did triage https://github.com/github/docs/pull/6782, which reported that some environments require `exec ssh-agent bash` or `exec ssh-agent zsh` instead of `eval "$(ssh-agent -s)"`.

It's not possible for us to cover every possible environment and the corresponding required commands in our docs. Now, we're doing our best to clarify that users need to start the SSH agent, but the exact commands they need to do that may vary. We include a few examples but won't be able to exhaustively list every situation in which each should be used.

**Comment by fnise-urt** [comment]
The GitHub docs would be technically correct with the textual changes.

For comparison running `ssh-agent xterm &` would "start the ssh-agent in the background".

Could a Member elucidate why a Linux sys admin would require sudo (or which Linux distro required sudo).

@lecoursen

The OP cited .md files' recent changes I have noted.

**Comment by fnise-urt** [comment]
I don't see the purpose for adding the `exec ssh-agent $SHELL` content.

Nobody's opened an issue regarding difficulty with the eval builtin.

If no Members can come up with an explanation for the sudo content one could add this change to the update.

start_ssh_agent.md  

```diff
-     Depending on your environment, you may need to use a different command. For example, you may need to use root access by running `sudo -s -H` before starting the ssh-agent, or you may need to use `exec ssh-agent bash` or `exec ssh-agent zsh` to run the ssh-agent.
+     The `ssh-agent -s` prints out environment variable settings that are treated as shell input.
```

**Comment by fnise-urt** [comment]
https://github.com/github/docs/issues/7194#issue-915442961

generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

This might be added at the end of the same section.

The `ssh-agent -s` prints out environment variable settings that are treated as shell input.

**Comment by fnise-urt** [comment]
@lecoursen 

> I actually wasn't involved in the addition of that line.

in https://github.com/github/docs/commit/ac50aa437ba195e2b755679265466db732d4dcad you took Linux content and applied it also to Mac

**Comment by Twelvesuns** [comment]
- [ ] Goos job@![image](https://user-images.githubusercontent.com/33124419/121795606-f8c7ed00-cc1a-11eb-9dfc-03438a081574.jpeg)

**Comment by Syahril92** [comment]
> * [x]  Goos job@![image](https://user-images.githubusercontent.com/33124419/121795606-f8c7ed00-cc1a-11eb-9dfc-03438a081574.jpeg)

Nice

**Comment by fnise-urt** [comment]
@janiceilene

You're welcome to invite me to collaborate on the docs repository.

Then I could hide off-topic comments on issues and PR's that I open.

Windows 10 since 1803 has included openssh-portable.

The docs provide info solely on the 'Git for Windows' (dependent on  msys-2.0.dll) implementation.

Is there Member interest to review the Windows openssh-portable?

**Comment by MhdAmr788** [comment]
Stop controlling person. You really know the true story?

**Comment by lee-dohm** [comment]
Hello @fnise-urt, thanks for reaching out.

Upon review, we don't believe that the suggested change will improve understanding for the majority of users of the GitHub documentation. Because of this, we're going to close the issue.

Thanks for your passion and interest in making the GitHub docs better!

**Comment by fnise-urt** [comment]
@lee-dohm

> docs would be technically correct with the textual changes.
