### ISSUE TITLE
GPG keys: add about how to save passphrase against typing it on every commit

### ISSUE THREAD

**Issue by vitaly-zdanevich** [github/docs#7323]
### What article on docs.github.com is affected?
https://github.com/github/docs/blob/main/content/github/authenticating-to-github/managing-commit-signature-verification/signing-commits.md

### What part(s) of the article would you like to see updated?

Near `To store your GPG key passphrase so you don't have to enter it every time you sign a commit, we recommend using the following tools:` add about Linux, how to configure `gpg-agent` (as I tried it will start automatically after first commit, without any configuration), and how to not enter passphrase even for the first time.

**Comment by fnise-urt** [comment]
At minimum `man gpg-agent` and `info gnupg` might be reviewed by STAFF.

**Comment by janiceilene** [comment]
👋 @vitaly-zdanevich Please fill out the [issue template](https://github.com/github/docs/blob/main/.github/ISSUE_TEMPLATE/improve-existing-docs.md) in the top comment in this issue and then I can get this triaged for you 💛 

The issue template helps us triage things easier, means we don't have to go back and forth to get all the required information, and it ensures that anyone that contributes a PR based on your issue has all the information needed in one place without having to go through the entire list of comments attached in order to get started.

**Comment by vitaly-zdanevich** [comment]
@janiceilene done

**Comment by Jahlll** [comment]
Done

**Comment by janiceilene** [comment]
Thanks @vitaly-zdanevich! I'll triage this for the team to take a look 👀

**Comment by lecoursen** [comment]
Thanks @vitaly-zdanevich, that sounds like useful information to include. Because that tip box is already quite long, we should remove the callout (so the existing content it just regular text) and add an "About commit signatures" header above all the conceptual content, which will mean also adding a "Signing commits" header to the procedure content as well. You or anyone else is welcome to open a PR doing that. ⚡
