### ISSUE TITLE
Following Github Actions tutorial but getting an npm EACCES error

### ISSUE THREAD

**Issue by jsoref** [github/docs#7866]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow

### Additional information

https://github.com/jsoref/188088/runs/2965080849?check_suite_focus=true

I followed the instructions:
1. I created a repository https://github.com/jsoref/188088
2. I went to https://github.com/jsoref/188088/new/main?filename=.github%2Fworkflows%2Fblank.yml&workflow_template=blank
3. I copy and pasted the filename and the contents from the help page
4. I clicked start commit
5. I pasted the url into the commit
6. I waited for the action to run and checked the results

It fails:
https://github.com/jsoref/188088/runs/2965080849?check_suite_focus=true

Precisely as reported here:
https://github.community/t/following-github-actions-tutorial-but-getting-an-npm-eacces-error/188088/1

Yes. I know how to do this right, but I should be able to follow the instructions (as @seddonr faithfully attempted) and get a working product.

**Comment by janiceilene** [comment]
Thanks for opening an issue @jsoref! Is there a particular update you'd like to see? Any suggestions?

**Comment by jsoref** [comment]
I'm not sure. One approach is to suggest using `npm bin` and adding that to the `PATH` using `GITHUB_ENV `and then *not* using `-g`.

There are other strategies. I don't want to be too prescriptive as in this area I don't necessarily go down the path most trodden.

Another involves using `sudo`.

And another involves the other thing that the reporter tried for which I filled the next ticket about `GITHUB_ENV` instructions being incomplete.

**Comment by jsoref** [comment]
#7892

**Comment by lucascosti** [comment]
Thanks a lot for reporting this, @jsoref!

This issue is seems to be caused by the recent update of `actions/setup-node` to `v2`, which now prefers a `node-version` to be specified.

If I add a `node-version` to the workflow, it works:

Workflow: https://github.com/lucascosti/actions-public-playground/blob/85f97785dc883e5007634bd3e9c529a4a2d5fe03/.github/workflows/intro_article_test.yml
Workflow run: https://github.com/lucascosti/actions-public-playground/runs/3053584138?check_suite_focus=true

I'll update the example to get this working again 👍

**Comment by gsteele178** [comment]
Well let's open her back up lol
