### ISSUE TITLE
How to resolve large filenames?

### ISSUE THREAD

**Issue by lucalves** [github/docs#8318]
### What is the current behavior?

Hello everyone, everything good?

I'm trying to contribute to the repository, but I can't even checkout a branch as there is a problem with files with very long names.

When I try to checkout a new branch, I come across the following:

![hotfix](https://user-images.githubusercontent.com/17712401/126021841-c5143abf-2d95-49db-aaa2-255b34f67550.png)

What would be the solution to resolve this and return to checkout normally? Before, I remember that I was able to create a branch and checkout without any problems.

### What changes are you suggesting?

I don't know a solution at the moment, I would like an opinion from the repository maintainers.

**Comment by radiohazard-dev** [comment]
This issue seems to stem from Windows; on Linux, those paths resolve just fine. [This StackOverflow answer](https://stackoverflow.com/a/22575737) explains what's going wrong under the hood, but enabling `core.longPaths` should fix it this time:
```
git config core.longpaths true
```
You may experience some glitches with git in scripts in other projects, but if you'd like to enable that globally, you can add `--system` or `--global`.

**Comment by lucalves** [comment]
I believe this command solved the problem. Thanks @radiohazard-dev!
