### ISSUE TITLE
Invalid `raw` markers in code samples

### ISSUE THREAD

**Issue by oliversalzburg** [github/docs#8339]
### What is the current behavior?

Invalid `{% raw %}` markers are left in content, confusing users.

See: https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages

### What changes are you suggesting?

I don't know. I would assume whatever is supposed to handle those needs markers some fixing.

### Additional information

I've only seen this on that one page and am assuming it's a more widespread issue, because I couldn't see any obvious errors in the page source code.

**Comment by oliversalzburg** [comment]
Oh baby, I feel so engaged. ❤️

**Comment by ramyaparimi** [comment]
@oliversalzburg Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by oliversalzburg** [comment]
@ramyaparimi I feel like the issue might actually have been specific to that one page. When I looked into it, the source code didn't seem to match up with the page though. I figured it's best for someone else to check it out. Cheers

**Comment by ramyaparimi** [comment]
@oliversalzburg Thanks so much for catching this error!! I checked it out and here is how it can be fixed.

This issue is in a reusable that is linked in this comment. 
Line #36 in this reusable has `{% endraw %}` missing at the end of the line. Adding that in the place of `{% raw %}` should fix the error. Here is the link to the reusable https://github.com/github/docs/edit/main/data/reusables/package_registry/publish-docker-image.md

You or anyone else can feel free to open a PR for this issue 👍 ✨

**Comment by oliversalzburg** [comment]
Awesome. Thanks for the help. I have opened the PR just now.
