### ISSUE TITLE
Describe how to re-request a review

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#897]
### What article on docs.github.com is affected?

I think we should update one of the subsections belonging to this main section:

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests

### What part(s) of the article would you like to see updated?

**Why should the docs be changed?**

I can't find anything in the GitHub docs about re-requesting a review??? I would expect it to be in one of the articles in the *Reviewing changes in pull requests* section, but I can't find it there at all.

**What use cases does it support?**

This should be documented somewhere, so that repository maintainers can link to this section to explain how "re-requesting an review" works.

This also exposes this functionality to anyone who reads the GitHub docs, that way they can "stumble into" this functionality.

**Expected outcome**

There is a section in the GitHub docs that explains that you can click on the refresh icon next to a review, to ping the reviewer for a fresh review.

### Additional information

See the image below for an example of the refresh icon that I'm talking about:

> ![image](https://user-images.githubusercontent.com/1798109/97479196-432d7f80-1952-11eb-883e-2cd8ebd633dd.png)

**Comment by janiceilene** [comment]
👋 @HonkingGoose I don't see anything about re requesting a PR review either! It sounds to me like you're interested in an addition that focuses on a contributor requesting an additional review after they've made changes in an already reviewed PR. Is that right?

The article you linked to above ☝️ [Reviewing changes in pull requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests) is aimed at the reviewer, so I don't think that's quite the right place for this information to live.

What about adding it to either [About pull request reviews](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews)? Or maybe [Incorporating feedback in your pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request), since that article focuses on how to apply suggested changes and open an issue for out of scope suggestions?

**Comment by HonkingGoose** [comment]
First of all, thanks for the quick response! :smile: 

> It sounds to me like you're interested in an addition that focuses on a contributor requesting an additional review after they've made changes in an already reviewed PR. Is that right?

Yes, that's right! :smile: 

> The article you linked to above :point_up: Reviewing changes in pull requests is aimed at the reviewer, so I don't think that's quite the right place for this information to live.

Agree, it should go somewhere else.

> What about adding it to either About pull request reviews? 

Sounds good to me, I think I like this place better than " Incorporating feedback in your pull request", as that seems to me more focused on the review feedback. I can see the case for both places though.

I think some keywords should be: "refresh review", "ping for a fresh review", "re-request review", I think things like that are what people would be search for. I know I typed in "re-request review" and "request review" to try to find this documentation.

**Comment by janiceilene** [comment]
The hover text says "re-request review," so I think that's what we should use here. I think it'd be beneficial to add the information to both articles. So what we can do is create a new reusable in https://github.com/github/docs/tree/main/data/reusables/pull_requests that includes:

- a sentence or two about why someone would want to re-request a review (like after making substantial changes) 
- a quick explanation of how to re-request a review, using the sync [octicon](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#octicons)

We can add a new section called "Re-requesting reviews" to the [About pull request reviews](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request) article after the "Resolving conversations" section with that reusable. We can also add a new section and reusable to [Incorporating feedback in your pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request) after the procedural, above the "Opening an issue for an out-of-scope suggestion" section.

Anyone is welcome to open a PR implementing that plan if you want to!

**Comment by HonkingGoose** [comment]
I'll go make a PR request for this then. :+1:
