### ISSUE TITLE
Incorrect Use of HTML Code for Apostrophe

### ISSUE THREAD

**Issue by CharlieMoon37** [github/docs#9485]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- **[Index File](https://github.com/github/docs/blob/main/content/organizations/managing-peoples-access-to-your-organization-with-roles/index.md)**
- **[Site](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles)**

![image](https://user-images.githubusercontent.com/74975634/131706597-86a2a090-f85b-4799-9f27-8fc509e9efd2.png)

### What changes are you suggesting?

The title should remove the HTML Apostrophe Code

**Comment by ramyaparimi** [comment]
@CharlieMoon37 
Thanks so much for opening an issue! You or anyone is welcome to open a PR with the fix ⚡ 🐬

**Comment by simonsabin** [comment]
This issue applies to any index.md file that has a title containing a '

It looks like the issue is in  https://github.com/github/docs/blob/d07d253daff9b5b2149a2172713da1874316f7e0/components/context/TocLandingContext.tsx#L36 in comparing with ArticleContext.tsx this should be `reg.context.page.titlePlainText`
